/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BracketTournamentOutput,
  CreateBracketRequest,
  HTTPValidationError,
  SetBracketMatchRequest,
  SetBracketRevealAtRequest,
} from '../models/index';
import {
    BracketTournamentOutputFromJSON,
    BracketTournamentOutputToJSON,
    CreateBracketRequestFromJSON,
    CreateBracketRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SetBracketMatchRequestFromJSON,
    SetBracketMatchRequestToJSON,
    SetBracketRevealAtRequestFromJSON,
    SetBracketRevealAtRequestToJSON,
} from '../models/index';

export interface CreateBracketApiBracketPostRequest {
    createBracketRequest: CreateBracketRequest;
}

export interface GetBracketApiBracketGetRequest {
    preview?: boolean;
}

export interface SetBracketMatchApiBracketMatchIdPostRequest {
    matchId: string;
    setBracketMatchRequest: SetBracketMatchRequest;
}

export interface SetBracketRevealAtApiBracketRevealAtPostRequest {
    setBracketRevealAtRequest: SetBracketRevealAtRequest;
}

/**
 * 
 */
export class BracketApi extends runtime.BaseAPI {

    /**
     * Creates request options for createBracketApiBracketPost without sending the request
     */
    async createBracketApiBracketPostRequestOpts(requestParameters: CreateBracketApiBracketPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createBracketRequest'] == null) {
            throw new runtime.RequiredError(
                'createBracketRequest',
                'Required parameter "createBracketRequest" was null or undefined when calling createBracketApiBracketPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/bracket`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBracketRequestToJSON(requestParameters['createBracketRequest']),
        };
    }

    /**
     * Create (or replace) the bracket with these 9-16 seeded entrants.
     * Create Bracket
     */
    async createBracketApiBracketPostRaw(requestParameters: CreateBracketApiBracketPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BracketTournamentOutput>> {
        const requestOptions = await this.createBracketApiBracketPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BracketTournamentOutputFromJSON(jsonValue));
    }

    /**
     * Create (or replace) the bracket with these 9-16 seeded entrants.
     * Create Bracket
     */
    async createBracketApiBracketPost(requestParameters: CreateBracketApiBracketPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BracketTournamentOutput> {
        const response = await this.createBracketApiBracketPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for eligiblePlayersApiBracketEligiblePlayersGet without sending the request
     */
    async eligiblePlayersApiBracketEligiblePlayersGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/bracket_eligible_players`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Known player names - the pool admins pick the 9-16 entrants from.
     * Eligible Players
     */
    async eligiblePlayersApiBracketEligiblePlayersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string | null>>> {
        const requestOptions = await this.eligiblePlayersApiBracketEligiblePlayersGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Known player names - the pool admins pick the 9-16 entrants from.
     * Eligible Players
     */
    async eligiblePlayersApiBracketEligiblePlayersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string | null>> {
        const response = await this.eligiblePlayersApiBracketEligiblePlayersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getBracketApiBracketGet without sending the request
     */
    async getBracketApiBracketGetRequestOpts(requestParameters: GetBracketApiBracketGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['preview'] != null) {
            queryParameters['preview'] = requestParameters['preview'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/bracket`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The current bracket tournament, or None if none has been created yet.  Before ``reveal_at``, player placements are withheld from the response (see ``_build_output_from_states``) - only the roster and blank bracket shape are visible. ``preview=true`` bypasses that gate, but only for a logged-in tournament admin; it\'s a per-request opt-in (an admin\'s own \"peek early\" button), not a way to reveal the bracket for everyone.
     * Get Bracket
     */
    async getBracketApiBracketGetRaw(requestParameters: GetBracketApiBracketGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BracketTournamentOutput>> {
        const requestOptions = await this.getBracketApiBracketGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BracketTournamentOutputFromJSON(jsonValue));
    }

    /**
     * The current bracket tournament, or None if none has been created yet.  Before ``reveal_at``, player placements are withheld from the response (see ``_build_output_from_states``) - only the roster and blank bracket shape are visible. ``preview=true`` bypasses that gate, but only for a logged-in tournament admin; it\'s a per-request opt-in (an admin\'s own \"peek early\" button), not a way to reveal the bracket for everyone.
     * Get Bracket
     */
    async getBracketApiBracketGet(requestParameters: GetBracketApiBracketGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BracketTournamentOutput> {
        const response = await this.getBracketApiBracketGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setBracketMatchApiBracketMatchIdPost without sending the request
     */
    async setBracketMatchApiBracketMatchIdPostRequestOpts(requestParameters: SetBracketMatchApiBracketMatchIdPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['matchId'] == null) {
            throw new runtime.RequiredError(
                'matchId',
                'Required parameter "matchId" was null or undefined when calling setBracketMatchApiBracketMatchIdPost().'
            );
        }

        if (requestParameters['setBracketMatchRequest'] == null) {
            throw new runtime.RequiredError(
                'setBracketMatchRequest',
                'Required parameter "setBracketMatchRequest" was null or undefined when calling setBracketMatchApiBracketMatchIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/bracket/{match_id}`;
        urlPath = urlPath.replace(`{${"match_id"}}`, encodeURIComponent(String(requestParameters['matchId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetBracketMatchRequestToJSON(requestParameters['setBracketMatchRequest']),
        };
    }

    /**
     * Update a match\'s scheduled date / best-of / score (admin only).  PATCH semantics: only fields present in the request body change; omitted fields keep their stored values, and an explicit null clears a field.
     * Set Bracket Match
     */
    async setBracketMatchApiBracketMatchIdPostRaw(requestParameters: SetBracketMatchApiBracketMatchIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BracketTournamentOutput>> {
        const requestOptions = await this.setBracketMatchApiBracketMatchIdPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BracketTournamentOutputFromJSON(jsonValue));
    }

    /**
     * Update a match\'s scheduled date / best-of / score (admin only).  PATCH semantics: only fields present in the request body change; omitted fields keep their stored values, and an explicit null clears a field.
     * Set Bracket Match
     */
    async setBracketMatchApiBracketMatchIdPost(requestParameters: SetBracketMatchApiBracketMatchIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BracketTournamentOutput> {
        const response = await this.setBracketMatchApiBracketMatchIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setBracketRevealAtApiBracketRevealAtPost without sending the request
     */
    async setBracketRevealAtApiBracketRevealAtPostRequestOpts(requestParameters: SetBracketRevealAtApiBracketRevealAtPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['setBracketRevealAtRequest'] == null) {
            throw new runtime.RequiredError(
                'setBracketRevealAtRequest',
                'Required parameter "setBracketRevealAtRequest" was null or undefined when calling setBracketRevealAtApiBracketRevealAtPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/bracket/reveal_at`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetBracketRevealAtRequestToJSON(requestParameters['setBracketRevealAtRequest']),
        };
    }

    /**
     * Set (or clear, with null) when the bracket becomes publicly visible.
     * Set Bracket Reveal At
     */
    async setBracketRevealAtApiBracketRevealAtPostRaw(requestParameters: SetBracketRevealAtApiBracketRevealAtPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BracketTournamentOutput>> {
        const requestOptions = await this.setBracketRevealAtApiBracketRevealAtPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BracketTournamentOutputFromJSON(jsonValue));
    }

    /**
     * Set (or clear, with null) when the bracket becomes publicly visible.
     * Set Bracket Reveal At
     */
    async setBracketRevealAtApiBracketRevealAtPost(requestParameters: SetBracketRevealAtApiBracketRevealAtPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BracketTournamentOutput> {
        const response = await this.setBracketRevealAtApiBracketRevealAtPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
