/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  MatchupCommentaryPromptPreview,
  MatchupCommentaryRequest,
  MatchupCommentaryResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MatchupCommentaryPromptPreviewFromJSON,
    MatchupCommentaryPromptPreviewToJSON,
    MatchupCommentaryRequestFromJSON,
    MatchupCommentaryRequestToJSON,
    MatchupCommentaryResponseFromJSON,
    MatchupCommentaryResponseToJSON,
} from '../models/index';

export interface GetMatchupCommentaryApiMatchupCommentaryPostRequest {
    matchupCommentaryRequest: MatchupCommentaryRequest;
}

export interface GetMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequest {
    player1: string;
    player2: string;
    roundName: string;
}

/**
 * 
 */
export class CommentaryApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMatchupCommentaryApiMatchupCommentaryPost without sending the request
     */
    async getMatchupCommentaryApiMatchupCommentaryPostRequestOpts(requestParameters: GetMatchupCommentaryApiMatchupCommentaryPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['matchupCommentaryRequest'] == null) {
            throw new runtime.RequiredError(
                'matchupCommentaryRequest',
                'Required parameter "matchupCommentaryRequest" was null or undefined when calling getMatchupCommentaryApiMatchupCommentaryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/matchup_commentary/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MatchupCommentaryRequestToJSON(requestParameters['matchupCommentaryRequest']),
        };
    }

    /**
     * Generate (or return the cached) pre-game hype commentary for a 1v1 matchup.  POST (not GET) and gated behind the write-tier API key deliberately - a cache miss triggers a real LLM call, not just a read. A cache hit is free and instant; see the module docstring for the caching scheme.
     * Get Matchup Commentary
     */
    async getMatchupCommentaryApiMatchupCommentaryPostRaw(requestParameters: GetMatchupCommentaryApiMatchupCommentaryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MatchupCommentaryResponse>> {
        const requestOptions = await this.getMatchupCommentaryApiMatchupCommentaryPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MatchupCommentaryResponseFromJSON(jsonValue));
    }

    /**
     * Generate (or return the cached) pre-game hype commentary for a 1v1 matchup.  POST (not GET) and gated behind the write-tier API key deliberately - a cache miss triggers a real LLM call, not just a read. A cache hit is free and instant; see the module docstring for the caching scheme.
     * Get Matchup Commentary
     */
    async getMatchupCommentaryApiMatchupCommentaryPost(requestParameters: GetMatchupCommentaryApiMatchupCommentaryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MatchupCommentaryResponse> {
        const response = await this.getMatchupCommentaryApiMatchupCommentaryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGet without sending the request
     */
    async getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequestOpts(requestParameters: GetMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['player1'] == null) {
            throw new runtime.RequiredError(
                'player1',
                'Required parameter "player1" was null or undefined when calling getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGet().'
            );
        }

        if (requestParameters['player2'] == null) {
            throw new runtime.RequiredError(
                'player2',
                'Required parameter "player2" was null or undefined when calling getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGet().'
            );
        }

        if (requestParameters['roundName'] == null) {
            throw new runtime.RequiredError(
                'roundName',
                'Required parameter "roundName" was null or undefined when calling getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['player1'] != null) {
            queryParameters['player1'] = requestParameters['player1'];
        }

        if (requestParameters['player2'] != null) {
            queryParameters['player2'] = requestParameters['player2'];
        }

        if (requestParameters['roundName'] != null) {
            queryParameters['round_name'] = requestParameters['roundName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/matchup_commentary/prompt_preview`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Dev-only: assemble the exact system + user content that would be sent to the active LLM provider for this matchup, without calling the API - for inspecting and trimming payload size/cost. E.g.:      curl -s \"http://localhost:8000/api/matchup_commentary/prompt_preview?player1=X&player2=Y&round_name=Test\" \\       | jq -r .userMessage > /tmp/prompt.json
     * Get Matchup Commentary Prompt Preview
     */
    async getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRaw(requestParameters: GetMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MatchupCommentaryPromptPreview>> {
        const requestOptions = await this.getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MatchupCommentaryPromptPreviewFromJSON(jsonValue));
    }

    /**
     * Dev-only: assemble the exact system + user content that would be sent to the active LLM provider for this matchup, without calling the API - for inspecting and trimming payload size/cost. E.g.:      curl -s \"http://localhost:8000/api/matchup_commentary/prompt_preview?player1=X&player2=Y&round_name=Test\" \\       | jq -r .userMessage > /tmp/prompt.json
     * Get Matchup Commentary Prompt Preview
     */
    async getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGet(requestParameters: GetMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MatchupCommentaryPromptPreview> {
        const response = await this.getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
