/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  MatchupCommentaryPromptPreview,
  MatchupCommentaryResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MatchupCommentaryPromptPreviewFromJSON,
    MatchupCommentaryPromptPreviewToJSON,
    MatchupCommentaryResponseFromJSON,
    MatchupCommentaryResponseToJSON,
} from '../models/index';

export interface GetMatchupCommentaryApiMatchupCommentaryGetRequest {
    player1: string;
    player2: string;
    roundName: string;
    bypassCache?: boolean;
    forceRefresh?: boolean;
}

export interface GetMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequest {
    player1: string;
    player2: string;
    roundName: string;
}

/**
 * 
 */
export class CommentaryApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMatchupCommentaryApiMatchupCommentaryGet without sending the request
     */
    async getMatchupCommentaryApiMatchupCommentaryGetRequestOpts(requestParameters: GetMatchupCommentaryApiMatchupCommentaryGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['player1'] == null) {
            throw new runtime.RequiredError(
                'player1',
                'Required parameter "player1" was null or undefined when calling getMatchupCommentaryApiMatchupCommentaryGet().'
            );
        }

        if (requestParameters['player2'] == null) {
            throw new runtime.RequiredError(
                'player2',
                'Required parameter "player2" was null or undefined when calling getMatchupCommentaryApiMatchupCommentaryGet().'
            );
        }

        if (requestParameters['roundName'] == null) {
            throw new runtime.RequiredError(
                'roundName',
                'Required parameter "roundName" was null or undefined when calling getMatchupCommentaryApiMatchupCommentaryGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['player1'] != null) {
            queryParameters['player1'] = requestParameters['player1'];
        }

        if (requestParameters['player2'] != null) {
            queryParameters['player2'] = requestParameters['player2'];
        }

        if (requestParameters['roundName'] != null) {
            queryParameters['round_name'] = requestParameters['roundName'];
        }

        if (requestParameters['bypassCache'] != null) {
            queryParameters['bypass_cache'] = requestParameters['bypassCache'];
        }

        if (requestParameters['forceRefresh'] != null) {
            queryParameters['force_refresh'] = requestParameters['forceRefresh'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/matchup_commentary/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Generate (or return the cached) pre-game hype commentary for a 1v1 matchup.  A GET so the normal-tier API key the browser ships with can reach it - the bracket UI needs to show this to everyone, and a cache hit is free and instant. A cache *miss* still triggers a real, billed LLM call, so the two things that would make that spend unbounded are fenced off:  - ``round_name`` must be one a bracket actually produces   (``bracket.known_round_names()``); the cache key is   (player1, player2, round_name) and all three must be enumerable, or a   caller could mint fresh keys forever. Player names are already bounded   by ``PlayerName``\'s alias resolution. - ``bypass_cache``/``force_refresh`` both skip the cache read and always   call the LLM, so they require the admin-tier key. They differ in   whether the result is then persisted: ``force_refresh`` overwrites the   cached row, ``bypass_cache`` does not touch it. If both are set,   ``bypass_cache`` wins (no write).
     * Get Matchup Commentary
     */
    async getMatchupCommentaryApiMatchupCommentaryGetRaw(requestParameters: GetMatchupCommentaryApiMatchupCommentaryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MatchupCommentaryResponse>> {
        const requestOptions = await this.getMatchupCommentaryApiMatchupCommentaryGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MatchupCommentaryResponseFromJSON(jsonValue));
    }

    /**
     * Generate (or return the cached) pre-game hype commentary for a 1v1 matchup.  A GET so the normal-tier API key the browser ships with can reach it - the bracket UI needs to show this to everyone, and a cache hit is free and instant. A cache *miss* still triggers a real, billed LLM call, so the two things that would make that spend unbounded are fenced off:  - ``round_name`` must be one a bracket actually produces   (``bracket.known_round_names()``); the cache key is   (player1, player2, round_name) and all three must be enumerable, or a   caller could mint fresh keys forever. Player names are already bounded   by ``PlayerName``\'s alias resolution. - ``bypass_cache``/``force_refresh`` both skip the cache read and always   call the LLM, so they require the admin-tier key. They differ in   whether the result is then persisted: ``force_refresh`` overwrites the   cached row, ``bypass_cache`` does not touch it. If both are set,   ``bypass_cache`` wins (no write).
     * Get Matchup Commentary
     */
    async getMatchupCommentaryApiMatchupCommentaryGet(requestParameters: GetMatchupCommentaryApiMatchupCommentaryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MatchupCommentaryResponse> {
        const response = await this.getMatchupCommentaryApiMatchupCommentaryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGet without sending the request
     */
    async getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequestOpts(requestParameters: GetMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['player1'] == null) {
            throw new runtime.RequiredError(
                'player1',
                'Required parameter "player1" was null or undefined when calling getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGet().'
            );
        }

        if (requestParameters['player2'] == null) {
            throw new runtime.RequiredError(
                'player2',
                'Required parameter "player2" was null or undefined when calling getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGet().'
            );
        }

        if (requestParameters['roundName'] == null) {
            throw new runtime.RequiredError(
                'roundName',
                'Required parameter "roundName" was null or undefined when calling getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['player1'] != null) {
            queryParameters['player1'] = requestParameters['player1'];
        }

        if (requestParameters['player2'] != null) {
            queryParameters['player2'] = requestParameters['player2'];
        }

        if (requestParameters['roundName'] != null) {
            queryParameters['round_name'] = requestParameters['roundName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/matchup_commentary/prompt_preview`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Dev-only: assemble the exact system + user content that would be sent to the active LLM provider for this matchup, without calling the API - for inspecting and trimming payload size/cost. E.g.:      curl -s \"http://localhost:8000/api/matchup_commentary/prompt_preview?player1=X&player2=Y&round_name=Test\" \\       | jq -r .userMessage > /tmp/prompt.json
     * Get Matchup Commentary Prompt Preview
     */
    async getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRaw(requestParameters: GetMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MatchupCommentaryPromptPreview>> {
        const requestOptions = await this.getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MatchupCommentaryPromptPreviewFromJSON(jsonValue));
    }

    /**
     * Dev-only: assemble the exact system + user content that would be sent to the active LLM provider for this matchup, without calling the API - for inspecting and trimming payload size/cost. E.g.:      curl -s \"http://localhost:8000/api/matchup_commentary/prompt_preview?player1=X&player2=Y&round_name=Test\" \\       | jq -r .userMessage > /tmp/prompt.json
     * Get Matchup Commentary Prompt Preview
     */
    async getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGet(requestParameters: GetMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MatchupCommentaryPromptPreview> {
        const response = await this.getMatchupCommentaryPromptPreviewApiMatchupCommentaryPromptPreviewGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
