/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DraftRequest,
  DraftResult,
  HTTPValidationError,
} from '../models/index';
import {
    DraftRequestFromJSON,
    DraftRequestToJSON,
    DraftResultFromJSON,
    DraftResultToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface RandomizeDraftApiDraftRandomizePostRequest {
    draftRequest: DraftRequest;
}

/**
 * 
 */
export class DraftApi extends runtime.BaseAPI {

    /**
     * Creates request options for randomizeDraftApiDraftRandomizePost without sending the request
     */
    async randomizeDraftApiDraftRandomizePostRequestOpts(requestParameters: RandomizeDraftApiDraftRandomizePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['draftRequest'] == null) {
            throw new runtime.RequiredError(
                'draftRequest',
                'Required parameter "draftRequest" was null or undefined when calling randomizeDraftApiDraftRandomizePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/draft/randomize`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DraftRequestToJSON(requestParameters['draftRequest']),
        };
    }

    /**
     * Randomize Draft
     */
    async randomizeDraftApiDraftRandomizePostRaw(requestParameters: RandomizeDraftApiDraftRandomizePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DraftResult>> {
        const requestOptions = await this.randomizeDraftApiDraftRandomizePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DraftResultFromJSON(jsonValue));
    }

    /**
     * Randomize Draft
     */
    async randomizeDraftApiDraftRandomizePost(requestParameters: RandomizeDraftApiDraftRandomizePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DraftResult> {
        const response = await this.randomizeDraftApiDraftRandomizePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
