/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GameNightRecap,
  GameNightSummaryStatus,
  HTTPValidationError,
} from '../models/index';
import {
    GameNightRecapFromJSON,
    GameNightRecapToJSON,
    GameNightSummaryStatusFromJSON,
    GameNightSummaryStatusToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetGameNightRecapApiGameNightNightGetRequest {
    night: Date;
}

export interface GetGameNightSummaryStatusApiGameNightStatusNightGetRequest {
    night: Date;
}

export interface ListGameNightSummariesApiGameNightSummariesGetRequest {
    limit?: number;
}

/**
 * 
 */
export class GameNightApi extends runtime.BaseAPI {

    /**
     * Creates request options for getGameNightRecapApiGameNightNightGet without sending the request
     */
    async getGameNightRecapApiGameNightNightGetRequestOpts(requestParameters: GetGameNightRecapApiGameNightNightGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['night'] == null) {
            throw new runtime.RequiredError(
                'night',
                'Required parameter "night" was null or undefined when calling getGameNightRecapApiGameNightNightGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/game_night/{night}`;
        if (requestParameters['night'] instanceof Date) {
            urlPath = urlPath.replace(`{${"night"}}`, encodeURIComponent(requestParameters['night'].toISOString().substring(0,10)));
        } else {
            urlPath = urlPath.replace(`{${"night"}}`, encodeURIComponent(String(requestParameters['night'])));
        }

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The recap for one game night.  ``night`` is the game-night date key (``utils.game_night_date``), the same one ``/api/dates/`` returns - not a calendar UTC date. A night with no games returns a zeroed recap rather than a 404, so the page can render \"nothing was played\" for a date somebody typed in.
     * Get Game Night Recap
     */
    async getGameNightRecapApiGameNightNightGetRaw(requestParameters: GetGameNightRecapApiGameNightNightGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameNightRecap>> {
        const requestOptions = await this.getGameNightRecapApiGameNightNightGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameNightRecapFromJSON(jsonValue));
    }

    /**
     * The recap for one game night.  ``night`` is the game-night date key (``utils.game_night_date``), the same one ``/api/dates/`` returns - not a calendar UTC date. A night with no games returns a zeroed recap rather than a 404, so the page can render \"nothing was played\" for a date somebody typed in.
     * Get Game Night Recap
     */
    async getGameNightRecapApiGameNightNightGet(requestParameters: GetGameNightRecapApiGameNightNightGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameNightRecap> {
        const response = await this.getGameNightRecapApiGameNightNightGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGameNightSummaryStatusApiGameNightStatusNightGet without sending the request
     */
    async getGameNightSummaryStatusApiGameNightStatusNightGetRequestOpts(requestParameters: GetGameNightSummaryStatusApiGameNightStatusNightGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['night'] == null) {
            throw new runtime.RequiredError(
                'night',
                'Required parameter "night" was null or undefined when calling getGameNightSummaryStatusApiGameNightStatusNightGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/game_night_status/{night}`;
        if (requestParameters['night'] instanceof Date) {
            urlPath = urlPath.replace(`{${"night"}}`, encodeURIComponent(requestParameters['night'].toISOString().substring(0,10)));
        } else {
            urlPath = urlPath.replace(`{${"night"}}`, encodeURIComponent(String(requestParameters['night'])));
        }

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Whether a night has a stored LLM recap, without shipping its text.
     * Get Game Night Summary Status
     */
    async getGameNightSummaryStatusApiGameNightStatusNightGetRaw(requestParameters: GetGameNightSummaryStatusApiGameNightStatusNightGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameNightSummaryStatus>> {
        const requestOptions = await this.getGameNightSummaryStatusApiGameNightStatusNightGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameNightSummaryStatusFromJSON(jsonValue));
    }

    /**
     * Whether a night has a stored LLM recap, without shipping its text.
     * Get Game Night Summary Status
     */
    async getGameNightSummaryStatusApiGameNightStatusNightGet(requestParameters: GetGameNightSummaryStatusApiGameNightStatusNightGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameNightSummaryStatus> {
        const response = await this.getGameNightSummaryStatusApiGameNightStatusNightGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listGameNightSummariesApiGameNightSummariesGet without sending the request
     */
    async listGameNightSummariesApiGameNightSummariesGetRequestOpts(requestParameters: ListGameNightSummariesApiGameNightSummariesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/game_night_summaries`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Game nights that have a stored LLM recap, newest first.  Lets a listing badge the nights that have one without fetching each night\'s recap. A distinct top-level path rather than a static sibling of ``/api/game_night/{night}`` - the OpenAPI generator silently merges those (see the maps note in CLAUDE.md).
     * List Game Night Summaries
     */
    async listGameNightSummariesApiGameNightSummariesGetRaw(requestParameters: ListGameNightSummariesApiGameNightSummariesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Date>>> {
        const requestOptions = await this.listGameNightSummariesApiGameNightSummariesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Game nights that have a stored LLM recap, newest first.  Lets a listing badge the nights that have one without fetching each night\'s recap. A distinct top-level path rather than a static sibling of ``/api/game_night/{night}`` - the OpenAPI generator silently merges those (see the maps note in CLAUDE.md).
     * List Game Night Summaries
     */
    async listGameNightSummariesApiGameNightSummariesGet(requestParameters: ListGameNightSummariesApiGameNightSummariesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Date>> {
        const response = await this.listGameNightSummariesApiGameNightSummariesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
