/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChooseMapRequest,
  ChooseMapResult,
  HTTPValidationError,
  MapVotePage,
  SetMapVoteRequest,
} from '../models/index';
import {
    ChooseMapRequestFromJSON,
    ChooseMapRequestToJSON,
    ChooseMapResultFromJSON,
    ChooseMapResultToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MapVotePageFromJSON,
    MapVotePageToJSON,
    SetMapVoteRequestFromJSON,
    SetMapVoteRequestToJSON,
} from '../models/index';

export interface ChooseMapApiMapVotePlayerCountChoosePostRequest {
    playerCount: number;
    chooseMapRequest: ChooseMapRequest;
}

export interface GetVotePageApiMapVotePlayerCountGetRequest {
    playerCount: number;
}

export interface SetVoteApiMapVotePlayerCountPostRequest {
    playerCount: number;
    setMapVoteRequest: SetMapVoteRequest;
}

/**
 * 
 */
export class MapVoteApi extends runtime.BaseAPI {

    /**
     * Creates request options for chooseMapApiMapVotePlayerCountChoosePost without sending the request
     */
    async chooseMapApiMapVotePlayerCountChoosePostRequestOpts(requestParameters: ChooseMapApiMapVotePlayerCountChoosePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playerCount'] == null) {
            throw new runtime.RequiredError(
                'playerCount',
                'Required parameter "playerCount" was null or undefined when calling chooseMapApiMapVotePlayerCountChoosePost().'
            );
        }

        if (requestParameters['chooseMapRequest'] == null) {
            throw new runtime.RequiredError(
                'chooseMapRequest',
                'Required parameter "chooseMapRequest" was null or undefined when calling chooseMapApiMapVotePlayerCountChoosePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/map_vote/{player_count}/choose`;
        urlPath = urlPath.replace(`{${"player_count"}}`, encodeURIComponent(String(requestParameters['playerCount'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChooseMapRequestToJSON(requestParameters['chooseMapRequest']),
        };
    }

    /**
     * Run the authoritative weighted-random draw for this player count.  Only the votes of the players in ``req.players`` are counted, so the draw reflects who\'s actually playing. Returns the chosen map (with its CRC, when stored) plus every voted/vetoed map (with tallies) for the reveal + spin.
     * Choose Map
     */
    async chooseMapApiMapVotePlayerCountChoosePostRaw(requestParameters: ChooseMapApiMapVotePlayerCountChoosePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChooseMapResult>> {
        const requestOptions = await this.chooseMapApiMapVotePlayerCountChoosePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChooseMapResultFromJSON(jsonValue));
    }

    /**
     * Run the authoritative weighted-random draw for this player count.  Only the votes of the players in ``req.players`` are counted, so the draw reflects who\'s actually playing. Returns the chosen map (with its CRC, when stored) plus every voted/vetoed map (with tallies) for the reveal + spin.
     * Choose Map
     */
    async chooseMapApiMapVotePlayerCountChoosePost(requestParameters: ChooseMapApiMapVotePlayerCountChoosePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChooseMapResult> {
        const response = await this.chooseMapApiMapVotePlayerCountChoosePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVotePageApiMapVotePlayerCountGet without sending the request
     */
    async getVotePageApiMapVotePlayerCountGetRequestOpts(requestParameters: GetVotePageApiMapVotePlayerCountGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playerCount'] == null) {
            throw new runtime.RequiredError(
                'playerCount',
                'Required parameter "playerCount" was null or undefined when calling getVotePageApiMapVotePlayerCountGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/map_vote/{player_count}`;
        urlPath = urlPath.replace(`{${"player_count"}}`, encodeURIComponent(String(requestParameters['playerCount'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Maps for a player count (ordered by total games) plus the viewer\'s picks.
     * Get Vote Page
     */
    async getVotePageApiMapVotePlayerCountGetRaw(requestParameters: GetVotePageApiMapVotePlayerCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MapVotePage>> {
        const requestOptions = await this.getVotePageApiMapVotePlayerCountGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MapVotePageFromJSON(jsonValue));
    }

    /**
     * Maps for a player count (ordered by total games) plus the viewer\'s picks.
     * Get Vote Page
     */
    async getVotePageApiMapVotePlayerCountGet(requestParameters: GetVotePageApiMapVotePlayerCountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MapVotePage> {
        const response = await this.getVotePageApiMapVotePlayerCountGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for playerCountsApiMapVotePlayerCountsGet without sending the request
     */
    async playerCountsApiMapVotePlayerCountsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/map_vote/player_counts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Player counts we have maps for (real players seen in games + MapData capacities).
     * Player Counts
     */
    async playerCountsApiMapVotePlayerCountsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<number | null>>> {
        const requestOptions = await this.playerCountsApiMapVotePlayerCountsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Player counts we have maps for (real players seen in games + MapData capacities).
     * Player Counts
     */
    async playerCountsApiMapVotePlayerCountsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number | null>> {
        const response = await this.playerCountsApiMapVotePlayerCountsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for setVoteApiMapVotePlayerCountPost without sending the request
     */
    async setVoteApiMapVotePlayerCountPostRequestOpts(requestParameters: SetVoteApiMapVotePlayerCountPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['playerCount'] == null) {
            throw new runtime.RequiredError(
                'playerCount',
                'Required parameter "playerCount" was null or undefined when calling setVoteApiMapVotePlayerCountPost().'
            );
        }

        if (requestParameters['setMapVoteRequest'] == null) {
            throw new runtime.RequiredError(
                'setMapVoteRequest',
                'Required parameter "setMapVoteRequest" was null or undefined when calling setVoteApiMapVotePlayerCountPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/map_vote/{player_count}`;
        urlPath = urlPath.replace(`{${"player_count"}}`, encodeURIComponent(String(requestParameters['playerCount'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetMapVoteRequestToJSON(requestParameters['setMapVoteRequest']),
        };
    }

    /**
     * Cast/clear a vote or veto for a map (requires login).
     * Set Vote
     */
    async setVoteApiMapVotePlayerCountPostRaw(requestParameters: SetVoteApiMapVotePlayerCountPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MapVotePage>> {
        const requestOptions = await this.setVoteApiMapVotePlayerCountPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MapVotePageFromJSON(jsonValue));
    }

    /**
     * Cast/clear a vote or veto for a map (requires login).
     * Set Vote
     */
    async setVoteApiMapVotePlayerCountPost(requestParameters: SetVoteApiMapVotePlayerCountPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MapVotePage> {
        const response = await this.setVoteApiMapVotePlayerCountPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for votingPlayersApiMapVotePlayersGet without sending the request
     */
    async votingPlayersApiMapVotePlayersGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/map_vote/players`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * In-game names with an account - the selectable participants for a draw.
     * Voting Players
     */
    async votingPlayersApiMapVotePlayersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string | null>>> {
        const requestOptions = await this.votingPlayersApiMapVotePlayersGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * In-game names with an account - the selectable participants for a draw.
     * Voting Players
     */
    async votingPlayersApiMapVotePlayersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string | null>> {
        const response = await this.votingPlayersApiMapVotePlayersGetRaw(initOverrides);
        return await response.value();
    }

}
