/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FactionMatchupPrediction,
  FactionMatrix,
  HTTPValidationError,
  MatchPrediction,
  PredictRequest,
  WinProbOverTime,
} from '../models/index';
import {
    FactionMatchupPredictionFromJSON,
    FactionMatchupPredictionToJSON,
    FactionMatrixFromJSON,
    FactionMatrixToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MatchPredictionFromJSON,
    MatchPredictionToJSON,
    PredictRequestFromJSON,
    PredictRequestToJSON,
    WinProbOverTimeFromJSON,
    WinProbOverTimeToJSON,
} from '../models/index';

export interface PredictFactionMatchupApiPredictFactionMatchupGetRequest {
    player1: string;
    player2: string;
    mapName?: string | null;
}

export interface PredictFromFeaturesApiPredictPostRequest {
    predictRequest: PredictRequest;
}

export interface PredictMatchApiPredictMatchMatchIdGetRequest {
    matchId: number;
}

export interface PredictOverTimeApiPredictOverTimeMatchIdGetRequest {
    matchId: number;
}

/**
 * 
 */
export class PredictApi extends runtime.BaseAPI {

    /**
     * Creates request options for predictFactionMatchupApiPredictFactionMatchupGet without sending the request
     */
    async predictFactionMatchupApiPredictFactionMatchupGetRequestOpts(requestParameters: PredictFactionMatchupApiPredictFactionMatchupGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['player1'] == null) {
            throw new runtime.RequiredError(
                'player1',
                'Required parameter "player1" was null or undefined when calling predictFactionMatchupApiPredictFactionMatchupGet().'
            );
        }

        if (requestParameters['player2'] == null) {
            throw new runtime.RequiredError(
                'player2',
                'Required parameter "player2" was null or undefined when calling predictFactionMatchupApiPredictFactionMatchupGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['player1'] != null) {
            queryParameters['player1'] = requestParameters['player1'];
        }

        if (requestParameters['player2'] != null) {
            queryParameters['player2'] = requestParameters['player2'];
        }

        if (requestParameters['mapName'] != null) {
            queryParameters['map_name'] = requestParameters['mapName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/predict/faction_matchup`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Rank every general-vs-general draw for a hypothetical 1v1 between player1 and player2, by running the win-prediction model once per (player1_general, player2_general) combination - 12x12 = 144 calls.  Backs the \"best possible draws\" section of Bracket.tsx\'s MatchupPopup, which calls this on every popup open - hence ``_faction_grid`` being a derivation; ``compute_ms`` is near-zero on a cache hit.  No map is known before the draw; omit map_name to use a placeholder the model treats as \"unknown\" (see ``_UNKNOWN_MAP_PLACEHOLDER``), or pass a real map name to fix it.
     * Predict Faction Matchup
     */
    async predictFactionMatchupApiPredictFactionMatchupGetRaw(requestParameters: PredictFactionMatchupApiPredictFactionMatchupGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FactionMatchupPrediction>> {
        const requestOptions = await this.predictFactionMatchupApiPredictFactionMatchupGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FactionMatchupPredictionFromJSON(jsonValue));
    }

    /**
     * Rank every general-vs-general draw for a hypothetical 1v1 between player1 and player2, by running the win-prediction model once per (player1_general, player2_general) combination - 12x12 = 144 calls.  Backs the \"best possible draws\" section of Bracket.tsx\'s MatchupPopup, which calls this on every popup open - hence ``_faction_grid`` being a derivation; ``compute_ms`` is near-zero on a cache hit.  No map is known before the draw; omit map_name to use a placeholder the model treats as \"unknown\" (see ``_UNKNOWN_MAP_PLACEHOLDER``), or pass a real map name to fix it.
     * Predict Faction Matchup
     */
    async predictFactionMatchupApiPredictFactionMatchupGet(requestParameters: PredictFactionMatchupApiPredictFactionMatchupGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FactionMatchupPrediction> {
        const response = await this.predictFactionMatchupApiPredictFactionMatchupGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for predictFactionMatrixApiPredictFactionMatrixGet without sending the request
     */
    async predictFactionMatrixApiPredictFactionMatrixGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/predict/faction_matrix`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The full 12x12 general-vs-general grid with both players and the map forced to the model\'s UNK slot - a pure faction-vs-faction signal with no player identity or map mixed in. Same 144-call approach as faction_matchup, just with placeholder inputs instead of a real pair of players.
     * Predict Faction Matrix
     */
    async predictFactionMatrixApiPredictFactionMatrixGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FactionMatrix>> {
        const requestOptions = await this.predictFactionMatrixApiPredictFactionMatrixGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FactionMatrixFromJSON(jsonValue));
    }

    /**
     * The full 12x12 general-vs-general grid with both players and the map forced to the model\'s UNK slot - a pure faction-vs-faction signal with no player identity or map mixed in. Same 144-call approach as faction_matchup, just with placeholder inputs instead of a real pair of players.
     * Predict Faction Matrix
     */
    async predictFactionMatrixApiPredictFactionMatrixGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FactionMatrix> {
        const response = await this.predictFactionMatrixApiPredictFactionMatrixGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for predictFromFeaturesApiPredictPost without sending the request
     */
    async predictFromFeaturesApiPredictPostRequestOpts(requestParameters: PredictFromFeaturesApiPredictPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['predictRequest'] == null) {
            throw new runtime.RequiredError(
                'predictRequest',
                'Required parameter "predictRequest" was null or undefined when calling predictFromFeaturesApiPredictPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/predict`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PredictRequestToJSON(requestParameters['predictRequest']),
        };
    }

    /**
     * Predict the winner from raw features: map, players, teams, generals.
     * Predict From Features
     */
    async predictFromFeaturesApiPredictPostRaw(requestParameters: PredictFromFeaturesApiPredictPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MatchPrediction>> {
        const requestOptions = await this.predictFromFeaturesApiPredictPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MatchPredictionFromJSON(jsonValue));
    }

    /**
     * Predict the winner from raw features: map, players, teams, generals.
     * Predict From Features
     */
    async predictFromFeaturesApiPredictPost(requestParameters: PredictFromFeaturesApiPredictPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MatchPrediction> {
        const response = await this.predictFromFeaturesApiPredictPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for predictMatchApiPredictMatchMatchIdGet without sending the request
     */
    async predictMatchApiPredictMatchMatchIdGetRequestOpts(requestParameters: PredictMatchApiPredictMatchMatchIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['matchId'] == null) {
            throw new runtime.RequiredError(
                'matchId',
                'Required parameter "matchId" was null or undefined when calling predictMatchApiPredictMatchMatchIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/predict/match/{match_id}`;
        urlPath = urlPath.replace(`{${"match_id"}}`, encodeURIComponent(String(requestParameters['matchId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Predict the winner of an existing match by id.
     * Predict Match
     */
    async predictMatchApiPredictMatchMatchIdGetRaw(requestParameters: PredictMatchApiPredictMatchMatchIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MatchPrediction>> {
        const requestOptions = await this.predictMatchApiPredictMatchMatchIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MatchPredictionFromJSON(jsonValue));
    }

    /**
     * Predict the winner of an existing match by id.
     * Predict Match
     */
    async predictMatchApiPredictMatchMatchIdGet(requestParameters: PredictMatchApiPredictMatchMatchIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MatchPrediction> {
        const response = await this.predictMatchApiPredictMatchMatchIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for predictOverTimeApiPredictOverTimeMatchIdGet without sending the request
     */
    async predictOverTimeApiPredictOverTimeMatchIdGetRequestOpts(requestParameters: PredictOverTimeApiPredictOverTimeMatchIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['matchId'] == null) {
            throw new runtime.RequiredError(
                'matchId',
                'Required parameter "matchId" was null or undefined when calling predictOverTimeApiPredictOverTimeMatchIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/predict/over_time/{match_id}`;
        urlPath = urlPath.replace(`{${"match_id"}}`, encodeURIComponent(String(requestParameters['matchId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Win-probability-over-time curve for an existing match.  Streams the match\'s parsed replay JSON from S3 and runs the sequence ONNX model, returning P(team A wins) at each 30-second window.
     * Predict Over Time
     */
    async predictOverTimeApiPredictOverTimeMatchIdGetRaw(requestParameters: PredictOverTimeApiPredictOverTimeMatchIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WinProbOverTime>> {
        const requestOptions = await this.predictOverTimeApiPredictOverTimeMatchIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WinProbOverTimeFromJSON(jsonValue));
    }

    /**
     * Win-probability-over-time curve for an existing match.  Streams the match\'s parsed replay JSON from S3 and runs the sequence ONNX model, returning P(team A wins) at each 30-second window.
     * Predict Over Time
     */
    async predictOverTimeApiPredictOverTimeMatchIdGet(requestParameters: PredictOverTimeApiPredictOverTimeMatchIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WinProbOverTime> {
        const response = await this.predictOverTimeApiPredictOverTimeMatchIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
