/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Superlatives,
} from '../models/index';
import {
    SuperlativesFromJSON,
    SuperlativesToJSON,
} from '../models/index';

/**
 * 
 */
export class SuperlativesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getSuperlativesApiSuperlativesGet without sending the request
     */
    async getSuperlativesApiSuperlativesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // APIKeyHeader authentication
        }


        let urlPath = `/api/superlatives`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Serve superlatives from the DB if available, otherwise compute on the fly.
     * Get Superlatives
     */
    async getSuperlativesApiSuperlativesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Superlatives>> {
        const requestOptions = await this.getSuperlativesApiSuperlativesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuperlativesFromJSON(jsonValue));
    }

    /**
     * Serve superlatives from the DB if available, otherwise compute on the fly.
     * Get Superlatives
     */
    async getSuperlativesApiSuperlativesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Superlatives> {
        const response = await this.getSuperlativesApiSuperlativesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for recomputeSuperlativesApiSuperlativesRecomputePost without sending the request
     */
    async recomputeSuperlativesApiSuperlativesRecomputePostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/superlatives/recompute`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Trigger superlatives recompute in the background and return immediately.
     * Recompute Superlatives
     */
    async recomputeSuperlativesApiSuperlativesRecomputePostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        const requestOptions = await this.recomputeSuperlativesApiSuperlativesRecomputePostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Trigger superlatives recompute in the background and return immediately.
     * Recompute Superlatives
     */
    async recomputeSuperlativesApiSuperlativesRecomputePost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.recomputeSuperlativesApiSuperlativesRecomputePostRaw(initOverrides);
        return await response.value();
    }

}
