#!/bin/bash
source .venv/bin/activate
source .env
export DATABASE_URL
export CNCSTATS_APIKEY
export CNCSTATS_API_KEY
export DISCORD_CLIENT_ID
export DISCORD_CLIENT_SECRET
export DISCORD_REDIRECT_URI
export SESSION_SECRET
export CLAUDE_API_KEY
export GEMINI_API_KEY
export DISCORD_BOT_TOKEN
export DISCORD_GUILD_ID
export DISCORD_VOICE_CHANNEL_ID
