"""Types from the cncstats parsed json.

Generated by claude from a jsonschema which was generated by ai, so may not be perfect
"""

from pydantic import BaseModel, Field, RootModel
from typing import Annotated


class ByteArray2(RootModel):
    """Array of exactly 2 bytes (0-255)"""

    root: Annotated[list[int], Field(min_length=2, max_length=2)]


class ByteArray4(RootModel):
    """Array of exactly 4 bytes (0-255)"""

    root: Annotated[list[int], Field(min_length=4, max_length=4)]


class ByteArray8(RootModel):
    """Array of exactly 8 bytes (0-255)"""

    root: Annotated[list[int], Field(min_length=8, max_length=8)]


class ByteArray12(RootModel):
    """Array of exactly 12 bytes (0-255)"""

    root: Annotated[list[int], Field(min_length=12, max_length=12)]


class Position3D(BaseModel):

    X: float
    Y: float
    Z: float


class ScreenPosition(BaseModel):

    X: int
    Y: int


class ScreenRectangle(RootModel):
    """Array of exactly 2 ScreenPosition objects"""

    root: Annotated[list[ScreenPosition], Field(min_length=2, max_length=2)]


class Unit(BaseModel):

    Name: str
    Cost: int


class Building(BaseModel):

    Name: str
    Cost: int


class Upgrade(BaseModel):

    Name: str
    Cost: int


class Power(BaseModel):

    Name: str


class ArgMetadata(BaseModel):

    Type: int
    Count: int


class Money(BaseModel):

    PlayerMoney: list[int]


class EnhancedBodyChunk(BaseModel):

    TimeCode: int
    OrderCode: int
    OrderName: str
    PlayerID: int
    PlayerName: str
    NumberOfArguments: int
    # Details: Optional[Union[Unit, Building, Upgrade, Power]] = None
    ArgMetadata: list[ArgMetadata]
    Arguments: list[
        int | float | bool | str | Position3D | ScreenPosition | ScreenRectangle
    ]
    PlayerMoney: Money | None = None


class ObjectSummary(BaseModel):

    Count: int
    TotalSpent: int


class PlayerSummary(BaseModel):

    Name: str
    Side: str
    Team: int
    Win: bool
    MoneySpent: int
    UnitsCreated: dict[str, ObjectSummary]
    BuildingsBuilt: dict[str, ObjectSummary]
    UpgradesBuilt: dict[str, ObjectSummary]
    PowersUsed: dict[str, int]


class Player(BaseModel):

    Type: str
    Name: str
    IP: str
    Port: str
    FT: str
    Color: str
    Faction: str
    StartingPosition: str
    Team: int
    Unknown: str


class Metadata(BaseModel):

    MapFile: str
    MapCRC: str
    MapSize: str
    Seed: int
    C: str
    SR: str
    StartingCredits: str
    O: str
    Players: list[Player]


class GeneralsHeader(BaseModel):

    GameType: str
    TimeStampBegin: int
    TimeStampEnd: int
    NumTimeStamps: int
    FileName: str
    Year: int
    Month: int
    DOW: int
    Day: int
    Hour: int
    Minute: int
    Second: int
    Millisecond: int
    Version: str
    BuildDate: str
    VersionMinor: int
    VersionMajor: int
    Hash: ByteArray8
    Metadata: Metadata
    ReplayOwnerSlot: ByteArray2
    Unknown1: ByteArray4
    Unknown2: ByteArray4
    Unknown3: ByteArray4
    GameSpeed: int


class EnhancedReplay(BaseModel):
    Header: GeneralsHeader
    Body: list[EnhancedBodyChunk]
    Summary: list[PlayerSummary]
    Offset: int

    def replay_id(self) -> int:
        return self.Header.Metadata.Seed
