"""Keeps src/lib/mapName.ts in step with replay_files.map_key/map_display_name.

The TS copy exists because the bracket keys map names it holds as literals
against server records, with no request to ask on. Delete it once the map pool
lives in the database.
"""

import json
from pathlib import Path

from radarvan.replay_files import map_display_name, map_key

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE = Path(__file__).parent / "map_name_cases.json"

MAP_NAME_CASES = [
    # Shapes production stores: lowercase, slash-separated, no suffix.
    "maps/defcon6",
    "userdata/maps/[rank] territorial dispute zh v1",
    "maps/tournament island",
    "userdata/maps/exkalibur_zh",
    # Suffixed, both cases - replay headers carry either.
    "maps/Tournament Desert.map",
    "a/b/c/Foo.MAP",
    "Dust Devil.Map",
    # Bare names: what the bracket's map pool holds.
    "Dust Devil",
    "[RANK] Barren Badlands Balanced ZH v2",
    "Oxygen 1",
    # ".map" mid-name.
    "maps/the.mapper zh v1",
    "the.map.map",
    "userdata/maps/Green   Pastures",
    "MAPS/Hostile Dawn",
    # map_basename returns "Unknown" for "" - matches with no recorded map.
    "",
    "trailing/",
]


def test_the_fixture_is_current() -> None:
    expected = {
        "_comment": "Generated by tests/test_map_key_parity.py; read by "
        "src/lib/mapName.test.ts. Delete and re-run pytest to regenerate.",
        "cases": [
            {"input": name, "key": map_key(name), "display": map_display_name(name)}
            for name in MAP_NAME_CASES
        ],
    }
    if not FIXTURE.exists():
        FIXTURE.write_text(json.dumps(expected, indent=2) + "\n")
    assert json.loads(FIXTURE.read_text()) == expected, (
        f"{FIXTURE.name} is stale. Delete it, re-run pytest, then check npm test."
    )


def test_key_strips_path_suffix_whitespace_and_case() -> None:
    assert map_key("userdata/maps/Green   Pastures") == "greenpastures"
    assert map_key("maps/Tournament Desert.map") == "tournamentdesert"
    assert map_key("a/b/c/Foo.MAP") == "foo"


def test_key_agrees_across_the_shapes_one_map_arrives_in() -> None:
    assert map_key("Dust Devil") == map_key("userdata/maps/dust devil.map")
    assert map_key("[RANK] Barren Badlands Balanced ZH v2") == map_key(
        "maps/[rank] barren badlands balanced zh v2"
    )


def test_display_keeps_case_and_interior_whitespace() -> None:
    assert map_display_name("userdata/maps/Green   Pastures") == "Green   Pastures"
    assert map_display_name("maps/Tournament Desert.map") == "Tournament Desert"
    assert map_display_name("a/b/c/Foo.MAP") == "Foo"


def test_only_a_trailing_map_suffix_is_stripped() -> None:
    assert map_display_name("maps/the.mapper zh v1") == "the.mapper zh v1"
    assert map_display_name("the.map.map") == "the.map"


def test_the_typescript_copy_points_back_here() -> None:
    ts = (REPO_ROOT / "src" / "lib" / "mapName.ts").read_text()
    assert "replay_files" in ts
    assert "map_name_cases.json" in ts or "mapName.test.ts" in ts
