# generated by datamodel-codegen:
#   filename:  cncstats_schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class Player(BaseModel):
    color: Annotated[
        str, Field(description="Color index (or name if ColorStore provided)")
    ]
    flags: Annotated[
        str,
        Field(
            description='Human: <accepted><hasMap> (e.g. "TT"); AI: difficulty (E/M/H)'
        ),
    ]
    ip: Annotated[str, Field(description="Human only (hex)")]
    name: Annotated[str, Field(description="Human only")]
    nat_behavior: Annotated[
        str,
        Field(alias="natBehavior", description="Human only: firewall behavior type"),
    ]
    player_template: Annotated[
        str,
        Field(alias="playerTemplate", description="Index into player template store"),
    ]
    port: Annotated[str, Field(description="Human only")]
    starting_position: Annotated[
        str, Field(alias="startingPosition", description="Start position (-1 = random)")
    ]
    team: Annotated[str, Field(description="Team number (-1 = none)")]
    type: Annotated[str, Field(description="H=human, C=computer")]


class Metadata(BaseModel):
    crc_interval: Annotated[str, Field(alias="crcInterval", description="C")]
    map_crc: Annotated[str, Field(alias="mapCRC", description="MC (hex)")]
    map_contents_mask: Annotated[
        str, Field(alias="mapContentsMask", description="M prefix (2 hex digits)")
    ]
    map_path: Annotated[
        str, Field(alias="mapPath", description="M remainder (map directory path)")
    ]
    map_size: Annotated[str, Field(alias="mapSize", description="MS")]
    old_factions_only: Annotated[
        str, Field(alias="oldFactionsOnly", description="O (ZH only: Y/N)")
    ]
    players: Annotated[list[Player], Field(description="S")]
    seed: Annotated[int, Field(description="SD")]
    starting_cash: Annotated[
        str, Field(alias="startingCash", description="SC (ZH only)")
    ]
    superweapon_restriction: Annotated[
        str, Field(alias="superweaponRestriction", description="SR (ZH only)")
    ]
    use_stats: Annotated[
        str, Field(alias="useStats", description="US (ZH only: 1=yes, 0=no)")
    ]


class GeneralsHeader(BaseModel):
    build_date: Annotated[
        str,
        Field(
            alias="buildDate", description="UTF-16 null-terminated (versionTimeString)"
        ),
    ]
    day: int
    desync: Annotated[bool, Field(description="1 byte Bool")]
    difficulty: Annotated[int, Field(description="int32 (GameDifficulty enum)")]
    dow: int
    exe_crc: Annotated[int, Field(alias="exeCRC", description="uint32")]
    frame_count: Annotated[int, Field(alias="frameCount", description="uint32")]
    game_type: Annotated[str, Field(alias="gameType", description='6 bytes: "GENREP"')]
    hour: int
    ini_crc: Annotated[int, Field(alias="iniCRC", description="uint32")]
    local_player_index: Annotated[
        int, Field(alias="localPlayerIndex", description="ASCII null-terminated int")
    ]
    max_fps: Annotated[int, Field(alias="maxFPS", description="int32")]
    metadata: Annotated[
        Metadata, Field(description="ASCII null-terminated (gameOptions)")
    ]
    millisecond: int
    minute: int
    month: int
    original_game_mode: Annotated[
        int, Field(alias="originalGameMode", description="int32")
    ]
    player_discons: Annotated[
        list[bool],
        Field(alias="playerDiscons", description="8 × 1 byte Bool (MAX_SLOTS)"),
    ]
    quit_early: Annotated[bool, Field(alias="quitEarly", description="1 byte Bool")]
    rank_points: Annotated[int, Field(alias="rankPoints", description="int32")]
    replay_name: Annotated[
        str, Field(alias="replayName", description="UTF-16 null-terminated")
    ]
    second: int
    time_stamp_begin: Annotated[
        int, Field(alias="timeStampBegin", description="int32 (replay_time_t)")
    ]
    time_stamp_end: Annotated[
        int, Field(alias="timeStampEnd", description="int32 (replay_time_t)")
    ]
    version: Annotated[str, Field(description="UTF-16 null-terminated")]
    version_number: Annotated[int, Field(alias="versionNumber", description="uint32")]
    year: Annotated[int, Field(description="SYSTEMTIME fields (8 × uint16)")]
