# generated by datamodel-codegen:
#   filename:  cncstats_schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class ObjectSummary(BaseModel):
    count: int
    total_spent: Annotated[int, Field(alias="totalSpent")]
