# generated by datamodel-codegen:
#   filename:  cncstats_schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class Academy(BaseModel):
    cleared_garrisoned_buildings: Annotated[
        int, Field(alias="clearedGarrisonedBuildings")
    ]
    control_groups_used: Annotated[int, Field(alias="controlGroupsUsed")]
    double_click_attack_move_orders_given: Annotated[
        int, Field(alias="doubleClickAttackMoveOrdersGiven")
    ]
    firestorms_created: Annotated[int, Field(alias="firestormsCreated")]
    gatherers_built: Annotated[int, Field(alias="gatherersBuilt")]
    generals_points_spent: Annotated[int, Field(alias="generalsPointsSpent")]
    guard_ability_used_count: Annotated[int, Field(alias="guardAbilityUsedCount")]
    heroes_built: Annotated[int, Field(alias="heroesBuilt")]
    mines_cleared: Annotated[int, Field(alias="minesCleared")]
    peons_built: Annotated[int, Field(alias="peonsBuilt")]
    salvage_collected: Annotated[int, Field(alias="salvageCollected")]
    secondary_income_units_built: Annotated[
        int, Field(alias="secondaryIncomeUnitsBuilt")
    ]
    special_powers_used: Annotated[int, Field(alias="specialPowersUsed")]
    structures_captured: Annotated[int, Field(alias="structuresCaptured")]
    structures_garrisoned: Annotated[int, Field(alias="structuresGarrisoned")]
    supply_centers_built: Annotated[int, Field(alias="supplyCentersBuilt")]
    upgrades_purchased: Annotated[int, Field(alias="upgradesPurchased")]
    vehicles_disguised: Annotated[int, Field(alias="vehiclesDisguised")]


class BattlePlanEvent(BaseModel):
    bombardment: int
    frame: int
    hold_the_line: Annotated[int, Field(alias="holdTheLine")]
    player: int
    search_and_destroy: Annotated[int, Field(alias="searchAndDestroy")]


class DeathEvent(BaseModel):
    frame: int
    player: int


class EnergyEvent(BaseModel):
    consumption: int
    frame: int
    player: int
    production: int


class IncomeBySource(BaseModel):
    black_market: Annotated[list[int], Field(alias="blackMarket")]
    bounty: list[int]
    crate: list[int]
    hacker: list[int]
    oil_derrick: Annotated[list[int], Field(alias="oilDerrick")]
    other: list[int]
    salvage: list[int]
    supply: list[int]
    supply_drop: Annotated[list[int], Field(alias="supplyDrop")]
    theft: list[int]


class RadarEvent(BaseModel):
    frame: int
    has_radar: Annotated[bool, Field(alias="hasRadar")]
    player: int


class RankEvent(BaseModel):
    frame: int
    player: int
    rank_level: Annotated[int, Field(alias="rankLevel")]


class SciencePointsEvent(BaseModel):
    frame: int
    player: int
    science_purchase_points: Annotated[int, Field(alias="sciencePurchasePoints")]


class SkillPointsEvent(BaseModel):
    frame: int
    player: int
    skill_points: Annotated[int, Field(alias="skillPoints")]


class TimeSeriesPlayer(BaseModel):
    index: int
    money: list[int]
    money_earned: Annotated[list[int], Field(alias="moneyEarned")]
    money_spent: Annotated[list[int], Field(alias="moneySpent")]
    income_by_source: Annotated[
        IncomeBySource | None, Field(alias="incomeBySource")
    ] = None


class TimeSeries(BaseModel):
    players: list[TimeSeriesPlayer]
