"""add_overrides

Revision ID: 245c9e30e90e
Revises: 46e452f5e547
Create Date: 2025-12-28 20:42:04.358242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245c9e30e90e'
down_revision: Union[str, Sequence[str], None] = '46e452f5e547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('winner_overrides',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('winning_team_id', sa.SmallInteger(), nullable=True),
    sa.Column('incomplete', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winner_overrides')
    # ### end Alembic commands ###
