"""add game version to parsed json

Revision ID: 516d57a75505
Revises: 6a0df7d8cf9b
Create Date: 2026-02-19 01:07:55.844226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516d57a75505'
down_revision: Union[str, Sequence[str], None] = '6a0df7d8cf9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_replay_json', sa.Column('game_version', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_replay_json', 'game_version')
    # ### end Alembic commands ###
