"""improved timestamps

Revision ID: 62cefcb100d5
Revises: 6603e8c3276c
Create Date: 2026-01-18 20:42:02.039635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62cefcb100d5'
down_revision: Union[str, Sequence[str], None] = '6603e8c3276c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_replay_json', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('replay_files', 'parsed_at')
    op.drop_column('replay_files', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replay_files', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('replay_files', sa.Column('parsed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('parsed_replay_json', 'updated_at')
    # ### end Alembic commands ###
