"""numtimestamps

Revision ID: 6603e8c3276c
Revises: 66459cb861f1
Create Date: 2026-01-18 20:28:46.736638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6603e8c3276c'
down_revision: Union[str, Sequence[str], None] = '66459cb861f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_replay_json', sa.Column('num_time_stamps', sa.Integer()))
    op.drop_column('parsed_replay_json', 'file_size_bytes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_replay_json', sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('parsed_replay_json', 'num_time_stamps')
    # ### end Alembic commands ###
