"""add game version

Revision ID: 6a0df7d8cf9b
Revises: 8da58256e2e7
Create Date: 2026-02-10 21:05:20.210279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a0df7d8cf9b'
down_revision: Union[str, Sequence[str], None] = '8da58256e2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('game_version', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'game_version')
    # ### end Alembic commands ###
