"""flag_for_has_enhanced_stats

Revision ID: 7cee6625bf8b
Revises: 62cefcb100d5
Create Date: 2026-01-18 21:39:28.603175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cee6625bf8b'
down_revision: Union[str, Sequence[str], None] = '62cefcb100d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_replay_json', sa.Column('has_enhanced_stats', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_replay_json', 'has_enhanced_stats')
    # ### end Alembic commands ###
