// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5000' | (string & {});
};

/**
 * General
 */
export type General = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | -1;

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MatchInfo
 */
export type MatchInfoInput = {
    /**
     * Id
     */
    id: number;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Map
     */
    map: string;
    winning_team: Team;
    /**
     * Players
     */
    players: Array<Player>;
    /**
     * Duration Minutes
     */
    duration_minutes: number;
    /**
     * Filename
     */
    filename: string;
    /**
     * Incomplete
     */
    incomplete: string;
    /**
     * Notes
     */
    notes: string;
};

/**
 * MatchInfo
 */
export type MatchInfoOutput = {
    /**
     * Id
     */
    id: number;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Map
     */
    map: string;
    winning_team: Team;
    /**
     * Players
     */
    players: Array<Player>;
    /**
     * Duration Minutes
     */
    duration_minutes: number;
    /**
     * Filename
     */
    filename: string;
    /**
     * Incomplete
     */
    incomplete: string;
    /**
     * Notes
     */
    notes: string;
};

/**
 * Matches
 */
export type Matches = {
    /**
     * Matches
     */
    matches: Array<MatchInfoOutput>;
};

/**
 * Player
 */
export type Player = {
    /**
     * Name
     */
    name: string;
    general: General;
    team: Team;
};

/**
 * Team
 */
export type Team = 0 | 1 | 2 | 3 | 4 | -1;

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMatchesApiMatchesMatchCountGetData = {
    body?: never;
    path: {
        /**
         * Match Count
         */
        match_count: number;
    };
    query?: never;
    url: '/api/matches/{match_count}';
};

export type GetMatchesApiMatchesMatchCountGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMatchesApiMatchesMatchCountGetError = GetMatchesApiMatchesMatchCountGetErrors[keyof GetMatchesApiMatchesMatchCountGetErrors];

export type GetMatchesApiMatchesMatchCountGetResponses = {
    /**
     * Successful Response
     */
    200: Matches;
};

export type GetMatchesApiMatchesMatchCountGetResponse = GetMatchesApiMatchesMatchCountGetResponses[keyof GetMatchesApiMatchesMatchCountGetResponses];
