export const MAPLIST = [
  "2v2 tournament desert.webp",
  "8p_oil rampage.webp",
  "AllBuildingsAllSidesUnitTest_Save.webp",
  "Allstars v3.webp",
  "Ancient Keep Bal [WBC2021].webp",
  "Armored Frenzy v1.webp",
  "At Doom's Gate [WBC2023].webp",
  "BUG_SavedGameandEnabledFolders.webp",
  "Battle Plan ZH v3.webp",
  "Beijing Uprise v4.webp",
  "Chunk Island [WBC2023].webp",
  "Coastal Shock [WBC2023].webp",
  "Desert Gauntlet v2.webp",
  "Echo Isle [WBC2023].webp",
  "Fergi's Revenge v2.webp",
  "Flower Oases.webp",
  "Forest of Camelot ZH v4.webp",
  "Forgotten Valley [WBC2022].webp",
  "Frontier Rails v2 [WBC2022].webp",
  "GC_ChemGeneral.webp",
  "GC_ChinaBoss.webp",
  "GC_DemolitionGeneral.webp",
  "GC_LaserGeneral.webp",
  "GC_Stealth.webp",
  "GC_SuperWeaponsGeneral.webp",
  "Glacier 6 [WBC2023].webp",
  "Greek Shores v2.webp",
  "Han Dynasty v3.webp",
  "Highland Offensive v1 [scotmap].webp",
  "Highland Rift v1 [scotmap].webp",
  "Koujou Okawa v3.webp",
  "Last Lagoon v1 [scotmap].webp",
  "MD_CHI01.webp",
  "MD_CHI02.webp",
  "MD_CHI03.webp",
  "MD_CHI04.webp",
  "MD_CHI05.webp",
  "MD_CHI05_END.webp",
  "MD_CHI05_Intro.webp",
  "MD_GLA01.webp",
  "MD_GLA02.webp",
  "MD_GLA02_CINE.webp",
  "MD_GLA03.webp",
  "MD_GLA03_CINE.webp",
  "MD_GLA03_END.webp",
  "MD_GLA04.webp",
  "MD_GLA04_INTRO.webp",
  "MD_GLA04_Sound.webp",
  "MD_GLA05.webp",
  "MD_GLA05_END.webp",
  "MD_GLA05_INTRO.webp",
  "MD_ShellMap.webp",
  "MD_USA01.webp",
  "MD_USA01_CINE.webp",
  "MD_USA02.webp",
  "MD_USA02_INTRO.webp",
  "MD_USA02_INTRO_NS.webp",
  "MD_USA03_END.webp",
  "MD_USA03_END1.webp",
  "MD_USA03_MID_CINE.webp",
  "MD_USA04.webp",
  "MD_USA04_CINE.webp",
  "MD_USA04_Intro.webp",
  "MD_USA05.webp",
  "MD_USA06_INTRO.webp",
  "Mt Pinatubo [WBC2022].webp",
  "Naval Port Reyes v4 [WBC2020].webp",
  "Oxygen 1.webp",
  "Pagasa Fortress [WBC2023].webp",
  "Purple Hearts [WBC2021].webp",
  "Radiation Ultima [WBC2021].webp",
  "Rebirth Valley v1.webp",
  "Sand Islands v5.webp",
  "ShellMapMD.webp",
  "Shivas Paradise v4.webp",
  "Storming Harvest v2 [WBC2021].webp",
  "Swamp Assault v3 [WBC2021].webp",
  "Sylt v5.webp",
  "Taal Lake [WBC2023].webp",
  "Taiga Terror.webp",
  "Thermopylae v5.webp",
  "Tiny Tactics ZH v2.webp",
  "Twenty4Seven [WBC2021].webp",
  "USA05_EndsConflict.webp",
  "USA05_EndsConflict_INTRO.webp",
  "USA05_EndsConflict_INTRO_N.webp",
  "USA07-TaskForces.webp",
  "Wells of Chaos v4.webp",
  "[AOD] Air Wave 2013 (China AI) (Pro Players) [pashacnc com].webp",
  "[AOD] Charge 2010 Final [pashacnc com].webp",
  "[AOD] Circle 4p by Vocux.webp",
  "[AOD] City 4p (China AI) by Vocux [pashacnc com].webp",
  "[AOD] Crossfire (USA AI) v2.webp",
  "[AOD] Cute v9 by I^Love^Mixery.webp",
  "[AOD] Defend till the End Remastered.webp",
  "[AOD] Demilitarized Zone (China AI) by Twinsen [pashacnc com].webp",
  "[AOD] Extreme Circle by Twinsen [pashacnc com].webp",
  "[AOD] Extreme Spiral by Twinsen [pashacnc com].webp",
  "[AOD] FIFA World Cup Terrorist Takedown v5.webp",
  "[AOD] Fort Blood by RDB v2 [pashacnc com].webp",
  "[AOD] GC Laser General by I^Love^Mixery.webp",
  "[AOD] Green Lands by ONE [pashacnc com].webp",
  "[AOD] Hardest AOD.webp",
  "[AOD] Mission Black Fork - GLA Out of Control v2.webp",
  "[AOD] No Money AOD.webp",
  "[AOD] No Name For This Map by ONE.webp",
  "[AOD] Pasha Challenges You (4P) v2 [pashacnc com].webp",
  "[AOD] Pasha Fire Circle [No Laser, EMP] (AI USA) Final V02 [pashacnc com].webp",
  "[AOD] Pasha's Back to Back Defense v1 [pashacnc com].webp",
  "[AOD] Pasha's Pentagram v3 [pashacnc com].webp",
  "[AOD] Pasha's R&D Zone v2 [pashacnc com].webp",
  "[AOD] Pentagram by Nemes1s & wWw (air-v2) [pashacnc com].webp",
  "[AOD] Super V by RDB v2 [pashacnc com].webp",
  "[AOD] Swarm by wWw [pashacnc com].webp",
  "[AOD] The Moment of Truth by Kingnino.webp",
  "[AOD] The Persian Gulf by Rebel [pashacnc com].webp",
  "[AOD] Time Machine 2021 by wWw [pashacnc com].webp",
  "[AOD] Time or Die (AI GLA slot 8).webp",
  "[AOD] Triangle Base v2 [pashacnc com].webp",
  "[AOD] Trinity by Evanz1987 fixed by Pasha v2 [pashacnc com].webp",
  "[AOD] U Turn [pashacnc com].webp",
  "[AOD] Ultimate Overlord by Twinsen v3 [pashacnc com].webp",
  "[AOD] Versus AOD v077.webp",
  "[Compstomp] 4vs4 Massacre ZH.webp",
  "[Coop] GLA vs China - Call of Dragon ZH v0-2.webp",
  "[Coop] Iranian Counterstrike ZH.webp",
  "[Coop] North-Korea Conflict.webp",
  "[Mission] Avis Interitus.webp",
  "[Mission] Operation Kihill Beach - Part 1 v2.webp",
  "[Mission] Operation Kihill Beach - Part 2 - Brutal ALPHA v2.webp",
  "[Mission] Operation Kihill Beach - Part 2 - Hard ALPHA v2.webp",
  "[Mission] Operation Kihill Beach - Part 2 - Normal ALPHA v2.webp",
  "[Mod] Battle Royale v2.webp",
  "[Mod] CTF - Armored Fury v2.webp",
  "[Mod] CTF - Coral Islands v2.webp",
  "[Mod] CTF - Defcon 51 v7.webp",
  "[Mod] CTF - Imperial Palace v8.webp",
  "[Mod] CTF - Tournament A v2.webp",
  "[Mod] CTF FFA - Armored Fury v3.webp",
  "[Mod] CTF FFA - Conflict in the Mediterranean v5.webp",
  "[Mod] CTF FFA - Coral Islands v2.webp",
  "[Mod] CTF FFA - Mortal Temptation v2.webp",
  "[Mod] CTF FFA - Purple Hearts v4.webp",
  "[Mod] CTF FFA - Trinity Island v2.webp",
  "[Mod] Cash Bounty ZH Restored v2.webp",
  "[Mod] Cash Bounty ZH by Moqqy v4.webp",
  "[Mod] Casino - Islands Of Fortune v6.webp",
  "[Mod] Casino - Resurrection Five v7.webp",
  "[Mod] Casino - Resurrection Four v8.webp",
  "[Mod] Casino - Resurrection Six v11.webp",
  "[Mod] Casino - Resurrection Three v6.webp",
  "[Mod] Casino - Resurrection Two v8.webp",
  "[Mod] Casino 2v2 - Resurrection Two v2.webp",
  "[Mod] Dual-Army - Tournament A.webp",
  "[Mod] Dual-Army - Tournament Island.webp",
  "[Mod] Football v3.webp",
  "[Mod] Mayhem - Defcon 51.webp",
  "[Mod] Mayhem - Defcon 6 v6.webp",
  "[Mod] Money Fields Reloaded.webp",
  "[Mod] P-U-B-G v2.webp",
  "[Mod] Race Map by SD v4.webp",
  "[Mod] Rebel Uprise 1 v1.webp",
  "[Mod] Rebel Uprise 2 v10.webp",
  "[NoMoney] !1v1 cXn.webp",
  "[NoMoney] !2v2 cXn.webp",
  "[NoMoney] !3v3 cXn.webp",
  "[NoMoney] 1v1 Super v2.webp",
  "[NoMoney] 1v1 Survival.webp",
  "[NoMoney] 1v1v1v1v1v1 CCG by Anji v1.webp",
  "[NoMoney] 1v1v1v1v1v1 by Krisu v5.webp",
  "[NoMoney] Blue Fox + Jono Remix ZH.webp",
  "[NoMoney] Immediately Action! v2x3.webp",
  "[NoMoney] Lots of Fun v3.webp",
  "[NoMoney] Volcano.webp",
  "[RANK] A New Tragedy ZH v2.webp",
  "[RANK] AKAs Magic ZH v1.webp",
  "[RANK] Aeon of Excalibur ZH v1.webp",
  "[RANK] Alfies Haven ZH v1.webp",
  "[RANK] Arctic Arena ZH v1.webp",
  "[RANK] Arctic Lagoon ZH v2.webp",
  "[RANK] Arizona Airfield ZH v1.webp",
  "[RANK] Battle Between Them ZH v1.webp",
  "[RANK] Battleship Bay ZH v1.webp",
  "[RANK] Black Hell ZH v1.webp",
  "[RANK] Blue Hole ZH v1.webp",
  "[RANK] Dammed Cottages ZH v1.webp",
  "[RANK] Dammed Korhal ZH v1.webp",
  "[RANK] Dammed Scorpion ZH v1.webp",
  "[RANK] Desert Fury ZH v1.webp",
  "[RANK] Desert Vortex ZH v1.webp",
  "[RANK] Dominion ZH v1.webp",
  "[RANK] Double Damination ZH v1.webp",
  "[RANK] Dry River ZH v1.webp",
  "[RANK] Dust Devil ZH v1.webp",
  "[RANK] Echo ZH v1.webp",
  "[RANK] Endboss ZH v1.webp",
  "[RANK] Fort Payne ZH v1.webp",
  "[RANK] Hanamura Temple ZH v1.webp",
  "[RANK] Lethal Mill ZH v1.webp",
  "[RANK] Lost Cause ZH v1.webp",
  "[RANK] Mt Pinatubo ZH v1.webp",
  "[RANK] Muddy Madness ZH v1.webp",
  "[RANK] Natural Threats ZH v4.webp",
  "[RANK] Persian Gulf Conflict ZH v1.webp",
  "[RANK] Proxy War ZH v1.webp",
  "[RANK] Rainforest Reservoir ZH v1.webp",
  "[RANK] Sacred Land ZH v1.webp",
  "[RANK] Sakura Forest II ZH v1.webp",
  "[RANK] Salt Lake River ZH v1.webp",
  "[RANK] Snowy Drought ZH v5.webp",
  "[RANK] Snowy Roads ZH v1.webp",
  "[RANK] Spiders Island ZH v1.webp",
  "[RANK] Storm Surge ZH v1.webp",
  "[RANK] Tiny Tactics ZH v1.webp",
  "[RANK] Twisted Treeline ZH v1.webp",
  "[RANK] Umbrella Corps ZH v1.webp",
  "[RANK] Urban Downfall ZH v1.webp",
  "[RANK] Wastelands Dust ZH v1.webp",
  "[RANK] Winding River Revised ZH v1.webp",
  "[RANK] Yelling Avalanche ZH v1.webp",
  "[go][rank] snowy drought zh v5.webp",
  "[nmc 2x2] coastline wold.webp",
  "[nmc] snowy drought.webp",
  "[wbc winner] subjugation mk 14.webp",
  "[wbc2020] arizona.webp",
  "_Art Review New Units.webp",
  "_vs5_fluch der karibik zh.webp",
  "battle of otis.webp",
  "canyon frost zh v1.webp",
  "casino diamond v2  pro.webp",
  "castle wolfenstein.webp",
  "clutha river.webp",
  "cp 3v5 look out now2.webp",
  "cp 4v4 ob32 paranoid.webp",
  "defcon 6 pro.webp",
  "desert trap.webp",
  "dry plague.webp",
  "exkalibur_zh.webp",
  "frozen vanguard v2.webp",
  "last hope.webp",
  "maps_alpine assault_alpine assault.webp",
  "maps_barrenbadlands_barrenbadlands.webp",
  "maps_bear town beatdown_bear town beatdown.webp",
  "maps_bitter winter_bitter winter.webp",
  "maps_bombardment beach_bombardment beach.webp",
  "maps_cairo commandos_cairo commandos.webp",
  "maps_dark mountain_dark mountain.webp",
  "maps_dark night_dark night.webp",
  "maps_death valley_death valley.webp",
  "maps_defcon6_defcon6.webp",
  "maps_desert fury_desert fury.webp",
  "maps_destruction station_destruction station.webp",
  "maps_dogsofwar_dogsofwar.webp",
  "maps_dust devil_dust devil.webp",
  "maps_eastern everglades_eastern everglades.webp",
  "maps_el scorcho_el scorcho.webp",
  "maps_fallen empire_fallen empire.webp",
  "maps_final crusade_final crusade.webp",
  "maps_flash effect_flash effect.webp",
  "maps_flash fire_flash fire.webp",
  "maps_floodedplains_floodedplains.webp",
  "maps_forgottenforestzh_forgottenforestzh.webp",
  "maps_fortress avalanche_fortress avalanche.webp",
  "maps_free fire zone_free fire zone.webp",
  "maps_golden oasis_golden oasis.webp",
  "maps_green pastures_green pastures.webp",
  "maps_heartland shield_heartland shield.webp",
  "maps_homeland alliance_homeland alliance.webp",
  "maps_hostile dawn_hostile dawn.webp",
  "maps_iron dragon_iron dragon.webp",
  "maps_killing fields_killing fields.webp",
  "maps_leipzig lowlands_leipzig lowlands.webp",
  "maps_lights out_lights out.webp",
  "maps_lone eagle_lone eagle.webp",
  "maps_manic aggression_manic aggression.webp",
  "maps_mountain guns_mountain guns.webp",
  "maps_mountainfox_mountainfox.webp",
  "maps_northamerica_northamerica.webp",
  "maps_overland_overland.webp",
  "maps_red rock_red rock.webp",
  "maps_rocky rampage_rocky rampage.webp",
  "maps_rogue agent_rogue agent.webp",
  "maps_sand serpent_sand serpent.webp",
  "maps_seaside mutiny_seaside mutiny.webp",
  "maps_silent river_silent river.webp",
  "maps_thefrontline_thefrontline.webp",
  "maps_tournament city_tournament city.webp",
  "maps_tournament continent_tournament continent.webp",
  "maps_tournament desert_tournament desert.webp",
  "maps_tournament island_tournament island.webp",
  "maps_tournament lake_tournament lake.webp",
  "maps_tournament plains_tournament plains.webp",
  "maps_tournament tundra_tournament tundra.webp",
  "maps_tournament urban_tournament urban.webp",
  "maps_tournamenta_tournamenta.webp",
  "maps_tournamentb_tournamentb.webp",
  "maps_twilight flame_twilight flame.webp",
  "maps_victory valley_victory valley.webp",
  "maps_wasteland warlords_wasteland warlords.webp",
  "maps_whiteout_whiteout.webp",
  "maps_winding river_winding river.webp",
  "maps_winter wolf_winter wolf.webp",
  "shallow grave.webp",
  "sin city.webp",
  "snow feud se.webp",
  "snowflake.webp",
  "super map no money !!!! v2.webp",
  "terra fantastica.webp",
  "thru the town.webp",
  "thy kingdom lagoon [wbc2022].webp",
  "tournament valley 2.webp",
  "toxic assault.webp",
  "triple_threat.webp",
  "tropicalflame.webp",
  "tumbleweed tactics v1.webp",
  "twilight fire 2.webp",
  "userdata_maps_! 1v1 ! super no money map v2_! 1v1 ! super no money map v2.webp",
  "userdata_maps_!!! superderrick_!!! superderrick.webp",
  "userdata_maps_!!! superderrik_!!! superderrik.webp",
  "userdata_maps_!1v1 cxn_!1v1 cxn.webp",
  "userdata_maps_!2v2 cxn_!2v2 cxn.webp",
  "userdata_maps_!3v3 cxn_!3v3 cxn.webp",
  "userdata_maps_!super map no money random by cetx_!super map no money random by cetx.webp",
  "userdata_maps_( 1v1 ) no money survival_( 1v1 ) no money survival.webp",
  "userdata_maps_(3 letter names required)_(3 letter names required).webp",
  "userdata_maps_1v1v1 no money pro_1v1v1 no money pro.webp",
  "userdata_maps_1v1v1v1v1 small v2_1v1v1v1v1 small v2.webp",
  "userdata_maps_1v1v1v1v1 small_1v1v1v1v1 small.webp",
  "userdata_maps_1v1v1v1v1v1 no money by krisu fair play5_1v1v1v1v1v1 no money by krisu fair play5.webp",
  "userdata_maps_6p cb restored by joker v2_6p cb restored by joker v2.webp",
  "userdata_maps_6p cb zh, moqqy balanced 3_6p cb zh, moqqy balanced 3.webp",
  "userdata_maps_[aod] cobalt rush v2_[aod] cobalt rush v2.webp",
  "userdata_maps_[aod] cobalt rush_[aod] cobalt rush.webp",
  "userdata_maps_[go] swamp assault v3 [wbc2021]_[go] swamp assault v3 [wbc2021].webp",
  "userdata_maps_[rank] [nmc 2x2] aftermath_[rank] [nmc 2x2] aftermath.webp",
  "userdata_maps_[rank] [nmc 2x2] coastline wold_[rank] [nmc 2x2] coastline wold.webp",
  "userdata_maps_[rank] [nmc 2x2] ghostly rocks_[rank] [nmc 2x2] ghostly rocks.webp",
  "userdata_maps_[rank] [nmc 2x2] maguso_[rank] [nmc 2x2] maguso.webp",
  "userdata_maps_[rank] [nmc 2x2] middle fight_[rank] [nmc 2x2] middle fight.webp",
  "userdata_maps_[rank] [nmc] battle on the river_[rank] [nmc] battle on the river.webp",
  "userdata_maps_[rank] [nmc] blasted lands_[rank] [nmc] blasted lands.webp",
  "userdata_maps_[rank] [nmc] gorge drought_[rank] [nmc] gorge drought.webp",
  "userdata_maps_[rank] [nmc] plant waste_[rank] [nmc] plant waste.webp",
  "userdata_maps_[rank] [nmc] summer arena_[rank] [nmc] summer arena.webp",
  "userdata_maps_[rank] [nmc] tournament arena_[rank] [nmc] tournament arena.webp",
  "userdata_maps_[rank] [nmc] tournament city_[rank] [nmc] tournament city.webp",
  "userdata_maps_[rank] a new tragedy zh v1_[rank] a new tragedy zh v1.webp",
  "userdata_maps_[rank] abandoned desert zh v1_[rank] abandoned desert zh v1.webp",
  "userdata_maps_[rank] abandoned farms zh v1_[rank] abandoned farms zh v1.webp",
  "userdata_maps_[rank] alterac pass zh v1_[rank] alterac pass zh v1.webp",
  "userdata_maps_[rank] ammars sandcastles v3_[rank] ammars sandcastles v3.webp",
  "userdata_maps_[rank] animals of the generals zh v1_[rank] animals of the generals zh v1.webp",
  "userdata_maps_[rank] annihilation_[rank] annihilation.webp",
  "userdata_maps_[rank] archaic meltdown zh v1_[rank] archaic meltdown zh v1.webp",
  "userdata_maps_[rank] area j1_[rank] area j1.webp",
  "userdata_maps_[rank] arena of war zh v1_[rank] arena of war zh v1.webp",
  "userdata_maps_[rank] artic lagoon_[rank] artic lagoon.webp",
  "userdata_maps_[rank] australia zh v1_[rank] australia zh v1.webp",
  "userdata_maps_[rank] aztec empire zh v1_[rank] aztec empire zh v1.webp",
  "userdata_maps_[rank] barren badlands balanced zh v1_[rank] barren badlands balanced zh v1.webp",
  "userdata_maps_[rank] barren badlands balanced zh v2_[rank] barren badlands balanced zh v2.webp",
  "userdata_maps_[rank] battle for reach zh v1_[rank] battle for reach zh v1.webp",
  "userdata_maps_[rank] battle plan zh v1_[rank] battle plan zh v1.webp",
  "userdata_maps_[rank] bitter winter balanced nocars zh v1_[rank] bitter winter balanced nocars zh v1.webp",
  "userdata_maps_[rank] blizzard badlands reloaded_[rank] blizzard badlands reloaded.webp",
  "userdata_maps_[rank] blizzard badlands zhv5_[rank] blizzard badlands zhv5.webp",
  "userdata_maps_[rank] blossoming valley zh v1_[rank] blossoming valley zh v1.webp",
  "userdata_maps_[rank] bounty v3_[rank] bounty v3.webp",
  "userdata_maps_[rank] bozic destruction zh v3_[rank] bozic destruction zh v3.webp",
  "userdata_maps_[rank] burning deadline zh v1_[rank] burning deadline zh v1.webp",
  "userdata_maps_[rank] bursting asunder zh v1_[rank] bursting asunder zh v1.webp",
  "userdata_maps_[rank] canyon of the dead v1_[rank] canyon of the dead v1.webp",
  "userdata_maps_[rank] canyon of the dead zh v2_[rank] canyon of the dead zh v2.webp",
  "userdata_maps_[rank] christmas zh v3_[rank] christmas zh v3.webp",
  "userdata_maps_[rank] coastal conflict zh v2_[rank] coastal conflict zh v2.webp",
  "userdata_maps_[rank] cold territory zh v2_[rank] cold territory zh v2.webp",
  "userdata_maps_[rank] combat encounter zh v1_[rank] combat encounter zh v1.webp",
  "userdata_maps_[rank] combat island zh v1_[rank] combat island zh v1.webp",
  "userdata_maps_[rank] conflict zone zh v2_[rank] conflict zone zh v2.webp",
  "userdata_maps_[rank] coral islands zh v1_[rank] coral islands zh v1.webp",
  "userdata_maps_[rank] coral islands zh v2_[rank] coral islands zh v2.webp",
  "userdata_maps_[rank] cursed hollows zh v1_[rank] cursed hollows zh v1.webp",
  "userdata_maps_[rank] danger close zh_[rank] danger close zh.webp",
  "userdata_maps_[rank] dedusu zh v1_[rank] dedusu zh v1.webp",
  "userdata_maps_[rank] defcon balanced zh v1_[rank] defcon balanced zh v1.webp",
  "userdata_maps_[rank] desert combat zh v2_[rank] desert combat zh v2.webp",
  "userdata_maps_[rank] desert quadrant zh v1_[rank] desert quadrant zh v1.webp",
  "userdata_maps_[rank] deserted village v3_[rank] deserted village v3.webp",
  "userdata_maps_[rank] desolated district zh v1_[rank] desolated district zh v1.webp",
  "userdata_maps_[rank] devastated oasis zh v2_[rank] devastated oasis zh v2.webp",
  "userdata_maps_[rank] diamonds edge zh v1_[rank] diamonds edge zh v1.webp",
  "userdata_maps_[rank] district 10 zh v1_[rank] district 10 zh v1.webp",
  "userdata_maps_[rank] down the road zh v1_[rank] down the road zh v1.webp",
  "userdata_maps_[rank] drallim desert zh v2_[rank] drallim desert zh v2.webp",
  "userdata_maps_[rank] drowning horses zh v1_[rank] drowning horses zh v1.webp",
  "userdata_maps_[rank] dusty rampage zh v1_[rank] dusty rampage zh v1.webp",
  "userdata_maps_[rank] eagle eye_[rank] eagle eye.webp",
  "userdata_maps_[rank] early spring zh v1_[rank] early spring zh v1.webp",
  "userdata_maps_[rank] early spring zh v2_[rank] early spring zh v2.webp",
  "userdata_maps_[rank] egyptian oasis zh v1_[rank] egyptian oasis zh v1.webp",
  "userdata_maps_[rank] eight zh v2_[rank] eight zh v2.webp",
  "userdata_maps_[rank] embattled land zh v2_[rank] embattled land zh v2.webp",
  "userdata_maps_[rank] epsilon 6 zh v1_[rank] epsilon 6 zh v1.webp",
  "userdata_maps_[rank] evergreen lagoon_[rank] evergreen lagoon.webp",
  "userdata_maps_[rank] fall out zh v1_[rank] fall out zh v1.webp",
  "userdata_maps_[rank] farmlands of the fallen zh v1_[rank] farmlands of the fallen zh v1.webp",
  "userdata_maps_[rank] fe nobug zh v1_[rank] fe nobug zh v1.webp",
  "userdata_maps_[rank] fe nowall zh v1_[rank] fe nowall zh v1.webp",
  "userdata_maps_[rank] final crossroad zh v1_[rank] final crossroad zh v1.webp",
  "userdata_maps_[rank] final crusade balanced zh v1_[rank] final crusade balanced zh v1.webp",
  "userdata_maps_[rank] final crusade fixedv2_[rank] final crusade fixedv2.webp",
  "userdata_maps_[rank] final departure zh v1_[rank] final departure zh v1.webp",
  "userdata_maps_[rank] flash fire balanced zh v1_[rank] flash fire balanced zh v1.webp",
  "userdata_maps_[rank] forbidden takover zh v3_[rank] forbidden takover zh v3.webp",
  "userdata_maps_[rank] forest of oblivion zh v1_[rank] forest of oblivion zh v1.webp",
  "userdata_maps_[rank] forgotten air battle v4_[rank] forgotten air battle v4.webp",
  "userdata_maps_[rank] forgotten air battle zh v5_[rank] forgotten air battle zh v5.webp",
  "userdata_maps_[rank] forgotten factory zh v1_[rank] forgotten factory zh v1.webp",
  "userdata_maps_[rank] forgotten ruins_[rank] forgotten ruins.webp",
  "userdata_maps_[rank] four victory zh v1_[rank] four victory zh v1.webp",
  "userdata_maps_[rank] freezing bursa zh v1_[rank] freezing bursa zh v1.webp",
  "userdata_maps_[rank] freezing rain zh v2_[rank] freezing rain zh v2.webp",
  "userdata_maps_[rank] frog prince zh v2_[rank] frog prince zh v2.webp",
  "userdata_maps_[rank] frontier rails zh v1_[rank] frontier rails zh v1.webp",
  "userdata_maps_[rank] frozen ruins_[rank] frozen ruins.webp",
  "userdata_maps_[rank] garden of terror zh v1_[rank] garden of terror zh v1.webp",
  "userdata_maps_[rank] glacial shores zh v2_[rank] glacial shores zh v2.webp",
  "userdata_maps_[rank] glacier 6 zh v1_[rank] glacier 6 zh v1.webp",
  "userdata_maps_[rank] gold cobra_[rank] gold cobra.webp",
  "userdata_maps_[rank] green goon zh v1_[rank] green goon zh v1.webp",
  "userdata_maps_[rank] green silk zh v1_[rank] green silk zh v1.webp",
  "userdata_maps_[rank] hard winter zh v2_[rank] hard winter zh v2.webp",
  "userdata_maps_[rank] hell on rails zh v1_[rank] hell on rails zh v1.webp",
  "userdata_maps_[rank] hidden pearls zh v1_[rank] hidden pearls zh v1.webp",
  "userdata_maps_[rank] hidden treasures v2_[rank] hidden treasures v2.webp",
  "userdata_maps_[rank] highway 99 zh v1_[rank] highway 99 zh v1.webp",
  "userdata_maps_[rank] highway 99 zh v2_[rank] highway 99 zh v2.webp",
  "userdata_maps_[rank] homeland rocks zh v4_[rank] homeland rocks zh v4.webp",
  "userdata_maps_[rank] icy frontier zh v1_[rank] icy frontier zh v1.webp",
  "userdata_maps_[rank] imminent victory zh v2_[rank] imminent victory zh v2.webp",
  "userdata_maps_[rank] irish front zh v1_[rank] irish front zh v1.webp",
  "userdata_maps_[rank] jungle wolf zh v2_[rank] jungle wolf zh v2.webp",
  "userdata_maps_[rank] jungle wolf zh v3_[rank] jungle wolf zh v3.webp",
  "userdata_maps_[rank] lagoon zh v2_[rank] lagoon zh v2.webp",
  "userdata_maps_[rank] lagoon zh v4_[rank] lagoon zh v4.webp",
  "userdata_maps_[rank] lagoon zh v5_[rank] lagoon zh v5.webp",
  "userdata_maps_[rank] lion heart zh v1_[rank] lion heart zh v1.webp",
  "userdata_maps_[rank] liquid gold zh v2_[rank] liquid gold zh v2.webp",
  "userdata_maps_[rank] lost temple zh v1_[rank] lost temple zh v1.webp",
  "userdata_maps_[rank] lost valley v2_[rank] lost valley v2.webp",
  "userdata_maps_[rank] maguso zh v3_[rank] maguso zh v3.webp",
  "userdata_maps_[rank] make make 2 zh v3_[rank] make make 2 zh v3.webp",
  "userdata_maps_[rank] make make 2 zh v4_[rank] make make 2 zh v4.webp",
  "userdata_maps_[rank] make make 4 zh v2_[rank] make make 4 zh v2.webp",
  "userdata_maps_[rank] medieval era zh v1_[rank] medieval era zh v1.webp",
  "userdata_maps_[rank] melting snow zh v3_[rank] melting snow zh v3.webp",
  "userdata_maps_[rank] melting snow zh v4_[rank] melting snow zh v4.webp",
  "userdata_maps_[rank] mojave desert zh v1_[rank] mojave desert zh v1.webp",
  "userdata_maps_[rank] morning dew zh v1_[rank] morning dew zh v1.webp",
  "userdata_maps_[rank] mountain mayhem v2_[rank] mountain mayhem v2.webp",
  "userdata_maps_[rank] mountain oil zh v1_[rank] mountain oil zh v1.webp",
  "userdata_maps_[rank] mountain path zh v4_[rank] mountain path zh v4.webp",
  "userdata_maps_[rank] natural threats zh v3_[rank] natural threats zh v3.webp",
  "userdata_maps_[rank] naval port reyes zh v1_[rank] naval port reyes zh v1.webp",
  "userdata_maps_[rank] nocky mountains zh v1_[rank] nocky mountains zh v1.webp",
  "userdata_maps_[rank] oil carnage zh v1_[rank] oil carnage zh v1.webp",
  "userdata_maps_[rank] oil oasis zh v1_[rank] oil oasis zh v1.webp",
  "userdata_maps_[rank] oil rampage zh v1_[rank] oil rampage zh v1.webp",
  "userdata_maps_[rank] onza map v1_[rank] onza map v1.webp",
  "userdata_maps_[rank] pagasa fortress zh v1_[rank] pagasa fortress zh v1.webp",
  "userdata_maps_[rank] philippine highlands zh v1_[rank] philippine highlands zh v1.webp",
  "userdata_maps_[rank] planet coyon zh v1_[rank] planet coyon zh v1.webp",
  "userdata_maps_[rank] plant waste zh v2_[rank] plant waste zh v2.webp",
  "userdata_maps_[rank] purification zh v1_[rank] purification zh v1.webp",
  "userdata_maps_[rank] rebellion zh v1_[rank] rebellion zh v1.webp",
  "userdata_maps_[rank] rubies and pearls zh v1_[rank] rubies and pearls zh v1.webp",
  "userdata_maps_[rank] sand scorpion_[rank] sand scorpion.webp",
  "userdata_maps_[rank] sand serpent balanced zh v1_[rank] sand serpent balanced zh v1.webp",
  "userdata_maps_[rank] sand serpent fixed_[rank] sand serpent fixed.webp",
  "userdata_maps_[rank] scaraa zh v1_[rank] scaraa zh v1.webp",
  "userdata_maps_[rank] scorched earth zh v3_[rank] scorched earth zh v3.webp",
  "userdata_maps_[rank] scorching heat zh v1_[rank] scorching heat zh v1.webp",
  "userdata_maps_[rank] silicon valley zh v1_[rank] silicon valley zh v1.webp",
  "userdata_maps_[rank] sleeping dragon v3_[rank] sleeping dragon v3.webp",
  "userdata_maps_[rank] snow aggression v3_[rank] snow aggression v3.webp",
  "userdata_maps_[rank] snow blind zh v2_[rank] snow blind zh v2.webp",
  "userdata_maps_[rank] snowy drought v2_[rank] snowy drought v2.webp",
  "userdata_maps_[rank] snowy drought v4_[rank] snowy drought v4.webp",
  "userdata_maps_[rank] sovereignty zh v1_[rank] sovereignty zh v1.webp",
  "userdata_maps_[rank] stonehenge zh v1_[rank] stonehenge zh v1.webp",
  "userdata_maps_[rank] storm valley_[rank] storm valley.webp",
  "userdata_maps_[rank] subjugation zh v1_[rank] subjugation zh v1.webp",
  "userdata_maps_[rank] target tournament zh v1_[rank] target tournament zh v1.webp",
  "userdata_maps_[rank] td classic nocars zh v1_[rank] td classic nocars zh v1.webp",
  "userdata_maps_[rank] td classic zh v1_[rank] td classic zh v1.webp",
  "userdata_maps_[rank] td nobugs zh v1_[rank] td nobugs zh v1.webp",
  "userdata_maps_[rank] td nobugscars zh v1_[rank] td nobugscars zh v1.webp",
  "userdata_maps_[rank] td openmiddle nocars zh v1_[rank] td openmiddle nocars zh v1.webp",
  "userdata_maps_[rank] td openmiddle zh v1_[rank] td openmiddle zh v1.webp",
  "userdata_maps_[rank] td resurrection v2_[rank] td resurrection v2.webp",
  "userdata_maps_[rank] td winter zh v2_[rank] td winter zh v2.webp",
  "userdata_maps_[rank] temperate woods zh v1_[rank] temperate woods zh v1.webp",
  "userdata_maps_[rank] territorial dispute zh v1_[rank] territorial dispute zh v1.webp",
  "userdata_maps_[rank] the first strike zh v2_[rank] the first strike zh v2.webp",
  "userdata_maps_[rank] the path zh v2_[rank] the path zh v2.webp",
  "userdata_maps_[rank] the survivors zh v1_[rank] the survivors zh v1.webp",
  "userdata_maps_[rank] total domination no sdz zh v1_[rank] total domination no sdz zh v1.webp",
  "userdata_maps_[rank] total domination sdz zh v1_[rank] total domination sdz zh v1.webp",
  "userdata_maps_[rank] tournament a zh v1_[rank] tournament a zh v1.webp",
  "userdata_maps_[rank] tournament c zh v1_[rank] tournament c zh v1.webp",
  "userdata_maps_[rank] tournament d zh v1_[rank] tournament d zh v1.webp",
  "userdata_maps_[rank] tournament delta zh v2_[rank] tournament delta zh v2.webp",
  "userdata_maps_[rank] tournament himalaya zh v1_[rank] tournament himalaya zh v1.webp",
  "userdata_maps_[rank] tournament in the canyon b zh v2_[rank] tournament in the canyon b zh v2.webp",
  "userdata_maps_[rank] tournament in the canyon va_[rank] tournament in the canyon va.webp",
  "userdata_maps_[rank] tournament in the canyon vb_[rank] tournament in the canyon vb.webp",
  "userdata_maps_[rank] toxic zh v3_[rank] toxic zh v3.webp",
  "userdata_maps_[rank] twister land zh v1_[rank] twister land zh v1.webp",
  "userdata_maps_[rank] uneven heights v2_[rank] uneven heights v2.webp",
  "userdata_maps_[rank] uneven heights v3_[rank] uneven heights v3.webp",
  "userdata_maps_[rank] unity a zh v2_[rank] unity a zh v2.webp",
  "userdata_maps_[rank] vendetta zh v1_[rank] vendetta zh v1.webp",
  "userdata_maps_[rank] volcanoe zh v1_[rank] volcanoe zh v1.webp",
  "userdata_maps_[rank] wasteland warlords balanced zh v1_[rank] wasteland warlords balanced zh v1.webp",
  "userdata_maps_[rank] wasteland warlords revised_[rank] wasteland warlords revised.webp",
  "userdata_maps_[rank] whispering woods zh v1_[rank] whispering woods zh v1.webp",
  "userdata_maps_[rank] white hell zh v1_[rank] white hell zh v1.webp",
  "userdata_maps_[rank] white serpent_[rank] white serpent.webp",
  "userdata_maps_[rank] winter arena_[rank] winter arena.webp",
  "userdata_maps_[rank] winter crows zh v1_[rank] winter crows zh v1.webp",
  "userdata_maps_[rank] winter wolf balanced zh v1_[rank] winter wolf balanced zh v1.webp",
  "userdata_maps_[rank] zh carrier is over v2_[rank] zh carrier is over v2.webp",
  "userdata_maps_air aod - frontline by evanz1987 [final]_air aod - frontline by evanz1987 [final].webp",
  "userdata_maps_allstars_allstars.webp",
  "userdata_maps_antarctic assault_antarctic assault.webp",
  "userdata_maps_aod gc laser general final by i love mixery [pashacnc com]_aod gc laser general final by i love mixery [pashacnc com].webp",
  "userdata_maps_aod pasha challenges you (4p) v_01 [pashacnc com]_aod pasha challenges you (4p) v_01 [pashacnc com].webp",
  "userdata_maps_aod pasha's back to back defense v01 final [pashacnc com]_aod pasha's back to back defense v01 final [pashacnc com].webp",
  "userdata_maps_aod pasha's pentagram v02 [pashacnc com]_aod pasha's pentagram v02 [pashacnc com].webp",
  "userdata_maps_arizona [wbc2020]_arizona [wbc2020].webp",
  "userdata_maps_armored fury zh v2_armored fury zh v2.webp",
  "userdata_maps_autumn sakura [wbc2020]_autumn sakura [wbc2020].webp",
  "userdata_maps_big-game hunting [wbc2020]_big-game hunting [wbc2020].webp",
  "userdata_maps_butterbrot zh v3_butterbrot zh v3.webp",
  "userdata_maps_city under fire v2_city under fire v2.webp",
  "userdata_maps_combat-island_combat-island.webp",
  "userdata_maps_conflict in the mediterranean [wbc2021]_conflict in the mediterranean [wbc2021].webp",
  "userdata_maps_coral islands [wbc2020]_coral islands [wbc2020].webp",
  "userdata_maps_defcon 51 winter_defcon 51 winter.webp",
  "userdata_maps_defcon 51_defcon 51.webp",
  "userdata_maps_dragon canyon_dragon canyon.webp",
  "userdata_maps_fata morgana_fata morgana.webp",
  "userdata_maps_fertile lowlands v2_fertile lowlands v2.webp",
  "userdata_maps_frontier rails [wbc2022]_frontier rails [wbc2022].webp",
  "userdata_maps_gentools secret lab a_gentools secret lab a.webp",
  "userdata_maps_green goon [wbc2022]_green goon [wbc2022].webp",
  "userdata_maps_hummer training control map by time2kill v4_hummer training control map by time2kill v4.webp",
  "userdata_maps_humvee micro by mrgreen [v2]_humvee micro by mrgreen [v2].webp",
  "userdata_maps_immediately action!v2x3_immediately action!v2x3.webp",
  "userdata_maps_industrial arena zh v1_industrial arena zh v1.webp",
  "userdata_maps_instant-shock arena v2 revealed_instant-shock arena v2 revealed.webp",
  "userdata_maps_instant-shock arena v2 show pos_instant-shock arena v2 show pos.webp",
  "userdata_maps_instant-shock arena v2_instant-shock arena v2.webp",
  "userdata_maps_ishock knockout_ishock knockout.webp",
  "userdata_maps_lone eagle [no rush 10 min]_lone eagle [no rush 10 min].webp",
  "userdata_maps_mgv2_mgv2.webp",
  "userdata_maps_middleman-friendly_middleman-friendly.webp",
  "userdata_maps_military encounter_military encounter.webp",
  "userdata_maps_mortal temptation [wbc2020]_mortal temptation [wbc2020].webp",
  "userdata_maps_mortal temptation zh v1_mortal temptation zh v1.webp",
  "userdata_maps_mountainguns2v2_mountainguns2v2.webp",
  "userdata_maps_naval base mabuhay [wbc2022]_naval base mabuhay [wbc2022].webp",
  "userdata_maps_naval port reyes v2 [wbc2020]_naval port reyes v2 [wbc2020].webp",
  "userdata_maps_operation kihill beach - part 1 v2_operation kihill beach - part 1 v2.webp",
  "userdata_maps_purification_purification.webp",
  "userdata_maps_rebel uprise 0-1_rebel uprise 0-1.webp",
  "userdata_maps_subjugation [wbc2020]_subjugation [wbc2020].webp",
  "userdata_maps_superderrick_superderrick.webp",
  "userdata_maps_superderrik_superderrik.webp",
  "userdata_maps_sylt v3_sylt v3.webp",
  "userdata_maps_timber wolf v2_timber wolf v2.webp",
  "userdata_maps_tournament archipelago_tournament archipelago.webp",
  "userdata_maps_tournament c v1_tournament c v1.webp",
  "userdata_maps_tournament graveyard zh v2_tournament graveyard zh v2.webp",
  "userdata_maps_tournament spaceship [wbc2022]_tournament spaceship [wbc2022].webp",
  "userdata_maps_transition zh v2_transition zh v2.webp",
  "userdata_maps_trinity island x_trinity island x.webp",
  "userdata_maps_tt twister_tt twister.webp",
  "userdata_maps_twilight flame edit_twilight flame edit.webp",
  "userdata_maps_twilight flame half v2_twilight flame half v2.webp",
  "userdata_maps_twilight flame half_twilight flame half.webp",
  "userdata_maps_twilight flame revealed_twilight flame revealed.webp",
  "userdata_maps_twilight flame_edit by cnc and sky_twilight flame_edit by cnc and sky.webp",
  "userdata_maps_unity b zh v2_unity b zh v2.webp",
  "userdata_maps_volcano revenge v2_volcano revenge v2.webp",
  "userdata_maps_volcano rush [wbc2020]_volcano rush [wbc2020].webp",
  "userdata_maps_volcano rush v2 [wbc2020]_volcano rush v2 [wbc2020].webp",
  "userdata_maps_volcano rush v3 [wbc2020]_volcano rush v3 [wbc2020].webp",
  "userdata_maps_volcano_volcano.webp",
  "userdata_maps_wings of fury_wings of fury.webp",
  "wall_of_china.webp",
  "wheel of death v5.webp",
  "yota nation arena v3.webp",
]
