export const MAPLIST = [
  "maps_alpine assault_alpine assault.webp",
  "maps_bear town beatdown_bear town beatdown.webp",
  "maps_cairo commandos_cairo commandos.webp",
  "maps_dark mountain_dark mountain.webp",
  "maps_dark night_dark night.webp",
  "maps_destruction station_destruction station.webp",
  "maps_dogsofwar_dogsofwar.webp",
  "maps_eastern everglades_eastern everglades.webp",
  "maps_el scorcho_el scorcho.webp",
  "maps_fallen empire_fallen empire.webp",
  "maps_flash effect_flash effect.webp",
  "maps_floodedplains_floodedplains.webp",
  "maps_golden oasis_golden oasis.webp",
  "maps_green pastures_green pastures.webp",
  "maps_homeland alliance_homeland alliance.webp",
  "maps_hostile dawn_hostile dawn.webp",
  "maps_lights out_lights out.webp",
  "maps_lone eagle_lone eagle.webp",
  "maps_manic aggression_manic aggression.webp",
  "maps_mountainfox_mountainfox.webp",
  "maps_mountain guns_mountain guns.webp",
  "maps_overland_overland.webp",
  "maps_red rock_red rock.webp",
  "maps_rocky rampage_rocky rampage.webp",
  "maps_rogue agent_rogue agent.webp",
  "maps_tournamenta_tournamenta.webp",
  "maps_tournamentb_tournamentb.webp",
  "maps_tournament continent_tournament continent.webp",
  "maps_tournament island_tournament island.webp",
  "maps_tournament lake_tournament lake.webp",
  "maps_tournament tundra_tournament tundra.webp",
  "maps_tournament urban_tournament urban.webp",
  "maps_victory valley_victory valley.webp",
  "maps_whiteout_whiteout.webp",
  "maps_winter wolf_winter wolf.webp",
  "userdata_maps_1v1v1v1v1 small v2_1v1v1v1v1 small v2.webp",
  "userdata_maps_[aod] cobalt rush v2_[aod] cobalt rush v2.webp",
  "userdata_maps_arizona [wbc2020]_arizona [wbc2020].webp",
  "userdata_maps_armored fury zh v2_armored fury zh v2.webp",
  "userdata_maps_autumn sakura [wbc2020]_autumn sakura [wbc2020].webp",
  "userdata_maps_city under fire v2_city under fire v2.webp",
  "userdata_maps_lone eagle [no rush 10 min]_lone eagle [no rush 10 min].webp",
  "userdata_maps_mortal temptation [wbc2020]_mortal temptation [wbc2020].webp",
  "userdata_maps_mortal temptation zh v1_mortal temptation zh v1.webp",
  "userdata_maps_purification_purification.webp",
  "userdata_maps_[rank] a new tragedy zh v1_[rank] a new tragedy zh v1.webp",
  "userdata_maps_[rank] annihilation_[rank] annihilation.webp",
  "userdata_maps_[rank] burning deadline zh v1_[rank] burning deadline zh v1.webp",
  "userdata_maps_[rank] bursting asunder zh v1_[rank] bursting asunder zh v1.webp",
  "userdata_maps_[rank] combat encounter zh v1_[rank] combat encounter zh v1.webp",
  "userdata_maps_[rank] conflict zone zh v2_[rank] conflict zone zh v2.webp",
  "userdata_maps_[rank] coral islands zh v1_[rank] coral islands zh v1.webp",
  "userdata_maps_[rank] danger close zh_[rank] danger close zh.webp",
  "userdata_maps_[rank] defcon balanced zh v1_[rank] defcon balanced zh v1.webp",
  "userdata_maps_[rank] desert combat zh v2_[rank] desert combat zh v2.webp",
  "userdata_maps_[rank] drowning horses zh v1_[rank] drowning horses zh v1.webp",
  "userdata_maps_[rank] fall out zh v1_[rank] fall out zh v1.webp",
  "userdata_maps_[rank] fe nobug zh v1_[rank] fe nobug zh v1.webp",
  "userdata_maps_[rank] fe nowall zh v1_[rank] fe nowall zh v1.webp",
  "userdata_maps_[rank] final departure zh v1_[rank] final departure zh v1.webp",
  "userdata_maps_[rank] hidden pearls zh v1_[rank] hidden pearls zh v1.webp",
  "userdata_maps_[rank] icy frontier zh v1_[rank] icy frontier zh v1.webp",
  "userdata_maps_[rank] lion heart zh v1_[rank] lion heart zh v1.webp",
  "userdata_maps_[rank] lost temple zh v1_[rank] lost temple zh v1.webp",
  "userdata_maps_[rank] maguso zh v3_[rank] maguso zh v3.webp",
  "userdata_maps_[rank] make make 4 zh v2_[rank] make make 4 zh v2.webp",
  "userdata_maps_[rank] mountain path zh v4_[rank] mountain path zh v4.webp",
  "userdata_maps_[rank] naval port reyes zh v1_[rank] naval port reyes zh v1.webp",
  "userdata_maps_[rank] [nmc 2x2] aftermath_[rank] [nmc 2x2] aftermath.webp",
  "userdata_maps_[rank] [nmc 2x2] coastline wold_[rank] [nmc 2x2] coastline wold.webp",
  "userdata_maps_[rank] [nmc 2x2] ghostly rocks_[rank] [nmc 2x2] ghostly rocks.webp",
  "userdata_maps_[rank] [nmc 2x2] maguso_[rank] [nmc 2x2] maguso.webp",
  "userdata_maps_[rank] [nmc 2x2] middle fight_[rank] [nmc 2x2] middle fight.webp",
  "userdata_maps_[rank] [nmc] battle on the river_[rank] [nmc] battle on the river.webp",
  "userdata_maps_[rank] [nmc] blasted lands_[rank] [nmc] blasted lands.webp",
  "userdata_maps_[rank] [nmc] summer arena_[rank] [nmc] summer arena.webp",
  "userdata_maps_[rank] [nmc] tournament arena_[rank] [nmc] tournament arena.webp",
  "userdata_maps_[rank] [nmc] tournament city_[rank] [nmc] tournament city.webp",
  "userdata_maps_[rank] philippine highlands zh v1_[rank] philippine highlands zh v1.webp",
  "userdata_maps_[rank] rubies and pearls zh v1_[rank] rubies and pearls zh v1.webp",
  "userdata_maps_[rank] subjugation zh v1_[rank] subjugation zh v1.webp",
  "userdata_maps_[rank] territorial dispute zh v1_[rank] territorial dispute zh v1.webp",
  "userdata_maps_[rank] tournament a zh v1_[rank] tournament a zh v1.webp",
  "userdata_maps_[rank] unity a zh v2_[rank] unity a zh v2.webp",
  "userdata_maps_[rank] volcanoe zh v1_[rank] volcanoe zh v1.webp",
  "userdata_maps_[rank] whispering woods zh v1_[rank] whispering woods zh v1.webp",
  "userdata_maps_[rank] zh carrier is over v2_[rank] zh carrier is over v2.webp",
  "userdata_maps_twilight flame half_twilight flame half.webp",
  "userdata_maps_volcano rush v2 [wbc2020]_volcano rush v2 [wbc2020].webp",
]
