/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcademyStats
 */
export interface AcademyStats {
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    clearedGarrisonedBuildings: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    controlGroupsUsed: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    doubleClickAttackMoveOrdersGiven: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    firestormsCreated: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    gatherersBuilt: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    generalsPointsSpent: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    guardAbilityUsedCount: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    heroesBuilt: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    minesCleared: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    peonsBuilt: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    salvageCollected: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    secondaryIncomeUnitsBuilt: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    specialPowersUsed: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    structuresCaptured: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    structuresGarrisoned: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    supplyCentersBuilt: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    upgradesPurchased: number;
    /**
     * 
     * @type {number}
     * @memberof AcademyStats
     */
    vehiclesDisguised: number;
}

/**
 * Check if a given object implements the AcademyStats interface.
 */
export function instanceOfAcademyStats(value: object): value is AcademyStats {
    if (!('clearedGarrisonedBuildings' in value) || value['clearedGarrisonedBuildings'] === undefined) return false;
    if (!('controlGroupsUsed' in value) || value['controlGroupsUsed'] === undefined) return false;
    if (!('doubleClickAttackMoveOrdersGiven' in value) || value['doubleClickAttackMoveOrdersGiven'] === undefined) return false;
    if (!('firestormsCreated' in value) || value['firestormsCreated'] === undefined) return false;
    if (!('gatherersBuilt' in value) || value['gatherersBuilt'] === undefined) return false;
    if (!('generalsPointsSpent' in value) || value['generalsPointsSpent'] === undefined) return false;
    if (!('guardAbilityUsedCount' in value) || value['guardAbilityUsedCount'] === undefined) return false;
    if (!('heroesBuilt' in value) || value['heroesBuilt'] === undefined) return false;
    if (!('minesCleared' in value) || value['minesCleared'] === undefined) return false;
    if (!('peonsBuilt' in value) || value['peonsBuilt'] === undefined) return false;
    if (!('salvageCollected' in value) || value['salvageCollected'] === undefined) return false;
    if (!('secondaryIncomeUnitsBuilt' in value) || value['secondaryIncomeUnitsBuilt'] === undefined) return false;
    if (!('specialPowersUsed' in value) || value['specialPowersUsed'] === undefined) return false;
    if (!('structuresCaptured' in value) || value['structuresCaptured'] === undefined) return false;
    if (!('structuresGarrisoned' in value) || value['structuresGarrisoned'] === undefined) return false;
    if (!('supplyCentersBuilt' in value) || value['supplyCentersBuilt'] === undefined) return false;
    if (!('upgradesPurchased' in value) || value['upgradesPurchased'] === undefined) return false;
    if (!('vehiclesDisguised' in value) || value['vehiclesDisguised'] === undefined) return false;
    return true;
}

export function AcademyStatsFromJSON(json: any): AcademyStats {
    return AcademyStatsFromJSONTyped(json, false);
}

export function AcademyStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcademyStats {
    if (json == null) {
        return json;
    }
    return {
        
        'clearedGarrisonedBuildings': json['clearedGarrisonedBuildings'],
        'controlGroupsUsed': json['controlGroupsUsed'],
        'doubleClickAttackMoveOrdersGiven': json['doubleClickAttackMoveOrdersGiven'],
        'firestormsCreated': json['firestormsCreated'],
        'gatherersBuilt': json['gatherersBuilt'],
        'generalsPointsSpent': json['generalsPointsSpent'],
        'guardAbilityUsedCount': json['guardAbilityUsedCount'],
        'heroesBuilt': json['heroesBuilt'],
        'minesCleared': json['minesCleared'],
        'peonsBuilt': json['peonsBuilt'],
        'salvageCollected': json['salvageCollected'],
        'secondaryIncomeUnitsBuilt': json['secondaryIncomeUnitsBuilt'],
        'specialPowersUsed': json['specialPowersUsed'],
        'structuresCaptured': json['structuresCaptured'],
        'structuresGarrisoned': json['structuresGarrisoned'],
        'supplyCentersBuilt': json['supplyCentersBuilt'],
        'upgradesPurchased': json['upgradesPurchased'],
        'vehiclesDisguised': json['vehiclesDisguised'],
    };
}

export function AcademyStatsToJSON(json: any): AcademyStats {
    return AcademyStatsToJSONTyped(json, false);
}

export function AcademyStatsToJSONTyped(value?: AcademyStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'clearedGarrisonedBuildings': value['clearedGarrisonedBuildings'],
        'controlGroupsUsed': value['controlGroupsUsed'],
        'doubleClickAttackMoveOrdersGiven': value['doubleClickAttackMoveOrdersGiven'],
        'firestormsCreated': value['firestormsCreated'],
        'gatherersBuilt': value['gatherersBuilt'],
        'generalsPointsSpent': value['generalsPointsSpent'],
        'guardAbilityUsedCount': value['guardAbilityUsedCount'],
        'heroesBuilt': value['heroesBuilt'],
        'minesCleared': value['minesCleared'],
        'peonsBuilt': value['peonsBuilt'],
        'salvageCollected': value['salvageCollected'],
        'secondaryIncomeUnitsBuilt': value['secondaryIncomeUnitsBuilt'],
        'specialPowersUsed': value['specialPowersUsed'],
        'structuresCaptured': value['structuresCaptured'],
        'structuresGarrisoned': value['structuresGarrisoned'],
        'supplyCentersBuilt': value['supplyCentersBuilt'],
        'upgradesPurchased': value['upgradesPurchased'],
        'vehiclesDisguised': value['vehiclesDisguised'],
    };
}

