/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BackfillMapCrcsResponse
 */
export interface BackfillMapCrcsResponse {
    /**
     * 
     * @type {number}
     * @memberof BackfillMapCrcsResponse
     */
    processed: number;
    /**
     * 
     * @type {number}
     * @memberof BackfillMapCrcsResponse
     */
    resolved: number;
    /**
     * 
     * @type {Array<Array<any>>}
     * @memberof BackfillMapCrcsResponse
     */
    results?: Array<Array<any>>;
}

/**
 * Check if a given object implements the BackfillMapCrcsResponse interface.
 */
export function instanceOfBackfillMapCrcsResponse(value: object): value is BackfillMapCrcsResponse {
    if (!('processed' in value) || value['processed'] === undefined) return false;
    if (!('resolved' in value) || value['resolved'] === undefined) return false;
    return true;
}

export function BackfillMapCrcsResponseFromJSON(json: any): BackfillMapCrcsResponse {
    return BackfillMapCrcsResponseFromJSONTyped(json, false);
}

export function BackfillMapCrcsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BackfillMapCrcsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'processed': json['processed'],
        'resolved': json['resolved'],
        'results': json['results'] == null ? undefined : json['results'],
    };
}

export function BackfillMapCrcsResponseToJSON(json: any): BackfillMapCrcsResponse {
    return BackfillMapCrcsResponseToJSONTyped(json, false);
}

export function BackfillMapCrcsResponseToJSONTyped(value?: BackfillMapCrcsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'processed': value['processed'],
        'resolved': value['resolved'],
        'results': value['results'],
    };
}

