/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BracketPredictionLeaderboardEntry
 */
export interface BracketPredictionLeaderboardEntry {
    /**
     * 
     * @type {string}
     * @memberof BracketPredictionLeaderboardEntry
     */
    userName: string;
    /**
     * 
     * @type {number}
     * @memberof BracketPredictionLeaderboardEntry
     */
    correct: number;
    /**
     * 
     * @type {number}
     * @memberof BracketPredictionLeaderboardEntry
     */
    total: number;
}

/**
 * Check if a given object implements the BracketPredictionLeaderboardEntry interface.
 */
export function instanceOfBracketPredictionLeaderboardEntry(value: object): value is BracketPredictionLeaderboardEntry {
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('correct' in value) || value['correct'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function BracketPredictionLeaderboardEntryFromJSON(json: any): BracketPredictionLeaderboardEntry {
    return BracketPredictionLeaderboardEntryFromJSONTyped(json, false);
}

export function BracketPredictionLeaderboardEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BracketPredictionLeaderboardEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['user_name'],
        'correct': json['correct'],
        'total': json['total'],
    };
}

export function BracketPredictionLeaderboardEntryToJSON(json: any): BracketPredictionLeaderboardEntry {
    return BracketPredictionLeaderboardEntryToJSONTyped(json, false);
}

export function BracketPredictionLeaderboardEntryToJSONTyped(value?: BracketPredictionLeaderboardEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_name': value['userName'],
        'correct': value['correct'],
        'total': value['total'],
    };
}

