/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BracketMatchPrediction
 */
export interface BracketMatchPrediction {
    /**
     * 
     * @type {string}
     * @memberof BracketMatchPrediction
     */
    matchId: string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof BracketMatchPrediction
     */
    tally?: { [key: string]: number; };
    /**
     * 
     * @type {string}
     * @memberof BracketMatchPrediction
     */
    myPick?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof BracketMatchPrediction
     */
    open?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof BracketMatchPrediction
     */
    correctPicks?: Array<string> | null;
}

/**
 * Check if a given object implements the BracketMatchPrediction interface.
 */
export function instanceOfBracketMatchPrediction(value: object): value is BracketMatchPrediction {
    if (!('matchId' in value) || value['matchId'] === undefined) return false;
    return true;
}

export function BracketMatchPredictionFromJSON(json: any): BracketMatchPrediction {
    return BracketMatchPredictionFromJSONTyped(json, false);
}

export function BracketMatchPredictionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BracketMatchPrediction {
    if (json == null) {
        return json;
    }
    return {
        
        'matchId': json['match_id'],
        'tally': json['tally'] == null ? undefined : json['tally'],
        'myPick': json['my_pick'] == null ? undefined : json['my_pick'],
        'open': json['open'] == null ? undefined : json['open'],
        'correctPicks': json['correct_picks'] == null ? undefined : json['correct_picks'],
    };
}

export function BracketMatchPredictionToJSON(json: any): BracketMatchPrediction {
    return BracketMatchPredictionToJSONTyped(json, false);
}

export function BracketMatchPredictionToJSONTyped(value?: BracketMatchPrediction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'match_id': value['matchId'],
        'tally': value['tally'],
        'my_pick': value['myPick'],
        'open': value['open'],
        'correct_picks': value['correctPicks'],
    };
}

