/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BracketPlayerEntry
 */
export interface BracketPlayerEntry {
    /**
     * 
     * @type {number}
     * @memberof BracketPlayerEntry
     */
    seed: number;
    /**
     * 
     * @type {string}
     * @memberof BracketPlayerEntry
     */
    playerName: string;
}

/**
 * Check if a given object implements the BracketPlayerEntry interface.
 */
export function instanceOfBracketPlayerEntry(value: object): value is BracketPlayerEntry {
    if (!('seed' in value) || value['seed'] === undefined) return false;
    if (!('playerName' in value) || value['playerName'] === undefined) return false;
    return true;
}

export function BracketPlayerEntryFromJSON(json: any): BracketPlayerEntry {
    return BracketPlayerEntryFromJSONTyped(json, false);
}

export function BracketPlayerEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): BracketPlayerEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'seed': json['seed'],
        'playerName': json['player_name'],
    };
}

export function BracketPlayerEntryToJSON(json: any): BracketPlayerEntry {
    return BracketPlayerEntryToJSONTyped(json, false);
}

export function BracketPlayerEntryToJSONTyped(value?: BracketPlayerEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seed': value['seed'],
        'player_name': value['playerName'],
    };
}

