/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchInfo } from './MatchInfo';
import {
    MatchInfoFromJSON,
    MatchInfoFromJSONTyped,
    MatchInfoToJSON,
    MatchInfoToJSONTyped,
} from './MatchInfo';

/**
 * The games played for one bracket match, plus what else it could be.
 * 
 * ``linked`` is what's persisted. ``candidates`` is what the detector would
 * propose but nobody has confirmed - shown to tournament admins so they can
 * link a game the automatic rule missed (a mismatched alias, a game played
 * on a different night than scheduled).
 * @export
 * @interface BracketMatchGames
 */
export interface BracketMatchGames {
    /**
     * 
     * @type {string}
     * @memberof BracketMatchGames
     */
    matchId: string;
    /**
     * 
     * @type {Array<MatchInfo>}
     * @memberof BracketMatchGames
     */
    linked?: Array<MatchInfo>;
    /**
     * 
     * @type {Array<MatchInfo>}
     * @memberof BracketMatchGames
     */
    candidates?: Array<MatchInfo>;
}

/**
 * Check if a given object implements the BracketMatchGames interface.
 */
export function instanceOfBracketMatchGames(value: object): value is BracketMatchGames {
    if (!('matchId' in value) || value['matchId'] === undefined) return false;
    return true;
}

export function BracketMatchGamesFromJSON(json: any): BracketMatchGames {
    return BracketMatchGamesFromJSONTyped(json, false);
}

export function BracketMatchGamesFromJSONTyped(json: any, ignoreDiscriminator: boolean): BracketMatchGames {
    if (json == null) {
        return json;
    }
    return {
        
        'matchId': json['matchId'],
        'linked': json['linked'] == null ? undefined : ((json['linked'] as Array<any>).map(MatchInfoFromJSON)),
        'candidates': json['candidates'] == null ? undefined : ((json['candidates'] as Array<any>).map(MatchInfoFromJSON)),
    };
}

export function BracketMatchGamesToJSON(json: any): BracketMatchGames {
    return BracketMatchGamesToJSONTyped(json, false);
}

export function BracketMatchGamesToJSONTyped(value?: BracketMatchGames | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'matchId': value['matchId'],
        'linked': value['linked'] == null ? undefined : ((value['linked'] as Array<any>).map(MatchInfoToJSON)),
        'candidates': value['candidates'] == null ? undefined : ((value['candidates'] as Array<any>).map(MatchInfoToJSON)),
    };
}

