/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BracketMatchOutput
 */
export interface BracketMatchOutput {
    /**
     * 
     * @type {string}
     * @memberof BracketMatchOutput
     */
    matchId: string;
    /**
     * 
     * @type {BracketMatchOutputBracketEnum}
     * @memberof BracketMatchOutput
     */
    bracket: BracketMatchOutputBracketEnum;
    /**
     * 
     * @type {number}
     * @memberof BracketMatchOutput
     */
    roundNumber: number;
    /**
     * 
     * @type {string}
     * @memberof BracketMatchOutput
     */
    roundName: string;
    /**
     * 
     * @type {string}
     * @memberof BracketMatchOutput
     */
    playerA?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BracketMatchOutput
     */
    playerB?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof BracketMatchOutput
     */
    scheduledDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof BracketMatchOutput
     */
    bestOf?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BracketMatchOutput
     */
    scoreA?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BracketMatchOutput
     */
    scoreB?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BracketMatchOutput
     */
    winner?: string | null;
    /**
     * 
     * @type {BracketMatchOutputStatusEnum}
     * @memberof BracketMatchOutput
     */
    status: BracketMatchOutputStatusEnum;
}


/**
 * @export
 */
export const BracketMatchOutputBracketEnum = {
    W: 'W',
    L: 'L',
    Gf: 'GF'
} as const;
export type BracketMatchOutputBracketEnum = typeof BracketMatchOutputBracketEnum[keyof typeof BracketMatchOutputBracketEnum];

/**
 * @export
 */
export const BracketMatchOutputStatusEnum = {
    Pending: 'pending',
    Ready: 'ready',
    Completed: 'completed',
    NotApplicable: 'not_applicable'
} as const;
export type BracketMatchOutputStatusEnum = typeof BracketMatchOutputStatusEnum[keyof typeof BracketMatchOutputStatusEnum];


/**
 * Check if a given object implements the BracketMatchOutput interface.
 */
export function instanceOfBracketMatchOutput(value: object): value is BracketMatchOutput {
    if (!('matchId' in value) || value['matchId'] === undefined) return false;
    if (!('bracket' in value) || value['bracket'] === undefined) return false;
    if (!('roundNumber' in value) || value['roundNumber'] === undefined) return false;
    if (!('roundName' in value) || value['roundName'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BracketMatchOutputFromJSON(json: any): BracketMatchOutput {
    return BracketMatchOutputFromJSONTyped(json, false);
}

export function BracketMatchOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BracketMatchOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'matchId': json['match_id'],
        'bracket': json['bracket'],
        'roundNumber': json['round_number'],
        'roundName': json['round_name'],
        'playerA': json['player_a'] == null ? undefined : json['player_a'],
        'playerB': json['player_b'] == null ? undefined : json['player_b'],
        'scheduledDate': json['scheduled_date'] == null ? undefined : (new Date(json['scheduled_date'])),
        'bestOf': json['best_of'] == null ? undefined : json['best_of'],
        'scoreA': json['score_a'] == null ? undefined : json['score_a'],
        'scoreB': json['score_b'] == null ? undefined : json['score_b'],
        'winner': json['winner'] == null ? undefined : json['winner'],
        'status': json['status'],
    };
}

export function BracketMatchOutputToJSON(json: any): BracketMatchOutput {
    return BracketMatchOutputToJSONTyped(json, false);
}

export function BracketMatchOutputToJSONTyped(value?: BracketMatchOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'match_id': value['matchId'],
        'bracket': value['bracket'],
        'round_number': value['roundNumber'],
        'round_name': value['roundName'],
        'player_a': value['playerA'],
        'player_b': value['playerB'],
        'scheduled_date': value['scheduledDate'] == null ? value['scheduledDate'] : value['scheduledDate'].toISOString().substring(0,10),
        'best_of': value['bestOf'],
        'score_a': value['scoreA'],
        'score_b': value['scoreB'],
        'winner': value['winner'],
        'status': value['status'],
    };
}

