/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChooseMapCandidate } from './ChooseMapCandidate';
import {
    ChooseMapCandidateFromJSON,
    ChooseMapCandidateFromJSONTyped,
    ChooseMapCandidateToJSON,
    ChooseMapCandidateToJSONTyped,
} from './ChooseMapCandidate';

/**
 * 
 * @export
 * @interface ChooseMapResult
 */
export interface ChooseMapResult {
    /**
     * 
     * @type {number}
     * @memberof ChooseMapResult
     */
    playerCount: number;
    /**
     * 
     * @type {string}
     * @memberof ChooseMapResult
     */
    chosenMap?: string | null;
    /**
     * 
     * @type {Array<ChooseMapCandidate>}
     * @memberof ChooseMapResult
     */
    candidates?: Array<ChooseMapCandidate>;
}

/**
 * Check if a given object implements the ChooseMapResult interface.
 */
export function instanceOfChooseMapResult(value: object): value is ChooseMapResult {
    if (!('playerCount' in value) || value['playerCount'] === undefined) return false;
    return true;
}

export function ChooseMapResultFromJSON(json: any): ChooseMapResult {
    return ChooseMapResultFromJSONTyped(json, false);
}

export function ChooseMapResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChooseMapResult {
    if (json == null) {
        return json;
    }
    return {
        
        'playerCount': json['player_count'],
        'chosenMap': json['chosen_map'] == null ? undefined : json['chosen_map'],
        'candidates': json['candidates'] == null ? undefined : ((json['candidates'] as Array<any>).map(ChooseMapCandidateFromJSON)),
    };
}

export function ChooseMapResultToJSON(json: any): ChooseMapResult {
    return ChooseMapResultToJSONTyped(json, false);
}

export function ChooseMapResultToJSONTyped(value?: ChooseMapResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player_count': value['playerCount'],
        'chosen_map': value['chosenMap'],
        'candidates': value['candidates'] == null ? undefined : ((value['candidates'] as Array<any>).map(ChooseMapCandidateToJSON)),
    };
}

