/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChooseMapRequest
 */
export interface ChooseMapRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof ChooseMapRequest
     */
    players?: Array<string>;
}

/**
 * Check if a given object implements the ChooseMapRequest interface.
 */
export function instanceOfChooseMapRequest(value: object): value is ChooseMapRequest {
    return true;
}

export function ChooseMapRequestFromJSON(json: any): ChooseMapRequest {
    return ChooseMapRequestFromJSONTyped(json, false);
}

export function ChooseMapRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChooseMapRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'players': json['players'] == null ? undefined : json['players'],
    };
}

export function ChooseMapRequestToJSON(json: any): ChooseMapRequest {
    return ChooseMapRequestToJSONTyped(json, false);
}

export function ChooseMapRequestToJSONTyped(value?: ChooseMapRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'players': value['players'],
    };
}

