/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BracketPlayerEntry } from './BracketPlayerEntry';
import {
    BracketPlayerEntryFromJSON,
    BracketPlayerEntryFromJSONTyped,
    BracketPlayerEntryToJSON,
    BracketPlayerEntryToJSONTyped,
} from './BracketPlayerEntry';

/**
 * 
 * @export
 * @interface CreateBracketRequest
 */
export interface CreateBracketRequest {
    /**
     * 
     * @type {Array<BracketPlayerEntry>}
     * @memberof CreateBracketRequest
     */
    players: Array<BracketPlayerEntry>;
}

/**
 * Check if a given object implements the CreateBracketRequest interface.
 */
export function instanceOfCreateBracketRequest(value: object): value is CreateBracketRequest {
    if (!('players' in value) || value['players'] === undefined) return false;
    return true;
}

export function CreateBracketRequestFromJSON(json: any): CreateBracketRequest {
    return CreateBracketRequestFromJSONTyped(json, false);
}

export function CreateBracketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBracketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'players': ((json['players'] as Array<any>).map(BracketPlayerEntryFromJSON)),
    };
}

export function CreateBracketRequestToJSON(json: any): CreateBracketRequest {
    return CreateBracketRequestToJSONTyped(json, false);
}

export function CreateBracketRequestToJSONTyped(value?: CreateBracketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'players': ((value['players'] as Array<any>).map(BracketPlayerEntryToJSON)),
    };
}

