/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentUser
 */
export interface CurrentUser {
    /**
     * 
     * @type {string}
     * @memberof CurrentUser
     */
    discordId: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUser
     */
    discordUsername: string;
    /**
     * 
     * @type {string}
     * @memberof CurrentUser
     */
    discordAvatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CurrentUser
     */
    playerName?: string | null;
    /**
     * True until the user has claimed an in-game name from PLAYER_NAMES.
     * @type {boolean}
     * @memberof CurrentUser
     */
    readonly needsPlayerSelection: boolean;
    /**
     * True if the claimed in-game name is in player_ids.ADMIN_PLAYERS.
     * @type {boolean}
     * @memberof CurrentUser
     */
    readonly isAdmin: boolean;
    /**
     * True if the claimed in-game name is in player_ids.TOURNAMENT_ADMINS.
     * @type {boolean}
     * @memberof CurrentUser
     */
    readonly isTournamentAdmin: boolean;
    /**
     * True if the claimed in-game name is in player_ids.OPS_ADMINS.
     * 
     * Gates the admin control panel - narrower than `is_admin`, which only
     * unlocks the debug views.
     * @type {boolean}
     * @memberof CurrentUser
     */
    readonly isOpsAdmin: boolean;
}

/**
 * Check if a given object implements the CurrentUser interface.
 */
export function instanceOfCurrentUser(value: object): value is CurrentUser {
    if (!('discordId' in value) || value['discordId'] === undefined) return false;
    if (!('discordUsername' in value) || value['discordUsername'] === undefined) return false;
    if (!('needsPlayerSelection' in value) || value['needsPlayerSelection'] === undefined) return false;
    if (!('isAdmin' in value) || value['isAdmin'] === undefined) return false;
    if (!('isTournamentAdmin' in value) || value['isTournamentAdmin'] === undefined) return false;
    if (!('isOpsAdmin' in value) || value['isOpsAdmin'] === undefined) return false;
    return true;
}

export function CurrentUserFromJSON(json: any): CurrentUser {
    return CurrentUserFromJSONTyped(json, false);
}

export function CurrentUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentUser {
    if (json == null) {
        return json;
    }
    return {
        
        'discordId': json['discord_id'],
        'discordUsername': json['discord_username'],
        'discordAvatar': json['discord_avatar'] == null ? undefined : json['discord_avatar'],
        'playerName': json['player_name'] == null ? undefined : json['player_name'],
        'needsPlayerSelection': json['needs_player_selection'],
        'isAdmin': json['is_admin'],
        'isTournamentAdmin': json['is_tournament_admin'],
        'isOpsAdmin': json['is_ops_admin'],
    };
}

export function CurrentUserToJSON(json: any): CurrentUser {
    return CurrentUserToJSONTyped(json, false);
}

export function CurrentUserToJSONTyped(value?: Omit<CurrentUser, 'needs_player_selection'|'is_admin'|'is_tournament_admin'|'is_ops_admin'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'discord_id': value['discordId'],
        'discord_username': value['discordUsername'],
        'discord_avatar': value['discordAvatar'],
        'player_name': value['playerName'],
    };
}

