/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One histogram bar: games whose duration is in [start, end) minutes.
 * 
 * The final bucket is the overflow bin and is half-open the other way -
 * ``end_minutes`` is null and it holds everything at or beyond ``start``, so
 * one four-hour marathon widens the tail label instead of the whole axis.
 * @export
 * @interface DurationBucket
 */
export interface DurationBucket {
    /**
     * 
     * @type {number}
     * @memberof DurationBucket
     */
    startMinutes: number;
    /**
     * 
     * @type {number}
     * @memberof DurationBucket
     */
    endMinutes?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DurationBucket
     */
    count: number;
}

/**
 * Check if a given object implements the DurationBucket interface.
 */
export function instanceOfDurationBucket(value: object): value is DurationBucket {
    if (!('startMinutes' in value) || value['startMinutes'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function DurationBucketFromJSON(json: any): DurationBucket {
    return DurationBucketFromJSONTyped(json, false);
}

export function DurationBucketFromJSONTyped(json: any, ignoreDiscriminator: boolean): DurationBucket {
    if (json == null) {
        return json;
    }
    return {
        
        'startMinutes': json['startMinutes'],
        'endMinutes': json['endMinutes'] == null ? undefined : json['endMinutes'],
        'count': json['count'],
    };
}

export function DurationBucketToJSON(json: any): DurationBucket {
    return DurationBucketToJSONTyped(json, false);
}

export function DurationBucketToJSONTyped(value?: DurationBucket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startMinutes': value['startMinutes'],
        'endMinutes': value['endMinutes'],
        'count': value['count'],
    };
}

