/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Faction = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_MINUS_1: -1
} as const;
export type Faction = typeof Faction[keyof typeof Faction];


export function instanceOfFaction(value: any): boolean {
    for (const key in Faction) {
        if (Object.prototype.hasOwnProperty.call(Faction, key)) {
            if (Faction[key as keyof typeof Faction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FactionFromJSON(json: any): Faction {
    return FactionFromJSONTyped(json, false);
}

export function FactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Faction {
    return json as Faction;
}

export function FactionToJSON(value?: Faction | null): any {
    return value as any;
}

export function FactionToJSONTyped(value: any, ignoreDiscriminator: boolean): Faction {
    return value as Faction;
}

