/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FetchMissingMapResult
 */
export interface FetchMissingMapResult {
    /**
     * 
     * @type {string}
     * @memberof FetchMissingMapResult
     */
    mapName: string;
    /**
     * 
     * @type {string}
     * @memberof FetchMissingMapResult
     */
    baseName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FetchMissingMapResult
     */
    tgaS3Uri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FetchMissingMapResult
     */
    webpS3Uri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FetchMissingMapResult
     */
    mapS3Uri?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FetchMissingMapResult
     */
    error?: string | null;
}

/**
 * Check if a given object implements the FetchMissingMapResult interface.
 */
export function instanceOfFetchMissingMapResult(value: object): value is FetchMissingMapResult {
    if (!('mapName' in value) || value['mapName'] === undefined) return false;
    return true;
}

export function FetchMissingMapResultFromJSON(json: any): FetchMissingMapResult {
    return FetchMissingMapResultFromJSONTyped(json, false);
}

export function FetchMissingMapResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchMissingMapResult {
    if (json == null) {
        return json;
    }
    return {
        
        'mapName': json['map_name'],
        'baseName': json['base_name'] == null ? undefined : json['base_name'],
        'tgaS3Uri': json['tga_s3_uri'] == null ? undefined : json['tga_s3_uri'],
        'webpS3Uri': json['webp_s3_uri'] == null ? undefined : json['webp_s3_uri'],
        'mapS3Uri': json['map_s3_uri'] == null ? undefined : json['map_s3_uri'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function FetchMissingMapResultToJSON(json: any): FetchMissingMapResult {
    return FetchMissingMapResultToJSONTyped(json, false);
}

export function FetchMissingMapResultToJSONTyped(value?: FetchMissingMapResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'map_name': value['mapName'],
        'base_name': value['baseName'],
        'tga_s3_uri': value['tgaS3Uri'],
        'webp_s3_uri': value['webpS3Uri'],
        'map_s3_uri': value['mapS3Uri'],
        'error': value['error'],
    };
}

