/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Per-player record across free-for-all games.
 * @export
 * @interface FFAPlayerStat
 */
export interface FFAPlayerStat {
    /**
     * 
     * @type {string}
     * @memberof FFAPlayerStat
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof FFAPlayerStat
     */
    games: number;
    /**
     * 
     * @type {number}
     * @memberof FFAPlayerStat
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof FFAPlayerStat
     */
    winRate: number;
    /**
     * 
     * @type {number}
     * @memberof FFAPlayerStat
     */
    expectedWins: number;
    /**
     * 
     * @type {number}
     * @memberof FFAPlayerStat
     */
    dominance: number;
    /**
     * 
     * @type {boolean}
     * @memberof FFAPlayerStat
     */
    isCpu?: boolean;
}

/**
 * Check if a given object implements the FFAPlayerStat interface.
 */
export function instanceOfFFAPlayerStat(value: object): value is FFAPlayerStat {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('games' in value) || value['games'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('winRate' in value) || value['winRate'] === undefined) return false;
    if (!('expectedWins' in value) || value['expectedWins'] === undefined) return false;
    if (!('dominance' in value) || value['dominance'] === undefined) return false;
    return true;
}

export function FFAPlayerStatFromJSON(json: any): FFAPlayerStat {
    return FFAPlayerStatFromJSONTyped(json, false);
}

export function FFAPlayerStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): FFAPlayerStat {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'games': json['games'],
        'wins': json['wins'],
        'winRate': json['winRate'],
        'expectedWins': json['expectedWins'],
        'dominance': json['dominance'],
        'isCpu': json['isCpu'] == null ? undefined : json['isCpu'],
    };
}

export function FFAPlayerStatToJSON(json: any): FFAPlayerStat {
    return FFAPlayerStatToJSONTyped(json, false);
}

export function FFAPlayerStatToJSONTyped(value?: FFAPlayerStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'games': value['games'],
        'wins': value['wins'],
        'winRate': value['winRate'],
        'expectedWins': value['expectedWins'],
        'dominance': value['dominance'],
        'isCpu': value['isCpu'],
    };
}

