/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Pointer to the most recently played FFA game.
 * @export
 * @interface FFARecentMatch
 */
export interface FFARecentMatch {
    /**
     * 
     * @type {number}
     * @memberof FFARecentMatch
     */
    matchId: number;
    /**
     * 
     * @type {string}
     * @memberof FFARecentMatch
     */
    winner: string;
}

/**
 * Check if a given object implements the FFARecentMatch interface.
 */
export function instanceOfFFARecentMatch(value: object): value is FFARecentMatch {
    if (!('matchId' in value) || value['matchId'] === undefined) return false;
    if (!('winner' in value) || value['winner'] === undefined) return false;
    return true;
}

export function FFARecentMatchFromJSON(json: any): FFARecentMatch {
    return FFARecentMatchFromJSONTyped(json, false);
}

export function FFARecentMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): FFARecentMatch {
    if (json == null) {
        return json;
    }
    return {
        
        'matchId': json['matchId'],
        'winner': json['winner'],
    };
}

export function FFARecentMatchToJSON(json: any): FFARecentMatch {
    return FFARecentMatchToJSONTyped(json, false);
}

export function FFARecentMatchToJSONTyped(value?: FFARecentMatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'matchId': value['matchId'],
        'winner': value['winner'],
    };
}

