/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FFAMapStat } from './FFAMapStat';
import {
    FFAMapStatFromJSON,
    FFAMapStatFromJSONTyped,
    FFAMapStatToJSON,
    FFAMapStatToJSONTyped,
} from './FFAMapStat';
import type { FFAPlayerStat } from './FFAPlayerStat';
import {
    FFAPlayerStatFromJSON,
    FFAPlayerStatFromJSONTyped,
    FFAPlayerStatToJSON,
    FFAPlayerStatToJSONTyped,
} from './FFAPlayerStat';
import type { FFAGeneralStat } from './FFAGeneralStat';
import {
    FFAGeneralStatFromJSON,
    FFAGeneralStatFromJSONTyped,
    FFAGeneralStatToJSON,
    FFAGeneralStatToJSONTyped,
} from './FFAGeneralStat';
import type { FFARecentMatch } from './FFARecentMatch';
import {
    FFARecentMatchFromJSON,
    FFARecentMatchFromJSONTyped,
    FFARecentMatchToJSON,
    FFARecentMatchToJSONTyped,
} from './FFARecentMatch';

/**
 * Everything the FFA page renders, computed over human free-for-all games.
 * @export
 * @interface FFAStats
 */
export interface FFAStats {
    /**
     * 
     * @type {number}
     * @memberof FFAStats
     */
    totalGames: number;
    /**
     * 
     * @type {number}
     * @memberof FFAStats
     */
    distinctPlayers: number;
    /**
     * 
     * @type {number}
     * @memberof FFAStats
     */
    avgPlayersPerGame: number;
    /**
     * 
     * @type {FFARecentMatch}
     * @memberof FFAStats
     */
    mostRecent?: FFARecentMatch | null;
    /**
     * 
     * @type {Array<FFAPlayerStat>}
     * @memberof FFAStats
     */
    playerStats: Array<FFAPlayerStat>;
    /**
     * 
     * @type {Array<FFAGeneralStat>}
     * @memberof FFAStats
     */
    generalStats: Array<FFAGeneralStat>;
    /**
     * 
     * @type {Array<FFAMapStat>}
     * @memberof FFAStats
     */
    mapStats: Array<FFAMapStat>;
}

/**
 * Check if a given object implements the FFAStats interface.
 */
export function instanceOfFFAStats(value: object): value is FFAStats {
    if (!('totalGames' in value) || value['totalGames'] === undefined) return false;
    if (!('distinctPlayers' in value) || value['distinctPlayers'] === undefined) return false;
    if (!('avgPlayersPerGame' in value) || value['avgPlayersPerGame'] === undefined) return false;
    if (!('playerStats' in value) || value['playerStats'] === undefined) return false;
    if (!('generalStats' in value) || value['generalStats'] === undefined) return false;
    if (!('mapStats' in value) || value['mapStats'] === undefined) return false;
    return true;
}

export function FFAStatsFromJSON(json: any): FFAStats {
    return FFAStatsFromJSONTyped(json, false);
}

export function FFAStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FFAStats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalGames': json['totalGames'],
        'distinctPlayers': json['distinctPlayers'],
        'avgPlayersPerGame': json['avgPlayersPerGame'],
        'mostRecent': json['mostRecent'] == null ? undefined : FFARecentMatchFromJSON(json['mostRecent']),
        'playerStats': ((json['playerStats'] as Array<any>).map(FFAPlayerStatFromJSON)),
        'generalStats': ((json['generalStats'] as Array<any>).map(FFAGeneralStatFromJSON)),
        'mapStats': ((json['mapStats'] as Array<any>).map(FFAMapStatFromJSON)),
    };
}

export function FFAStatsToJSON(json: any): FFAStats {
    return FFAStatsToJSONTyped(json, false);
}

export function FFAStatsToJSONTyped(value?: FFAStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalGames': value['totalGames'],
        'distinctPlayers': value['distinctPlayers'],
        'avgPlayersPerGame': value['avgPlayersPerGame'],
        'mostRecent': FFARecentMatchToJSON(value['mostRecent']),
        'playerStats': ((value['playerStats'] as Array<any>).map(FFAPlayerStatToJSON)),
        'generalStats': ((value['generalStats'] as Array<any>).map(FFAGeneralStatToJSON)),
        'mapStats': ((value['mapStats'] as Array<any>).map(FFAMapStatToJSON)),
    };
}

