/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameNightBackfillNight } from './GameNightBackfillNight';
import {
    GameNightBackfillNightFromJSON,
    GameNightBackfillNightFromJSONTyped,
    GameNightBackfillNightToJSON,
    GameNightBackfillNightToJSONTyped,
} from './GameNightBackfillNight';

/**
 * The result of one backfill run over the last N game nights.
 * @export
 * @interface GameNightBackfill
 */
export interface GameNightBackfill {
    /**
     * 
     * @type {number}
     * @memberof GameNightBackfill
     */
    days: number;
    /**
     * 
     * @type {number}
     * @memberof GameNightBackfill
     */
    generated: number;
    /**
     * 
     * @type {number}
     * @memberof GameNightBackfill
     */
    remaining: number;
    /**
     * 
     * @type {Array<GameNightBackfillNight>}
     * @memberof GameNightBackfill
     */
    nights?: Array<GameNightBackfillNight>;
}

/**
 * Check if a given object implements the GameNightBackfill interface.
 */
export function instanceOfGameNightBackfill(value: object): value is GameNightBackfill {
    if (!('days' in value) || value['days'] === undefined) return false;
    if (!('generated' in value) || value['generated'] === undefined) return false;
    if (!('remaining' in value) || value['remaining'] === undefined) return false;
    return true;
}

export function GameNightBackfillFromJSON(json: any): GameNightBackfill {
    return GameNightBackfillFromJSONTyped(json, false);
}

export function GameNightBackfillFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameNightBackfill {
    if (json == null) {
        return json;
    }
    return {
        
        'days': json['days'],
        'generated': json['generated'],
        'remaining': json['remaining'],
        'nights': json['nights'] == null ? undefined : ((json['nights'] as Array<any>).map(GameNightBackfillNightFromJSON)),
    };
}

export function GameNightBackfillToJSON(json: any): GameNightBackfill {
    return GameNightBackfillToJSONTyped(json, false);
}

export function GameNightBackfillToJSONTyped(value?: GameNightBackfill | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'days': value['days'],
        'generated': value['generated'],
        'remaining': value['remaining'],
        'nights': value['nights'] == null ? undefined : ((value['nights'] as Array<any>).map(GameNightBackfillNightToJSON)),
    };
}

