/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Whether a night's LLM summary exists, without shipping its text.
 * 
 * Used by the ops panel to see what the nightly job has and hasn't written.
 * @export
 * @interface GameNightSummaryStatus
 */
export interface GameNightSummaryStatus {
    /**
     * 
     * @type {Date}
     * @memberof GameNightSummaryStatus
     */
    date: Date;
    /**
     * 
     * @type {boolean}
     * @memberof GameNightSummaryStatus
     */
    hasSummary: boolean;
    /**
     * 
     * @type {string}
     * @memberof GameNightSummaryStatus
     */
    provider?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GameNightSummaryStatus
     */
    computedAt?: Date | null;
}

/**
 * Check if a given object implements the GameNightSummaryStatus interface.
 */
export function instanceOfGameNightSummaryStatus(value: object): value is GameNightSummaryStatus {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('hasSummary' in value) || value['hasSummary'] === undefined) return false;
    return true;
}

export function GameNightSummaryStatusFromJSON(json: any): GameNightSummaryStatus {
    return GameNightSummaryStatusFromJSONTyped(json, false);
}

export function GameNightSummaryStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameNightSummaryStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'hasSummary': json['hasSummary'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'computedAt': json['computedAt'] == null ? undefined : (new Date(json['computedAt'])),
    };
}

export function GameNightSummaryStatusToJSON(json: any): GameNightSummaryStatus {
    return GameNightSummaryStatusToJSONTyped(json, false);
}

export function GameNightSummaryStatusToJSONTyped(value?: GameNightSummaryStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'].toISOString().substring(0,10),
        'hasSummary': value['hasSummary'],
        'provider': value['provider'],
        'computedAt': value['computedAt'] == null ? value['computedAt'] : value['computedAt'].toISOString(),
    };
}

