/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One player's night: their record and what they played.
 * 
 * Computed over the night's *decided competitive* games only, so it agrees
 * with every other W/L surface in the app (see the "two match sets" note in
 * CLAUDE.md). Observers never appear - a spectator slot is not a game
 * played.
 * @export
 * @interface GameNightPlayerLine
 */
export interface GameNightPlayerLine {
    /**
     * 
     * @type {string}
     * @memberof GameNightPlayerLine
     */
    player: string;
    /**
     * 
     * @type {number}
     * @memberof GameNightPlayerLine
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof GameNightPlayerLine
     */
    losses: number;
    /**
     * 
     * @type {number}
     * @memberof GameNightPlayerLine
     */
    games: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof GameNightPlayerLine
     */
    generals?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof GameNightPlayerLine
     */
    bestStreak?: number;
    /**
     * 
     * @type {number}
     * @memberof GameNightPlayerLine
     */
    bestApm?: number | null;
}

/**
 * Check if a given object implements the GameNightPlayerLine interface.
 */
export function instanceOfGameNightPlayerLine(value: object): value is GameNightPlayerLine {
    if (!('player' in value) || value['player'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    if (!('games' in value) || value['games'] === undefined) return false;
    return true;
}

export function GameNightPlayerLineFromJSON(json: any): GameNightPlayerLine {
    return GameNightPlayerLineFromJSONTyped(json, false);
}

export function GameNightPlayerLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameNightPlayerLine {
    if (json == null) {
        return json;
    }
    return {
        
        'player': json['player'],
        'wins': json['wins'],
        'losses': json['losses'],
        'games': json['games'],
        'generals': json['generals'] == null ? undefined : json['generals'],
        'bestStreak': json['bestStreak'] == null ? undefined : json['bestStreak'],
        'bestApm': json['bestApm'] == null ? undefined : json['bestApm'],
    };
}

export function GameNightPlayerLineToJSON(json: any): GameNightPlayerLine {
    return GameNightPlayerLineToJSONTyped(json, false);
}

export function GameNightPlayerLineToJSONTyped(value?: GameNightPlayerLine | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player': value['player'],
        'wins': value['wins'],
        'losses': value['losses'],
        'games': value['games'],
        'generals': value['generals'],
        'bestStreak': value['bestStreak'],
        'bestApm': value['bestApm'],
    };
}

