/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameNightPlayerLine } from './GameNightPlayerLine';
import {
    GameNightPlayerLineFromJSON,
    GameNightPlayerLineFromJSONTyped,
    GameNightPlayerLineToJSON,
    GameNightPlayerLineToJSONTyped,
} from './GameNightPlayerLine';
import type { GameNightHighlight } from './GameNightHighlight';
import {
    GameNightHighlightFromJSON,
    GameNightHighlightFromJSONTyped,
    GameNightHighlightToJSON,
    GameNightHighlightToJSONTyped,
} from './GameNightHighlight';

/**
 * Everything the recap page shows for one game night.
 * 
 * ``match_count`` counts every match played that night; ``counted_matches``
 * is the decided-competitive subset the player lines and most highlights are
 * computed over. The two differ when the night included comp-stomps,
 * unfinished games, or games with an unknown player.
 * @export
 * @interface GameNightRecap
 */
export interface GameNightRecap {
    /**
     * 
     * @type {Date}
     * @memberof GameNightRecap
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof GameNightRecap
     */
    matchCount: number;
    /**
     * 
     * @type {number}
     * @memberof GameNightRecap
     */
    countedMatches: number;
    /**
     * 
     * @type {number}
     * @memberof GameNightRecap
     */
    totalMinutes: number;
    /**
     * 
     * @type {number}
     * @memberof GameNightRecap
     */
    medianMinutes?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof GameNightRecap
     */
    startedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof GameNightRecap
     */
    endedAt?: Date | null;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GameNightRecap
     */
    formats?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof GameNightRecap
     */
    maps?: { [key: string]: number; };
    /**
     * 
     * @type {Array<GameNightPlayerLine>}
     * @memberof GameNightRecap
     */
    players?: Array<GameNightPlayerLine>;
    /**
     * 
     * @type {Array<GameNightHighlight>}
     * @memberof GameNightRecap
     */
    highlights?: Array<GameNightHighlight>;
    /**
     * 
     * @type {string}
     * @memberof GameNightRecap
     */
    aiSummary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GameNightRecap
     */
    aiSummaryProvider?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GameNightRecap
     */
    aiSummaryComputedAt?: Date | null;
}

/**
 * Check if a given object implements the GameNightRecap interface.
 */
export function instanceOfGameNightRecap(value: object): value is GameNightRecap {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('matchCount' in value) || value['matchCount'] === undefined) return false;
    if (!('countedMatches' in value) || value['countedMatches'] === undefined) return false;
    if (!('totalMinutes' in value) || value['totalMinutes'] === undefined) return false;
    return true;
}

export function GameNightRecapFromJSON(json: any): GameNightRecap {
    return GameNightRecapFromJSONTyped(json, false);
}

export function GameNightRecapFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameNightRecap {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'matchCount': json['matchCount'],
        'countedMatches': json['countedMatches'],
        'totalMinutes': json['totalMinutes'],
        'medianMinutes': json['medianMinutes'] == null ? undefined : json['medianMinutes'],
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'endedAt': json['endedAt'] == null ? undefined : (new Date(json['endedAt'])),
        'formats': json['formats'] == null ? undefined : json['formats'],
        'maps': json['maps'] == null ? undefined : json['maps'],
        'players': json['players'] == null ? undefined : ((json['players'] as Array<any>).map(GameNightPlayerLineFromJSON)),
        'highlights': json['highlights'] == null ? undefined : ((json['highlights'] as Array<any>).map(GameNightHighlightFromJSON)),
        'aiSummary': json['aiSummary'] == null ? undefined : json['aiSummary'],
        'aiSummaryProvider': json['aiSummaryProvider'] == null ? undefined : json['aiSummaryProvider'],
        'aiSummaryComputedAt': json['aiSummaryComputedAt'] == null ? undefined : (new Date(json['aiSummaryComputedAt'])),
    };
}

export function GameNightRecapToJSON(json: any): GameNightRecap {
    return GameNightRecapToJSONTyped(json, false);
}

export function GameNightRecapToJSONTyped(value?: GameNightRecap | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'].toISOString().substring(0,10),
        'matchCount': value['matchCount'],
        'countedMatches': value['countedMatches'],
        'totalMinutes': value['totalMinutes'],
        'medianMinutes': value['medianMinutes'],
        'startedAt': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'endedAt': value['endedAt'] == null ? value['endedAt'] : value['endedAt'].toISOString(),
        'formats': value['formats'],
        'maps': value['maps'],
        'players': value['players'] == null ? undefined : ((value['players'] as Array<any>).map(GameNightPlayerLineToJSON)),
        'highlights': value['highlights'] == null ? undefined : ((value['highlights'] as Array<any>).map(GameNightHighlightToJSON)),
        'aiSummary': value['aiSummary'],
        'aiSummaryProvider': value['aiSummaryProvider'],
        'aiSummaryComputedAt': value['aiSummaryComputedAt'] == null ? value['aiSummaryComputedAt'] : value['aiSummaryComputedAt'].toISOString(),
    };
}

