/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { General } from './General';
import {
    GeneralFromJSON,
    GeneralFromJSONTyped,
    GeneralToJSON,
    GeneralToJSONTyped,
} from './General';

/**
 * Actual 1v1 record between two generals - `a_wins`/`b_wins` are wins for
 * whichever human piloted `general_a`/`general_b` respectively in those
 * games, so `a_wins + b_wins` is the total games seen for this pair.
 * @export
 * @interface GeneralMatchupCell
 */
export interface GeneralMatchupCell {
    /**
     * 
     * @type {General}
     * @memberof GeneralMatchupCell
     */
    generalA: General;
    /**
     * 
     * @type {General}
     * @memberof GeneralMatchupCell
     */
    generalB: General;
    /**
     * 
     * @type {number}
     * @memberof GeneralMatchupCell
     */
    aWins: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralMatchupCell
     */
    bWins: number;
}



/**
 * Check if a given object implements the GeneralMatchupCell interface.
 */
export function instanceOfGeneralMatchupCell(value: object): value is GeneralMatchupCell {
    if (!('generalA' in value) || value['generalA'] === undefined) return false;
    if (!('generalB' in value) || value['generalB'] === undefined) return false;
    if (!('aWins' in value) || value['aWins'] === undefined) return false;
    if (!('bWins' in value) || value['bWins'] === undefined) return false;
    return true;
}

export function GeneralMatchupCellFromJSON(json: any): GeneralMatchupCell {
    return GeneralMatchupCellFromJSONTyped(json, false);
}

export function GeneralMatchupCellFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralMatchupCell {
    if (json == null) {
        return json;
    }
    return {
        
        'generalA': GeneralFromJSON(json['generalA']),
        'generalB': GeneralFromJSON(json['generalB']),
        'aWins': json['aWins'],
        'bWins': json['bWins'],
    };
}

export function GeneralMatchupCellToJSON(json: any): GeneralMatchupCell {
    return GeneralMatchupCellToJSONTyped(json, false);
}

export function GeneralMatchupCellToJSONTyped(value?: GeneralMatchupCell | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'generalA': GeneralToJSON(value['generalA']),
        'generalB': GeneralToJSON(value['generalB']),
        'aWins': value['aWins'],
        'bWins': value['bWins'],
    };
}

