/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneralMatchupCell } from './GeneralMatchupCell';
import {
    GeneralMatchupCellFromJSON,
    GeneralMatchupCellFromJSONTyped,
    GeneralMatchupCellToJSON,
    GeneralMatchupCellToJSONTyped,
} from './GeneralMatchupCell';

/**
 * 
 * @export
 * @interface GeneralMatchups
 */
export interface GeneralMatchups {
    /**
     * 
     * @type {Array<GeneralMatchupCell>}
     * @memberof GeneralMatchups
     */
    cells: Array<GeneralMatchupCell>;
}

/**
 * Check if a given object implements the GeneralMatchups interface.
 */
export function instanceOfGeneralMatchups(value: object): value is GeneralMatchups {
    if (!('cells' in value) || value['cells'] === undefined) return false;
    return true;
}

export function GeneralMatchupsFromJSON(json: any): GeneralMatchups {
    return GeneralMatchupsFromJSONTyped(json, false);
}

export function GeneralMatchupsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralMatchups {
    if (json == null) {
        return json;
    }
    return {
        
        'cells': ((json['cells'] as Array<any>).map(GeneralMatchupCellFromJSON)),
    };
}

export function GeneralMatchupsToJSON(json: any): GeneralMatchups {
    return GeneralMatchupsToJSONTyped(json, false);
}

export function GeneralMatchupsToJSONTyped(value?: GeneralMatchups | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cells': ((value['cells'] as Array<any>).map(GeneralMatchupCellToJSON)),
    };
}

