/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneralStatOutput } from './GeneralStatOutput';
import {
    GeneralStatOutputFromJSON,
    GeneralStatOutputFromJSONTyped,
    GeneralStatOutputToJSON,
    GeneralStatOutputToJSONTyped,
} from './GeneralStatOutput';

/**
 * 
 * @export
 * @interface GeneralStats
 */
export interface GeneralStats {
    /**
     * 
     * @type {Array<GeneralStatOutput>}
     * @memberof GeneralStats
     */
    generalStats: Array<GeneralStatOutput>;
}

/**
 * Check if a given object implements the GeneralStats interface.
 */
export function instanceOfGeneralStats(value: object): value is GeneralStats {
    if (!('generalStats' in value) || value['generalStats'] === undefined) return false;
    return true;
}

export function GeneralStatsFromJSON(json: any): GeneralStats {
    return GeneralStatsFromJSONTyped(json, false);
}

export function GeneralStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralStats {
    if (json == null) {
        return json;
    }
    return {
        
        'generalStats': ((json['general_stats'] as Array<any>).map(GeneralStatOutputFromJSON)),
    };
}

export function GeneralStatsToJSON(json: any): GeneralStats {
    return GeneralStatsToJSONTyped(json, false);
}

export function GeneralStatsToJSONTyped(value?: GeneralStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'general_stats': ((value['generalStats'] as Array<any>).map(GeneralStatOutputToJSON)),
    };
}

