/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One point in a player's running win-rate-over-time series for a general.
 * 
 * ``wins``/``losses`` are cumulative as of this game (not just this game's
 * result), so plotting ``win_rate`` against ``game_number`` traces how the
 * player's record on this general evolved.
 * @export
 * @interface GeneralWinRatePoint
 */
export interface GeneralWinRatePoint {
    /**
     * 
     * @type {Date}
     * @memberof GeneralWinRatePoint
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof GeneralWinRatePoint
     */
    gameNumber: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralWinRatePoint
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralWinRatePoint
     */
    losses: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralWinRatePoint
     */
    winRate: number;
}

/**
 * Check if a given object implements the GeneralWinRatePoint interface.
 */
export function instanceOfGeneralWinRatePoint(value: object): value is GeneralWinRatePoint {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('gameNumber' in value) || value['gameNumber'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    if (!('winRate' in value) || value['winRate'] === undefined) return false;
    return true;
}

export function GeneralWinRatePointFromJSON(json: any): GeneralWinRatePoint {
    return GeneralWinRatePointFromJSONTyped(json, false);
}

export function GeneralWinRatePointFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralWinRatePoint {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'gameNumber': json['gameNumber'],
        'wins': json['wins'],
        'losses': json['losses'],
        'winRate': json['winRate'],
    };
}

export function GeneralWinRatePointToJSON(json: any): GeneralWinRatePoint {
    return GeneralWinRatePointToJSONTyped(json, false);
}

export function GeneralWinRatePointToJSONTyped(value?: GeneralWinRatePoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'].toISOString().substring(0,10),
        'gameNumber': value['gameNumber'],
        'wins': value['wins'],
        'losses': value['losses'],
        'winRate': value['winRate'],
    };
}

