/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WinLoss } from './WinLoss';
import {
    WinLossFromJSON,
    WinLossFromJSONTyped,
    WinLossToJSON,
    WinLossToJSONTyped,
} from './WinLoss';
import type { General } from './General';
import {
    GeneralFromJSON,
    GeneralFromJSONTyped,
    GeneralToJSON,
    GeneralToJSONTyped,
} from './General';
import type { GeneralStatPlayerWL } from './GeneralStatPlayerWL';
import {
    GeneralStatPlayerWLFromJSON,
    GeneralStatPlayerWLFromJSONTyped,
    GeneralStatPlayerWLToJSON,
    GeneralStatPlayerWLToJSONTyped,
} from './GeneralStatPlayerWL';

/**
 * 
 * @export
 * @interface GeneralStat
 */
export interface GeneralStat {
    /**
     * 
     * @type {General}
     * @memberof GeneralStat
     */
    general: General;
    /**
     * 
     * @type {Array<GeneralStatPlayerWL>}
     * @memberof GeneralStat
     */
    stats: Array<GeneralStatPlayerWL>;
    /**
     * 
     * @type {WinLoss}
     * @memberof GeneralStat
     */
    total: WinLoss;
}



/**
 * Check if a given object implements the GeneralStat interface.
 */
export function instanceOfGeneralStat(value: object): value is GeneralStat {
    if (!('general' in value) || value['general'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function GeneralStatFromJSON(json: any): GeneralStat {
    return GeneralStatFromJSONTyped(json, false);
}

export function GeneralStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralStat {
    if (json == null) {
        return json;
    }
    return {
        
        'general': GeneralFromJSON(json['general']),
        'stats': ((json['stats'] as Array<any>).map(GeneralStatPlayerWLFromJSON)),
        'total': WinLossFromJSON(json['total']),
    };
}

export function GeneralStatToJSON(json: any): GeneralStat {
    return GeneralStatToJSONTyped(json, false);
}

export function GeneralStatToJSONTyped(value?: GeneralStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'general': GeneralToJSON(value['general']),
        'stats': ((value['stats'] as Array<any>).map(GeneralStatPlayerWLToJSON)),
        'total': WinLossToJSON(value['total']),
    };
}

