/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneralWinRatePoint } from './GeneralWinRatePoint';
import {
    GeneralWinRatePointFromJSON,
    GeneralWinRatePointFromJSONTyped,
    GeneralWinRatePointToJSON,
    GeneralWinRatePointToJSONTyped,
} from './GeneralWinRatePoint';
import type { General } from './General';
import {
    GeneralFromJSON,
    GeneralFromJSONTyped,
    GeneralToJSON,
    GeneralToJSONTyped,
} from './General';

/**
 * 
 * @export
 * @interface GeneralWinRateSeries
 */
export interface GeneralWinRateSeries {
    /**
     * 
     * @type {General}
     * @memberof GeneralWinRateSeries
     */
    general: General;
    /**
     * 
     * @type {Array<GeneralWinRatePoint>}
     * @memberof GeneralWinRateSeries
     */
    points: Array<GeneralWinRatePoint>;
}



/**
 * Check if a given object implements the GeneralWinRateSeries interface.
 */
export function instanceOfGeneralWinRateSeries(value: object): value is GeneralWinRateSeries {
    if (!('general' in value) || value['general'] === undefined) return false;
    if (!('points' in value) || value['points'] === undefined) return false;
    return true;
}

export function GeneralWinRateSeriesFromJSON(json: any): GeneralWinRateSeries {
    return GeneralWinRateSeriesFromJSONTyped(json, false);
}

export function GeneralWinRateSeriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralWinRateSeries {
    if (json == null) {
        return json;
    }
    return {
        
        'general': GeneralFromJSON(json['general']),
        'points': ((json['points'] as Array<any>).map(GeneralWinRatePointFromJSON)),
    };
}

export function GeneralWinRateSeriesToJSON(json: any): GeneralWinRateSeries {
    return GeneralWinRateSeriesToJSONTyped(json, false);
}

export function GeneralWinRateSeriesToJSONTyped(value?: GeneralWinRateSeries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'general': GeneralToJSON(value['general']),
        'points': ((value['points'] as Array<any>).map(GeneralWinRatePointToJSON)),
    };
}

