/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { General } from './General';
import {
    GeneralFromJSON,
    GeneralFromJSONTyped,
    GeneralToJSON,
    GeneralToJSONTyped,
} from './General';

/**
 * 
 * @export
 * @interface GeneralProfileStat
 */
export interface GeneralProfileStat {
    /**
     * 
     * @type {General}
     * @memberof GeneralProfileStat
     */
    general: General;
    /**
     * 
     * @type {number}
     * @memberof GeneralProfileStat
     */
    games: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralProfileStat
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralProfileStat
     */
    losses: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralProfileStat
     */
    winRate: number;
}



/**
 * Check if a given object implements the GeneralProfileStat interface.
 */
export function instanceOfGeneralProfileStat(value: object): value is GeneralProfileStat {
    if (!('general' in value) || value['general'] === undefined) return false;
    if (!('games' in value) || value['games'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    if (!('winRate' in value) || value['winRate'] === undefined) return false;
    return true;
}

export function GeneralProfileStatFromJSON(json: any): GeneralProfileStat {
    return GeneralProfileStatFromJSONTyped(json, false);
}

export function GeneralProfileStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralProfileStat {
    if (json == null) {
        return json;
    }
    return {
        
        'general': GeneralFromJSON(json['general']),
        'games': json['games'],
        'wins': json['wins'],
        'losses': json['losses'],
        'winRate': json['winRate'],
    };
}

export function GeneralProfileStatToJSON(json: any): GeneralProfileStat {
    return GeneralProfileStatToJSONTyped(json, false);
}

export function GeneralProfileStatToJSONTyped(value?: GeneralProfileStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'general': GeneralToJSON(value['general']),
        'games': value['games'],
        'wins': value['wins'],
        'losses': value['losses'],
        'winRate': value['winRate'],
    };
}

