/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HeadToHeadGeneralRecord } from './HeadToHeadGeneralRecord';
import {
    HeadToHeadGeneralRecordFromJSON,
    HeadToHeadGeneralRecordFromJSONTyped,
    HeadToHeadGeneralRecordToJSON,
    HeadToHeadGeneralRecordToJSONTyped,
} from './HeadToHeadGeneralRecord';
import type { HeadToHeadGame } from './HeadToHeadGame';
import {
    HeadToHeadGameFromJSON,
    HeadToHeadGameFromJSONTyped,
    HeadToHeadGameToJSON,
    HeadToHeadGameToJSONTyped,
} from './HeadToHeadGame';
import type { HeadToHeadMapRecord } from './HeadToHeadMapRecord';
import {
    HeadToHeadMapRecordFromJSON,
    HeadToHeadMapRecordFromJSONTyped,
    HeadToHeadMapRecordToJSON,
    HeadToHeadMapRecordToJSONTyped,
} from './HeadToHeadMapRecord';

/**
 * Detailed head-to-head record between two players in opposite-team games,
 * plus how often they've been teammates instead.
 * @export
 * @interface HeadToHeadDetail
 */
export interface HeadToHeadDetail {
    /**
     * 
     * @type {string}
     * @memberof HeadToHeadDetail
     */
    player1: string;
    /**
     * 
     * @type {string}
     * @memberof HeadToHeadDetail
     */
    player2: string;
    /**
     * 
     * @type {number}
     * @memberof HeadToHeadDetail
     */
    player1Wins: number;
    /**
     * 
     * @type {number}
     * @memberof HeadToHeadDetail
     */
    player2Wins: number;
    /**
     * 
     * @type {Array<HeadToHeadGame>}
     * @memberof HeadToHeadDetail
     */
    games: Array<HeadToHeadGame>;
    /**
     * 
     * @type {Array<HeadToHeadGeneralRecord>}
     * @memberof HeadToHeadDetail
     */
    player1ByGeneral: Array<HeadToHeadGeneralRecord>;
    /**
     * 
     * @type {Array<HeadToHeadGeneralRecord>}
     * @memberof HeadToHeadDetail
     */
    player2ByGeneral: Array<HeadToHeadGeneralRecord>;
    /**
     * 
     * @type {Array<HeadToHeadMapRecord>}
     * @memberof HeadToHeadDetail
     */
    byMap: Array<HeadToHeadMapRecord>;
    /**
     * 
     * @type {number}
     * @memberof HeadToHeadDetail
     */
    player1ValueDestroyed?: number;
    /**
     * 
     * @type {number}
     * @memberof HeadToHeadDetail
     */
    player2ValueDestroyed?: number;
    /**
     * 
     * @type {number}
     * @memberof HeadToHeadDetail
     */
    teammateGames: number;
    /**
     * 
     * @type {number}
     * @memberof HeadToHeadDetail
     */
    teammateWins: number;
}

/**
 * Check if a given object implements the HeadToHeadDetail interface.
 */
export function instanceOfHeadToHeadDetail(value: object): value is HeadToHeadDetail {
    if (!('player1' in value) || value['player1'] === undefined) return false;
    if (!('player2' in value) || value['player2'] === undefined) return false;
    if (!('player1Wins' in value) || value['player1Wins'] === undefined) return false;
    if (!('player2Wins' in value) || value['player2Wins'] === undefined) return false;
    if (!('games' in value) || value['games'] === undefined) return false;
    if (!('player1ByGeneral' in value) || value['player1ByGeneral'] === undefined) return false;
    if (!('player2ByGeneral' in value) || value['player2ByGeneral'] === undefined) return false;
    if (!('byMap' in value) || value['byMap'] === undefined) return false;
    if (!('teammateGames' in value) || value['teammateGames'] === undefined) return false;
    if (!('teammateWins' in value) || value['teammateWins'] === undefined) return false;
    return true;
}

export function HeadToHeadDetailFromJSON(json: any): HeadToHeadDetail {
    return HeadToHeadDetailFromJSONTyped(json, false);
}

export function HeadToHeadDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeadToHeadDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'player1': json['player1'],
        'player2': json['player2'],
        'player1Wins': json['player1Wins'],
        'player2Wins': json['player2Wins'],
        'games': ((json['games'] as Array<any>).map(HeadToHeadGameFromJSON)),
        'player1ByGeneral': ((json['player1ByGeneral'] as Array<any>).map(HeadToHeadGeneralRecordFromJSON)),
        'player2ByGeneral': ((json['player2ByGeneral'] as Array<any>).map(HeadToHeadGeneralRecordFromJSON)),
        'byMap': ((json['byMap'] as Array<any>).map(HeadToHeadMapRecordFromJSON)),
        'player1ValueDestroyed': json['player1ValueDestroyed'] == null ? undefined : json['player1ValueDestroyed'],
        'player2ValueDestroyed': json['player2ValueDestroyed'] == null ? undefined : json['player2ValueDestroyed'],
        'teammateGames': json['teammateGames'],
        'teammateWins': json['teammateWins'],
    };
}

export function HeadToHeadDetailToJSON(json: any): HeadToHeadDetail {
    return HeadToHeadDetailToJSONTyped(json, false);
}

export function HeadToHeadDetailToJSONTyped(value?: HeadToHeadDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player1': value['player1'],
        'player2': value['player2'],
        'player1Wins': value['player1Wins'],
        'player2Wins': value['player2Wins'],
        'games': ((value['games'] as Array<any>).map(HeadToHeadGameToJSON)),
        'player1ByGeneral': ((value['player1ByGeneral'] as Array<any>).map(HeadToHeadGeneralRecordToJSON)),
        'player2ByGeneral': ((value['player2ByGeneral'] as Array<any>).map(HeadToHeadGeneralRecordToJSON)),
        'byMap': ((value['byMap'] as Array<any>).map(HeadToHeadMapRecordToJSON)),
        'player1ValueDestroyed': value['player1ValueDestroyed'],
        'player2ValueDestroyed': value['player2ValueDestroyed'],
        'teammateGames': value['teammateGames'],
        'teammateWins': value['teammateWins'],
    };
}

