/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { General } from './General';
import {
    GeneralFromJSON,
    GeneralFromJSONTyped,
    GeneralToJSON,
    GeneralToJSONTyped,
} from './General';

/**
 * 
 * @export
 * @interface HeadToHeadGame
 */
export interface HeadToHeadGame {
    /**
     * 
     * @type {number}
     * @memberof HeadToHeadGame
     */
    matchId: number;
    /**
     * 
     * @type {Date}
     * @memberof HeadToHeadGame
     */
    timestamp: Date;
    /**
     * 
     * @type {Date}
     * @memberof HeadToHeadGame
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof HeadToHeadGame
     */
    map: string;
    /**
     * 
     * @type {number}
     * @memberof HeadToHeadGame
     */
    durationMinutes: number;
    /**
     * 
     * @type {string}
     * @memberof HeadToHeadGame
     */
    gameFormat?: string | null;
    /**
     * 
     * @type {General}
     * @memberof HeadToHeadGame
     */
    player1General: General;
    /**
     * 
     * @type {General}
     * @memberof HeadToHeadGame
     */
    player2General: General;
    /**
     * 
     * @type {boolean}
     * @memberof HeadToHeadGame
     */
    player1Won: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof HeadToHeadGame
     */
    player1Team: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof HeadToHeadGame
     */
    player2Team: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof HeadToHeadGame
     */
    player1ValueDestroyed?: number;
    /**
     * 
     * @type {number}
     * @memberof HeadToHeadGame
     */
    player2ValueDestroyed?: number;
}



/**
 * Check if a given object implements the HeadToHeadGame interface.
 */
export function instanceOfHeadToHeadGame(value: object): value is HeadToHeadGame {
    if (!('matchId' in value) || value['matchId'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('map' in value) || value['map'] === undefined) return false;
    if (!('durationMinutes' in value) || value['durationMinutes'] === undefined) return false;
    if (!('player1General' in value) || value['player1General'] === undefined) return false;
    if (!('player2General' in value) || value['player2General'] === undefined) return false;
    if (!('player1Won' in value) || value['player1Won'] === undefined) return false;
    if (!('player1Team' in value) || value['player1Team'] === undefined) return false;
    if (!('player2Team' in value) || value['player2Team'] === undefined) return false;
    return true;
}

export function HeadToHeadGameFromJSON(json: any): HeadToHeadGame {
    return HeadToHeadGameFromJSONTyped(json, false);
}

export function HeadToHeadGameFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeadToHeadGame {
    if (json == null) {
        return json;
    }
    return {
        
        'matchId': json['matchId'],
        'timestamp': (new Date(json['timestamp'])),
        'date': (new Date(json['date'])),
        'map': json['map'],
        'durationMinutes': json['durationMinutes'],
        'gameFormat': json['gameFormat'] == null ? undefined : json['gameFormat'],
        'player1General': GeneralFromJSON(json['player1General']),
        'player2General': GeneralFromJSON(json['player2General']),
        'player1Won': json['player1Won'],
        'player1Team': json['player1Team'],
        'player2Team': json['player2Team'],
        'player1ValueDestroyed': json['player1ValueDestroyed'] == null ? undefined : json['player1ValueDestroyed'],
        'player2ValueDestroyed': json['player2ValueDestroyed'] == null ? undefined : json['player2ValueDestroyed'],
    };
}

export function HeadToHeadGameToJSON(json: any): HeadToHeadGame {
    return HeadToHeadGameToJSONTyped(json, false);
}

export function HeadToHeadGameToJSONTyped(value?: HeadToHeadGame | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'matchId': value['matchId'],
        'timestamp': value['timestamp'].toISOString(),
        'date': value['date'].toISOString().substring(0,10),
        'map': value['map'],
        'durationMinutes': value['durationMinutes'],
        'gameFormat': value['gameFormat'],
        'player1General': GeneralToJSON(value['player1General']),
        'player2General': GeneralToJSON(value['player2General']),
        'player1Won': value['player1Won'],
        'player1Team': value['player1Team'],
        'player2Team': value['player2Team'],
        'player1ValueDestroyed': value['player1ValueDestroyed'],
        'player2ValueDestroyed': value['player2ValueDestroyed'],
    };
}

