/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KillEventOutput
 */
export interface KillEventOutput {
    /**
     * 
     * @type {number}
     * @memberof KillEventOutput
     */
    atMinute: number;
    /**
     * 
     * @type {string}
     * @memberof KillEventOutput
     */
    killerPlayer: string;
    /**
     * 
     * @type {string}
     * @memberof KillEventOutput
     */
    victimPlayer: string;
    /**
     * 
     * @type {number}
     * @memberof KillEventOutput
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof KillEventOutput
     */
    y: number;
    /**
     * 
     * @type {string}
     * @memberof KillEventOutput
     */
    killer: string;
    /**
     * 
     * @type {string}
     * @memberof KillEventOutput
     */
    victim: string;
    /**
     * 
     * @type {string}
     * @memberof KillEventOutput
     */
    damageType: string;
    /**
     * 
     * @type {number}
     * @memberof KillEventOutput
     */
    value?: number;
}

/**
 * Check if a given object implements the KillEventOutput interface.
 */
export function instanceOfKillEventOutput(value: object): value is KillEventOutput {
    if (!('atMinute' in value) || value['atMinute'] === undefined) return false;
    if (!('killerPlayer' in value) || value['killerPlayer'] === undefined) return false;
    if (!('victimPlayer' in value) || value['victimPlayer'] === undefined) return false;
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    if (!('killer' in value) || value['killer'] === undefined) return false;
    if (!('victim' in value) || value['victim'] === undefined) return false;
    if (!('damageType' in value) || value['damageType'] === undefined) return false;
    return true;
}

export function KillEventOutputFromJSON(json: any): KillEventOutput {
    return KillEventOutputFromJSONTyped(json, false);
}

export function KillEventOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): KillEventOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'atMinute': json['atMinute'],
        'killerPlayer': json['killerPlayer'],
        'victimPlayer': json['victimPlayer'],
        'x': json['x'],
        'y': json['y'],
        'killer': json['killer'],
        'victim': json['victim'],
        'damageType': json['damageType'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function KillEventOutputToJSON(json: any): KillEventOutput {
    return KillEventOutputToJSONTyped(json, false);
}

export function KillEventOutputToJSONTyped(value?: KillEventOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'atMinute': value['atMinute'],
        'killerPlayer': value['killerPlayer'],
        'victimPlayer': value['victimPlayer'],
        'x': value['x'],
        'y': value['y'],
        'killer': value['killer'],
        'victim': value['victim'],
        'damageType': value['damageType'],
        'value': value['value'],
    };
}

