/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MapPoint } from './MapPoint';
import {
    MapPointFromJSON,
    MapPointFromJSONTyped,
    MapPointToJSON,
    MapPointToJSONTyped,
} from './MapPoint';
import type { MapExtent } from './MapExtent';
import {
    MapExtentFromJSON,
    MapExtentFromJSONTyped,
    MapExtentToJSON,
    MapExtentToJSONTyped,
} from './MapExtent';
import type { MapPlayerStart } from './MapPlayerStart';
import {
    MapPlayerStartFromJSON,
    MapPlayerStartFromJSONTyped,
    MapPlayerStartToJSON,
    MapPlayerStartToJSONTyped,
} from './MapPlayerStart';

/**
 * 
 * @export
 * @interface MapDataPayload
 */
export interface MapDataPayload {
    /**
     * 
     * @type {MapExtent}
     * @memberof MapDataPayload
     */
    extent: MapExtent;
    /**
     * 
     * @type {Array<MapPlayerStart>}
     * @memberof MapDataPayload
     */
    playerStarts: Array<MapPlayerStart>;
    /**
     * 
     * @type {Array<MapPoint>}
     * @memberof MapDataPayload
     */
    supply: Array<MapPoint>;
    /**
     * 
     * @type {Array<MapPoint>}
     * @memberof MapDataPayload
     */
    tech: Array<MapPoint>;
    /**
     * 
     * @type {Array<MapPoint>}
     * @memberof MapDataPayload
     */
    waypoints: Array<MapPoint>;
}

/**
 * Check if a given object implements the MapDataPayload interface.
 */
export function instanceOfMapDataPayload(value: object): value is MapDataPayload {
    if (!('extent' in value) || value['extent'] === undefined) return false;
    if (!('playerStarts' in value) || value['playerStarts'] === undefined) return false;
    if (!('supply' in value) || value['supply'] === undefined) return false;
    if (!('tech' in value) || value['tech'] === undefined) return false;
    if (!('waypoints' in value) || value['waypoints'] === undefined) return false;
    return true;
}

export function MapDataPayloadFromJSON(json: any): MapDataPayload {
    return MapDataPayloadFromJSONTyped(json, false);
}

export function MapDataPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapDataPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'extent': MapExtentFromJSON(json['extent']),
        'playerStarts': ((json['player_starts'] as Array<any>).map(MapPlayerStartFromJSON)),
        'supply': ((json['supply'] as Array<any>).map(MapPointFromJSON)),
        'tech': ((json['tech'] as Array<any>).map(MapPointFromJSON)),
        'waypoints': ((json['waypoints'] as Array<any>).map(MapPointFromJSON)),
    };
}

export function MapDataPayloadToJSON(json: any): MapDataPayload {
    return MapDataPayloadToJSONTyped(json, false);
}

export function MapDataPayloadToJSONTyped(value?: MapDataPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extent': MapExtentToJSON(value['extent']),
        'player_starts': ((value['playerStarts'] as Array<any>).map(MapPlayerStartToJSON)),
        'supply': ((value['supply'] as Array<any>).map(MapPointToJSON)),
        'tech': ((value['tech'] as Array<any>).map(MapPointToJSON)),
        'waypoints': ((value['waypoints'] as Array<any>).map(MapPointToJSON)),
    };
}

