/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapExtent
 */
export interface MapExtent {
    /**
     * 
     * @type {number}
     * @memberof MapExtent
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof MapExtent
     */
    height: number;
    /**
     * 
     * @type {number}
     * @memberof MapExtent
     */
    gridWidth: number;
    /**
     * 
     * @type {number}
     * @memberof MapExtent
     */
    gridHeight: number;
    /**
     * 
     * @type {number}
     * @memberof MapExtent
     */
    borderSize: number;
}

/**
 * Check if a given object implements the MapExtent interface.
 */
export function instanceOfMapExtent(value: object): value is MapExtent {
    if (!('width' in value) || value['width'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('gridWidth' in value) || value['gridWidth'] === undefined) return false;
    if (!('gridHeight' in value) || value['gridHeight'] === undefined) return false;
    if (!('borderSize' in value) || value['borderSize'] === undefined) return false;
    return true;
}

export function MapExtentFromJSON(json: any): MapExtent {
    return MapExtentFromJSONTyped(json, false);
}

export function MapExtentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapExtent {
    if (json == null) {
        return json;
    }
    return {
        
        'width': json['width'],
        'height': json['height'],
        'gridWidth': json['grid_width'],
        'gridHeight': json['grid_height'],
        'borderSize': json['border_size'],
    };
}

export function MapExtentToJSON(json: any): MapExtent {
    return MapExtentToJSONTyped(json, false);
}

export function MapExtentToJSONTyped(value?: MapExtent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'width': value['width'],
        'height': value['height'],
        'grid_width': value['gridWidth'],
        'grid_height': value['gridHeight'],
        'border_size': value['borderSize'],
    };
}

