/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single map-positioned, time-stamped event for replay playback.
 * 
 * `kind` is one of "build" (structure completed) or "capture" (neutral/enemy
 * structure taken). `player_name` is the owner after the event; `name` is the
 * cleaned object name. Kill events are served separately via `kill_events`.
 * @export
 * @interface MapEventOutput
 */
export interface MapEventOutput {
    /**
     * 
     * @type {number}
     * @memberof MapEventOutput
     */
    atMinute: number;
    /**
     * 
     * @type {number}
     * @memberof MapEventOutput
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof MapEventOutput
     */
    y: number;
    /**
     * 
     * @type {string}
     * @memberof MapEventOutput
     */
    playerName: string;
    /**
     * 
     * @type {string}
     * @memberof MapEventOutput
     */
    kind: string;
    /**
     * 
     * @type {string}
     * @memberof MapEventOutput
     */
    name: string;
}

/**
 * Check if a given object implements the MapEventOutput interface.
 */
export function instanceOfMapEventOutput(value: object): value is MapEventOutput {
    if (!('atMinute' in value) || value['atMinute'] === undefined) return false;
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    if (!('playerName' in value) || value['playerName'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MapEventOutputFromJSON(json: any): MapEventOutput {
    return MapEventOutputFromJSONTyped(json, false);
}

export function MapEventOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapEventOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'atMinute': json['atMinute'],
        'x': json['x'],
        'y': json['y'],
        'playerName': json['playerName'],
        'kind': json['kind'],
        'name': json['name'],
    };
}

export function MapEventOutputToJSON(json: any): MapEventOutput {
    return MapEventOutputToJSONTyped(json, false);
}

export function MapEventOutputToJSONTyped(value?: MapEventOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'atMinute': value['atMinute'],
        'x': value['x'],
        'y': value['y'],
        'playerName': value['playerName'],
        'kind': value['kind'],
        'name': value['name'],
    };
}

