/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { General } from './General';
import {
    GeneralFromJSON,
    GeneralFromJSONTyped,
    GeneralToJSON,
    GeneralToJSONTyped,
} from './General';

/**
 * 
 * @export
 * @interface MapGeneralWL
 */
export interface MapGeneralWL {
    /**
     * 
     * @type {General}
     * @memberof MapGeneralWL
     */
    general: General;
    /**
     * 
     * @type {number}
     * @memberof MapGeneralWL
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof MapGeneralWL
     */
    losses: number;
    /**
     * 
     * @type {number}
     * @memberof MapGeneralWL
     */
    winRateDelta?: number;
}



/**
 * Check if a given object implements the MapGeneralWL interface.
 */
export function instanceOfMapGeneralWL(value: object): value is MapGeneralWL {
    if (!('general' in value) || value['general'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    return true;
}

export function MapGeneralWLFromJSON(json: any): MapGeneralWL {
    return MapGeneralWLFromJSONTyped(json, false);
}

export function MapGeneralWLFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapGeneralWL {
    if (json == null) {
        return json;
    }
    return {
        
        'general': GeneralFromJSON(json['general']),
        'wins': json['wins'],
        'losses': json['losses'],
        'winRateDelta': json['winRateDelta'] == null ? undefined : json['winRateDelta'],
    };
}

export function MapGeneralWLToJSON(json: any): MapGeneralWL {
    return MapGeneralWLToJSONTyped(json, false);
}

export function MapGeneralWLToJSONTyped(value?: MapGeneralWL | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'general': GeneralToJSON(value['general']),
        'wins': value['wins'],
        'losses': value['losses'],
        'winRateDelta': value['winRateDelta'],
    };
}

