/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapMatchCount
 */
export interface MapMatchCount {
    /**
     * 
     * @type {string}
     * @memberof MapMatchCount
     */
    map: string;
    /**
     * 
     * @type {number}
     * @memberof MapMatchCount
     */
    matchCount: number;
}

/**
 * Check if a given object implements the MapMatchCount interface.
 */
export function instanceOfMapMatchCount(value: object): value is MapMatchCount {
    if (!('map' in value) || value['map'] === undefined) return false;
    if (!('matchCount' in value) || value['matchCount'] === undefined) return false;
    return true;
}

export function MapMatchCountFromJSON(json: any): MapMatchCount {
    return MapMatchCountFromJSONTyped(json, false);
}

export function MapMatchCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapMatchCount {
    if (json == null) {
        return json;
    }
    return {
        
        'map': json['map'],
        'matchCount': json['matchCount'],
    };
}

export function MapMatchCountToJSON(json: any): MapMatchCount {
    return MapMatchCountToJSONTyped(json, false);
}

export function MapMatchCountToJSONTyped(value?: MapMatchCount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'map': value['map'],
        'matchCount': value['matchCount'],
    };
}

