/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapPlayerWL
 */
export interface MapPlayerWL {
    /**
     * 
     * @type {string}
     * @memberof MapPlayerWL
     */
    player: string;
    /**
     * 
     * @type {number}
     * @memberof MapPlayerWL
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof MapPlayerWL
     */
    losses: number;
}

/**
 * Check if a given object implements the MapPlayerWL interface.
 */
export function instanceOfMapPlayerWL(value: object): value is MapPlayerWL {
    if (!('player' in value) || value['player'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    return true;
}

export function MapPlayerWLFromJSON(json: any): MapPlayerWL {
    return MapPlayerWLFromJSONTyped(json, false);
}

export function MapPlayerWLFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapPlayerWL {
    if (json == null) {
        return json;
    }
    return {
        
        'player': json['player'],
        'wins': json['wins'],
        'losses': json['losses'],
    };
}

export function MapPlayerWLToJSON(json: any): MapPlayerWL {
    return MapPlayerWLToJSONTyped(json, false);
}

export function MapPlayerWLToJSONTyped(value?: MapPlayerWL | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player': value['player'],
        'wins': value['wins'],
        'losses': value['losses'],
    };
}

