/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapProfileStat
 */
export interface MapProfileStat {
    /**
     * 
     * @type {string}
     * @memberof MapProfileStat
     */
    map: string;
    /**
     * 
     * @type {number}
     * @memberof MapProfileStat
     */
    games: number;
    /**
     * 
     * @type {number}
     * @memberof MapProfileStat
     */
    wins: number;
    /**
     * 
     * @type {number}
     * @memberof MapProfileStat
     */
    losses: number;
}

/**
 * Check if a given object implements the MapProfileStat interface.
 */
export function instanceOfMapProfileStat(value: object): value is MapProfileStat {
    if (!('map' in value) || value['map'] === undefined) return false;
    if (!('games' in value) || value['games'] === undefined) return false;
    if (!('wins' in value) || value['wins'] === undefined) return false;
    if (!('losses' in value) || value['losses'] === undefined) return false;
    return true;
}

export function MapProfileStatFromJSON(json: any): MapProfileStat {
    return MapProfileStatFromJSONTyped(json, false);
}

export function MapProfileStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapProfileStat {
    if (json == null) {
        return json;
    }
    return {
        
        'map': json['map'],
        'games': json['games'],
        'wins': json['wins'],
        'losses': json['losses'],
    };
}

export function MapProfileStatToJSON(json: any): MapProfileStat {
    return MapProfileStatToJSONTyped(json, false);
}

export function MapProfileStatToJSONTyped(value?: MapProfileStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'map': value['map'],
        'games': value['games'],
        'wins': value['wins'],
        'losses': value['losses'],
    };
}

