/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MapRenderPlayer } from './MapRenderPlayer';
import {
    MapRenderPlayerFromJSON,
    MapRenderPlayerFromJSONTyped,
    MapRenderPlayerToJSON,
    MapRenderPlayerToJSONTyped,
} from './MapRenderPlayer';

/**
 * 
 * @export
 * @interface MapRenderRequest
 */
export interface MapRenderRequest {
    /**
     * 
     * @type {string}
     * @memberof MapRenderRequest
     */
    mapName: string;
    /**
     * 
     * @type {Array<MapRenderPlayer>}
     * @memberof MapRenderRequest
     */
    players: Array<MapRenderPlayer>;
}

/**
 * Check if a given object implements the MapRenderRequest interface.
 */
export function instanceOfMapRenderRequest(value: object): value is MapRenderRequest {
    if (!('mapName' in value) || value['mapName'] === undefined) return false;
    if (!('players' in value) || value['players'] === undefined) return false;
    return true;
}

export function MapRenderRequestFromJSON(json: any): MapRenderRequest {
    return MapRenderRequestFromJSONTyped(json, false);
}

export function MapRenderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapRenderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mapName': json['map_name'],
        'players': ((json['players'] as Array<any>).map(MapRenderPlayerFromJSON)),
    };
}

export function MapRenderRequestToJSON(json: any): MapRenderRequest {
    return MapRenderRequestToJSONTyped(json, false);
}

export function MapRenderRequestToJSONTyped(value?: MapRenderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'map_name': value['mapName'],
        'players': ((value['players'] as Array<any>).map(MapRenderPlayerToJSON)),
    };
}

