/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapUploadItem
 */
export interface MapUploadItem {
    /**
     * 
     * @type {string}
     * @memberof MapUploadItem
     */
    baseName: string;
    /**
     * 
     * @type {string}
     * @memberof MapUploadItem
     */
    image?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MapUploadItem
     */
    playerCount?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof MapUploadItem
     */
    alreadyExists?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MapUploadItem
     */
    saved?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MapUploadItem
     */
    crc?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof MapUploadItem
     */
    pushedToCncstats?: boolean;
}

/**
 * Check if a given object implements the MapUploadItem interface.
 */
export function instanceOfMapUploadItem(value: object): value is MapUploadItem {
    if (!('baseName' in value) || value['baseName'] === undefined) return false;
    return true;
}

export function MapUploadItemFromJSON(json: any): MapUploadItem {
    return MapUploadItemFromJSONTyped(json, false);
}

export function MapUploadItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapUploadItem {
    if (json == null) {
        return json;
    }
    return {
        
        'baseName': json['base_name'],
        'image': json['image'] == null ? undefined : json['image'],
        'playerCount': json['player_count'] == null ? undefined : json['player_count'],
        'alreadyExists': json['already_exists'] == null ? undefined : json['already_exists'],
        'saved': json['saved'] == null ? undefined : json['saved'],
        'crc': json['crc'] == null ? undefined : json['crc'],
        'pushedToCncstats': json['pushed_to_cncstats'] == null ? undefined : json['pushed_to_cncstats'],
    };
}

export function MapUploadItemToJSON(json: any): MapUploadItem {
    return MapUploadItemToJSONTyped(json, false);
}

export function MapUploadItemToJSONTyped(value?: MapUploadItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base_name': value['baseName'],
        'image': value['image'],
        'player_count': value['playerCount'],
        'already_exists': value['alreadyExists'],
        'saved': value['saved'],
        'crc': value['crc'],
        'pushed_to_cncstats': value['pushedToCncstats'],
    };
}

