/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapVoteOption
 */
export interface MapVoteOption {
    /**
     * 
     * @type {string}
     * @memberof MapVoteOption
     */
    mapName: string;
    /**
     * 
     * @type {number}
     * @memberof MapVoteOption
     */
    gameCount: number;
    /**
     * 
     * @type {Date}
     * @memberof MapVoteOption
     */
    lastPlayed?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof MapVoteOption
     */
    daysSinceLastPlayed?: number | null;
    /**
     * 
     * @type {MapVoteOptionMyChoiceEnum}
     * @memberof MapVoteOption
     */
    myChoice?: MapVoteOptionMyChoiceEnum | null;
}


/**
 * @export
 */
export const MapVoteOptionMyChoiceEnum = {
    Vote: 'vote',
    Veto: 'veto'
} as const;
export type MapVoteOptionMyChoiceEnum = typeof MapVoteOptionMyChoiceEnum[keyof typeof MapVoteOptionMyChoiceEnum];


/**
 * Check if a given object implements the MapVoteOption interface.
 */
export function instanceOfMapVoteOption(value: object): value is MapVoteOption {
    if (!('mapName' in value) || value['mapName'] === undefined) return false;
    if (!('gameCount' in value) || value['gameCount'] === undefined) return false;
    return true;
}

export function MapVoteOptionFromJSON(json: any): MapVoteOption {
    return MapVoteOptionFromJSONTyped(json, false);
}

export function MapVoteOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapVoteOption {
    if (json == null) {
        return json;
    }
    return {
        
        'mapName': json['map_name'],
        'gameCount': json['game_count'],
        'lastPlayed': json['last_played'] == null ? undefined : (new Date(json['last_played'])),
        'daysSinceLastPlayed': json['days_since_last_played'] == null ? undefined : json['days_since_last_played'],
        'myChoice': json['my_choice'] == null ? undefined : json['my_choice'],
    };
}

export function MapVoteOptionToJSON(json: any): MapVoteOption {
    return MapVoteOptionToJSONTyped(json, false);
}

export function MapVoteOptionToJSONTyped(value?: MapVoteOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'map_name': value['mapName'],
        'game_count': value['gameCount'],
        'last_played': value['lastPlayed'] == null ? value['lastPlayed'] : value['lastPlayed'].toISOString(),
        'days_since_last_played': value['daysSinceLastPlayed'],
        'my_choice': value['myChoice'],
    };
}

