/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MatchBlurbBackfillNight } from './MatchBlurbBackfillNight';
import {
    MatchBlurbBackfillNightFromJSON,
    MatchBlurbBackfillNightFromJSONTyped,
    MatchBlurbBackfillNightToJSON,
    MatchBlurbBackfillNightToJSONTyped,
} from './MatchBlurbBackfillNight';

/**
 * The result of one blurb backfill run over the last N closed game nights.
 * @export
 * @interface MatchBlurbBackfill
 */
export interface MatchBlurbBackfill {
    /**
     * 
     * @type {number}
     * @memberof MatchBlurbBackfill
     */
    days: number;
    /**
     * 
     * @type {number}
     * @memberof MatchBlurbBackfill
     */
    generated: number;
    /**
     * 
     * @type {number}
     * @memberof MatchBlurbBackfill
     */
    pending: number;
    /**
     * 
     * @type {boolean}
     * @memberof MatchBlurbBackfill
     */
    stopped: boolean;
    /**
     * 
     * @type {Array<MatchBlurbBackfillNight>}
     * @memberof MatchBlurbBackfill
     */
    nights?: Array<MatchBlurbBackfillNight>;
}

/**
 * Check if a given object implements the MatchBlurbBackfill interface.
 */
export function instanceOfMatchBlurbBackfill(value: object): value is MatchBlurbBackfill {
    if (!('days' in value) || value['days'] === undefined) return false;
    if (!('generated' in value) || value['generated'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    if (!('stopped' in value) || value['stopped'] === undefined) return false;
    return true;
}

export function MatchBlurbBackfillFromJSON(json: any): MatchBlurbBackfill {
    return MatchBlurbBackfillFromJSONTyped(json, false);
}

export function MatchBlurbBackfillFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchBlurbBackfill {
    if (json == null) {
        return json;
    }
    return {
        
        'days': json['days'],
        'generated': json['generated'],
        'pending': json['pending'],
        'stopped': json['stopped'],
        'nights': json['nights'] == null ? undefined : ((json['nights'] as Array<any>).map(MatchBlurbBackfillNightFromJSON)),
    };
}

export function MatchBlurbBackfillToJSON(json: any): MatchBlurbBackfill {
    return MatchBlurbBackfillToJSONTyped(json, false);
}

export function MatchBlurbBackfillToJSONTyped(value?: MatchBlurbBackfill | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'days': value['days'],
        'generated': value['generated'],
        'pending': value['pending'],
        'stopped': value['stopped'],
        'nights': value['nights'] == null ? undefined : ((value['nights'] as Array<any>).map(MatchBlurbBackfillNightToJSON)),
    };
}

