/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WinLoss } from './WinLoss';
import {
    WinLossFromJSON,
    WinLossFromJSONTyped,
    WinLossToJSON,
    WinLossToJSONTyped,
} from './WinLoss';
import type { MatchInfoOutput } from './MatchInfoOutput';
import {
    MatchInfoOutputFromJSON,
    MatchInfoOutputFromJSONTyped,
    MatchInfoOutputToJSON,
    MatchInfoOutputToJSONTyped,
} from './MatchInfoOutput';

/**
 * 
 * @export
 * @interface MatchupResultOutput
 */
export interface MatchupResultOutput {
    /**
     * 
     * @type {string}
     * @memberof MatchupResultOutput
     */
    tournamentName: string;
    /**
     * 
     * @type {Array<MatchInfoOutput>}
     * @memberof MatchupResultOutput
     */
    matches: Array<MatchInfoOutput>;
    /**
     * 
     * @type {{ [key: string]: WinLoss; }}
     * @memberof MatchupResultOutput
     */
    outcome: { [key: string]: WinLoss; };
    /**
     * 
     * @type {string}
     * @memberof MatchupResultOutput
     */
    override?: string | null;
}

/**
 * Check if a given object implements the MatchupResultOutput interface.
 */
export function instanceOfMatchupResultOutput(value: object): value is MatchupResultOutput {
    if (!('tournamentName' in value) || value['tournamentName'] === undefined) return false;
    if (!('matches' in value) || value['matches'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    return true;
}

export function MatchupResultOutputFromJSON(json: any): MatchupResultOutput {
    return MatchupResultOutputFromJSONTyped(json, false);
}

export function MatchupResultOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchupResultOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'tournamentName': json['tournament_name'],
        'matches': ((json['matches'] as Array<any>).map(MatchInfoOutputFromJSON)),
        'outcome': (mapValues(json['outcome'], WinLossFromJSON)),
        'override': json['override'] == null ? undefined : json['override'],
    };
}

export function MatchupResultOutputToJSON(json: any): MatchupResultOutput {
    return MatchupResultOutputToJSONTyped(json, false);
}

export function MatchupResultOutputToJSONTyped(value?: MatchupResultOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tournament_name': value['tournamentName'],
        'matches': ((value['matches'] as Array<any>).map(MatchInfoOutputToJSON)),
        'outcome': (mapValues(value['outcome'], WinLossToJSON)),
        'override': value['override'],
    };
}

