/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NarrativeBeat } from './NarrativeBeat';
import {
    NarrativeBeatFromJSON,
    NarrativeBeatFromJSONTyped,
    NarrativeBeatToJSON,
    NarrativeBeatToJSONTyped,
} from './NarrativeBeat';

/**
 * A match retold as an ordered list of beats.
 * 
 * ``beats`` is empty when the match has no parsed details yet; ``headline``
 * and the match metadata are still populated from the match row, so the UI
 * always has something to show.
 * @export
 * @interface MatchNarrative
 */
export interface MatchNarrative {
    /**
     * 
     * @type {number}
     * @memberof MatchNarrative
     */
    matchId: number;
    /**
     * 
     * @type {string}
     * @memberof MatchNarrative
     */
    headline: string;
    /**
     * 
     * @type {Array<NarrativeBeat>}
     * @memberof MatchNarrative
     */
    beats?: Array<NarrativeBeat>;
    /**
     * 
     * @type {Date}
     * @memberof MatchNarrative
     */
    startedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof MatchNarrative
     */
    durationMinutes?: number;
    /**
     * 
     * @type {string}
     * @memberof MatchNarrative
     */
    tournament?: string | null;
}

/**
 * Check if a given object implements the MatchNarrative interface.
 */
export function instanceOfMatchNarrative(value: object): value is MatchNarrative {
    if (!('matchId' in value) || value['matchId'] === undefined) return false;
    if (!('headline' in value) || value['headline'] === undefined) return false;
    return true;
}

export function MatchNarrativeFromJSON(json: any): MatchNarrative {
    return MatchNarrativeFromJSONTyped(json, false);
}

export function MatchNarrativeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchNarrative {
    if (json == null) {
        return json;
    }
    return {
        
        'matchId': json['matchId'],
        'headline': json['headline'],
        'beats': json['beats'] == null ? undefined : ((json['beats'] as Array<any>).map(NarrativeBeatFromJSON)),
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'durationMinutes': json['durationMinutes'] == null ? undefined : json['durationMinutes'],
        'tournament': json['tournament'] == null ? undefined : json['tournament'],
    };
}

export function MatchNarrativeToJSON(json: any): MatchNarrative {
    return MatchNarrativeToJSONTyped(json, false);
}

export function MatchNarrativeToJSONTyped(value?: MatchNarrative | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'matchId': value['matchId'],
        'headline': value['headline'],
        'beats': value['beats'] == null ? undefined : ((value['beats'] as Array<any>).map(NarrativeBeatToJSON)),
        'startedAt': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'durationMinutes': value['durationMinutes'],
        'tournament': value['tournament'],
    };
}

