/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WinLoss } from './WinLoss';
import {
    WinLossFromJSON,
    WinLossFromJSONTyped,
    WinLossToJSON,
    WinLossToJSONTyped,
} from './WinLoss';
import type { MatchInfo } from './MatchInfo';
import {
    MatchInfoFromJSON,
    MatchInfoFromJSONTyped,
    MatchInfoToJSON,
    MatchInfoToJSONTyped,
} from './MatchInfo';

/**
 * 
 * @export
 * @interface MatchupResult
 */
export interface MatchupResult {
    /**
     * 
     * @type {string}
     * @memberof MatchupResult
     */
    tournamentName: string;
    /**
     * 
     * @type {Array<MatchInfo>}
     * @memberof MatchupResult
     */
    matches: Array<MatchInfo>;
    /**
     * 
     * @type {{ [key: string]: WinLoss; }}
     * @memberof MatchupResult
     */
    outcome: { [key: string]: WinLoss; };
    /**
     * 
     * @type {string}
     * @memberof MatchupResult
     */
    override?: string | null;
}

/**
 * Check if a given object implements the MatchupResult interface.
 */
export function instanceOfMatchupResult(value: object): value is MatchupResult {
    if (!('tournamentName' in value) || value['tournamentName'] === undefined) return false;
    if (!('matches' in value) || value['matches'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    return true;
}

export function MatchupResultFromJSON(json: any): MatchupResult {
    return MatchupResultFromJSONTyped(json, false);
}

export function MatchupResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchupResult {
    if (json == null) {
        return json;
    }
    return {
        
        'tournamentName': json['tournament_name'],
        'matches': ((json['matches'] as Array<any>).map(MatchInfoFromJSON)),
        'outcome': (mapValues(json['outcome'], WinLossFromJSON)),
        'override': json['override'] == null ? undefined : json['override'],
    };
}

export function MatchupResultToJSON(json: any): MatchupResult {
    return MatchupResultToJSONTyped(json, false);
}

export function MatchupResultToJSONTyped(value?: MatchupResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tournament_name': value['tournamentName'],
        'matches': ((value['matches'] as Array<any>).map(MatchInfoToJSON)),
        'outcome': (mapValues(value['outcome'], WinLossToJSON)),
        'override': value['override'],
    };
}

