/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerPowers } from './PlayerPowers';
import {
    PlayerPowersFromJSON,
    PlayerPowersFromJSONTyped,
    PlayerPowersToJSON,
    PlayerPowersToJSONTyped,
} from './PlayerPowers';

/**
 * Per-player generals-power picks and activations for one match.
 * @export
 * @interface MatchPowers
 */
export interface MatchPowers {
    /**
     * 
     * @type {Array<PlayerPowers>}
     * @memberof MatchPowers
     */
    players?: Array<PlayerPowers>;
}

/**
 * Check if a given object implements the MatchPowers interface.
 */
export function instanceOfMatchPowers(value: object): value is MatchPowers {
    return true;
}

export function MatchPowersFromJSON(json: any): MatchPowers {
    return MatchPowersFromJSONTyped(json, false);
}

export function MatchPowersFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchPowers {
    if (json == null) {
        return json;
    }
    return {
        
        'players': json['players'] == null ? undefined : ((json['players'] as Array<any>).map(PlayerPowersFromJSON)),
    };
}

export function MatchPowersToJSON(json: any): MatchPowers {
    return MatchPowersToJSONTyped(json, false);
}

export function MatchPowersToJSONTyped(value?: MatchPowers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'players': value['players'] == null ? undefined : ((value['players'] as Array<any>).map(PlayerPowersToJSON)),
    };
}

