/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * What the blurb backfill did about one night: its picks, what it wrote, what is left.
 * @export
 * @interface MatchBlurbBackfillNight
 */
export interface MatchBlurbBackfillNight {
    /**
     * 
     * @type {Date}
     * @memberof MatchBlurbBackfillNight
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof MatchBlurbBackfillNight
     */
    picked: number;
    /**
     * 
     * @type {number}
     * @memberof MatchBlurbBackfillNight
     */
    generated: number;
    /**
     * 
     * @type {number}
     * @memberof MatchBlurbBackfillNight
     */
    pending: number;
}

/**
 * Check if a given object implements the MatchBlurbBackfillNight interface.
 */
export function instanceOfMatchBlurbBackfillNight(value: object): value is MatchBlurbBackfillNight {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('picked' in value) || value['picked'] === undefined) return false;
    if (!('generated' in value) || value['generated'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    return true;
}

export function MatchBlurbBackfillNightFromJSON(json: any): MatchBlurbBackfillNight {
    return MatchBlurbBackfillNightFromJSONTyped(json, false);
}

export function MatchBlurbBackfillNightFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchBlurbBackfillNight {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'picked': json['picked'],
        'generated': json['generated'],
        'pending': json['pending'],
    };
}

export function MatchBlurbBackfillNightToJSON(json: any): MatchBlurbBackfillNight {
    return MatchBlurbBackfillNightToJSONTyped(json, false);
}

export function MatchBlurbBackfillNightToJSONTyped(value?: MatchBlurbBackfillNight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'].toISOString().substring(0,10),
        'picked': value['picked'],
        'generated': value['generated'],
        'pending': value['pending'],
    };
}

