/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchupCommentaryRequest
 */
export interface MatchupCommentaryRequest {
    /**
     * 
     * @type {string}
     * @memberof MatchupCommentaryRequest
     */
    player1: string;
    /**
     * 
     * @type {string}
     * @memberof MatchupCommentaryRequest
     */
    player2: string;
    /**
     * 
     * @type {string}
     * @memberof MatchupCommentaryRequest
     */
    roundName: string;
}

/**
 * Check if a given object implements the MatchupCommentaryRequest interface.
 */
export function instanceOfMatchupCommentaryRequest(value: object): value is MatchupCommentaryRequest {
    if (!('player1' in value) || value['player1'] === undefined) return false;
    if (!('player2' in value) || value['player2'] === undefined) return false;
    if (!('roundName' in value) || value['roundName'] === undefined) return false;
    return true;
}

export function MatchupCommentaryRequestFromJSON(json: any): MatchupCommentaryRequest {
    return MatchupCommentaryRequestFromJSONTyped(json, false);
}

export function MatchupCommentaryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchupCommentaryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'player1': json['player1'],
        'player2': json['player2'],
        'roundName': json['round_name'],
    };
}

export function MatchupCommentaryRequestToJSON(json: any): MatchupCommentaryRequest {
    return MatchupCommentaryRequestToJSONTyped(json, false);
}

export function MatchupCommentaryRequestToJSONTyped(value?: MatchupCommentaryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player1': value['player1'],
        'player2': value['player2'],
        'round_name': value['roundName'],
    };
}

