/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * What one night's match-blurb run picked and wrote.
 * @export
 * @interface MatchBlurbRun
 */
export interface MatchBlurbRun {
    /**
     * 
     * @type {Date}
     * @memberof MatchBlurbRun
     */
    date: Date;
    /**
     * 
     * @type {Array<number>}
     * @memberof MatchBlurbRun
     */
    picked: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof MatchBlurbRun
     */
    generated: Array<number>;
}

/**
 * Check if a given object implements the MatchBlurbRun interface.
 */
export function instanceOfMatchBlurbRun(value: object): value is MatchBlurbRun {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('picked' in value) || value['picked'] === undefined) return false;
    if (!('generated' in value) || value['generated'] === undefined) return false;
    return true;
}

export function MatchBlurbRunFromJSON(json: any): MatchBlurbRun {
    return MatchBlurbRunFromJSONTyped(json, false);
}

export function MatchBlurbRunFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchBlurbRun {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'picked': json['picked'],
        'generated': json['generated'],
    };
}

export function MatchBlurbRunToJSON(json: any): MatchBlurbRun {
    return MatchBlurbRunToJSONTyped(json, false);
}

export function MatchBlurbRunToJSONTyped(value?: MatchBlurbRun | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'].toISOString().substring(0,10),
        'picked': value['picked'],
        'generated': value['generated'],
    };
}

