/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Costs } from './Costs';
import {
    CostsFromJSON,
    CostsFromJSONTyped,
    CostsToJSON,
    CostsToJSONTyped,
} from './Costs';
import type { PlayerSummary } from './PlayerSummary';
import {
    PlayerSummaryFromJSON,
    PlayerSummaryFromJSONTyped,
    PlayerSummaryToJSON,
    PlayerSummaryToJSONTyped,
} from './PlayerSummary';
import type { Upgrades } from './Upgrades';
import {
    UpgradesFromJSON,
    UpgradesFromJSONTyped,
    UpgradesToJSON,
    UpgradesToJSONTyped,
} from './Upgrades';
import type { FirstBlood } from './FirstBlood';
import {
    FirstBloodFromJSON,
    FirstBloodFromJSONTyped,
    FirstBloodToJSON,
    FirstBloodToJSONTyped,
} from './FirstBlood';
import type { KillEventOutput } from './KillEventOutput';
import {
    KillEventOutputFromJSON,
    KillEventOutputFromJSONTyped,
    KillEventOutputToJSON,
    KillEventOutputToJSONTyped,
} from './KillEventOutput';
import type { APM } from './APM';
import {
    APMFromJSON,
    APMFromJSONTyped,
    APMToJSON,
    APMToJSONTyped,
} from './APM';

/**
 * 
 * @export
 * @interface MatchDetails
 */
export interface MatchDetails {
    /**
     * 
     * @type {number}
     * @memberof MatchDetails
     */
    matchId: number;
    /**
     * 
     * @type {string}
     * @memberof MatchDetails
     */
    gameVersion?: string | null;
    /**
     * 
     * @type {Array<Costs>}
     * @memberof MatchDetails
     */
    costs: Array<Costs>;
    /**
     * 
     * @type {Array<APM>}
     * @memberof MatchDetails
     */
    apms: Array<APM>;
    /**
     * 
     * @type {{ [key: string]: Upgrades; }}
     * @memberof MatchDetails
     */
    upgradeEvents: { [key: string]: Upgrades; };
    /**
     * at a time map each player to xp
     * @type {{ [key: string]: { [key: string]: { [key: string]: number; }; }; }}
     * @memberof MatchDetails
     */
    statsData: { [key: string]: { [key: string]: { [key: string]: number; }; }; };
    /**
     * 
     * @type {string}
     * @memberof MatchDetails
     */
    mapName?: string;
    /**
     * 
     * @type {FirstBlood}
     * @memberof MatchDetails
     */
    firstBlood?: FirstBlood | null;
    /**
     * 
     * @type {FirstBlood}
     * @memberof MatchDetails
     */
    buildingFirstBlood?: FirstBlood | null;
    /**
     * 
     * @type {Array<PlayerSummary>}
     * @memberof MatchDetails
     */
    playerSummary: Array<PlayerSummary>;
    /**
     * 
     * @type {Array<KillEventOutput>}
     * @memberof MatchDetails
     */
    killEvents?: Array<KillEventOutput>;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof MatchDetails
     */
    playerMoneySpent?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof MatchDetails
     */
    playerMoneyCollected?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof MatchDetails
     */
    timeToRank5?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof MatchDetails
     */
    timeToSearchDestroy?: { [key: string]: number; };
}

/**
 * Check if a given object implements the MatchDetails interface.
 */
export function instanceOfMatchDetails(value: object): value is MatchDetails {
    if (!('matchId' in value) || value['matchId'] === undefined) return false;
    if (!('costs' in value) || value['costs'] === undefined) return false;
    if (!('apms' in value) || value['apms'] === undefined) return false;
    if (!('upgradeEvents' in value) || value['upgradeEvents'] === undefined) return false;
    if (!('statsData' in value) || value['statsData'] === undefined) return false;
    if (!('playerSummary' in value) || value['playerSummary'] === undefined) return false;
    return true;
}

export function MatchDetailsFromJSON(json: any): MatchDetails {
    return MatchDetailsFromJSONTyped(json, false);
}

export function MatchDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'matchId': json['matchId'],
        'gameVersion': json['game_version'] == null ? undefined : json['game_version'],
        'costs': ((json['costs'] as Array<any>).map(CostsFromJSON)),
        'apms': ((json['apms'] as Array<any>).map(APMFromJSON)),
        'upgradeEvents': (mapValues(json['upgradeEvents'], UpgradesFromJSON)),
        'statsData': json['stats_data'],
        'mapName': json['mapName'] == null ? undefined : json['mapName'],
        'firstBlood': json['first_blood'] == null ? undefined : FirstBloodFromJSON(json['first_blood']),
        'buildingFirstBlood': json['building_first_blood'] == null ? undefined : FirstBloodFromJSON(json['building_first_blood']),
        'playerSummary': ((json['player_summary'] as Array<any>).map(PlayerSummaryFromJSON)),
        'killEvents': json['killEvents'] == null ? undefined : ((json['killEvents'] as Array<any>).map(KillEventOutputFromJSON)),
        'playerMoneySpent': json['player_money_spent'] == null ? undefined : json['player_money_spent'],
        'playerMoneyCollected': json['player_money_collected'] == null ? undefined : json['player_money_collected'],
        'timeToRank5': json['timeToRank5'] == null ? undefined : json['timeToRank5'],
        'timeToSearchDestroy': json['timeToSearchDestroy'] == null ? undefined : json['timeToSearchDestroy'],
    };
}

export function MatchDetailsToJSON(json: any): MatchDetails {
    return MatchDetailsToJSONTyped(json, false);
}

export function MatchDetailsToJSONTyped(value?: MatchDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'matchId': value['matchId'],
        'game_version': value['gameVersion'],
        'costs': ((value['costs'] as Array<any>).map(CostsToJSON)),
        'apms': ((value['apms'] as Array<any>).map(APMToJSON)),
        'upgradeEvents': (mapValues(value['upgradeEvents'], UpgradesToJSON)),
        'stats_data': value['statsData'],
        'mapName': value['mapName'],
        'first_blood': FirstBloodToJSON(value['firstBlood']),
        'building_first_blood': FirstBloodToJSON(value['buildingFirstBlood']),
        'player_summary': ((value['playerSummary'] as Array<any>).map(PlayerSummaryToJSON)),
        'killEvents': value['killEvents'] == null ? undefined : ((value['killEvents'] as Array<any>).map(KillEventOutputToJSON)),
        'player_money_spent': value['playerMoneySpent'],
        'player_money_collected': value['playerMoneyCollected'],
        'timeToRank5': value['timeToRank5'],
        'timeToSearchDestroy': value['timeToSearchDestroy'],
    };
}

