/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One sentence of the story, optionally pinned to a minute.
 * 
 * ``kind`` groups beats for styling and is one of: "setup" (map, format,
 * lineup - no minute), "first_blood", "milestone" (rank 5, search &
 * destroy), "superweapon", "collapse" (went hunted, lost power), "economy",
 * "damage", "tempo" (APM), "result". The frontend maps it to an icon; an
 * unknown kind must render as a plain bullet rather than break the list.
 * @export
 * @interface NarrativeBeat
 */
export interface NarrativeBeat {
    /**
     * 
     * @type {string}
     * @memberof NarrativeBeat
     */
    kind: string;
    /**
     * 
     * @type {string}
     * @memberof NarrativeBeat
     */
    text: string;
    /**
     * 
     * @type {number}
     * @memberof NarrativeBeat
     */
    atMinute?: number | null;
    /**
     * 
     * @type {string}
     * @memberof NarrativeBeat
     */
    playerName?: string | null;
}

/**
 * Check if a given object implements the NarrativeBeat interface.
 */
export function instanceOfNarrativeBeat(value: object): value is NarrativeBeat {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function NarrativeBeatFromJSON(json: any): NarrativeBeat {
    return NarrativeBeatFromJSONTyped(json, false);
}

export function NarrativeBeatFromJSONTyped(json: any, ignoreDiscriminator: boolean): NarrativeBeat {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'text': json['text'],
        'atMinute': json['atMinute'] == null ? undefined : json['atMinute'],
        'playerName': json['playerName'] == null ? undefined : json['playerName'],
    };
}

export function NarrativeBeatToJSON(json: any): NarrativeBeat {
    return NarrativeBeatToJSONTyped(json, false);
}

export function NarrativeBeatToJSONTyped(value?: NarrativeBeat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'text': value['text'],
        'atMinute': value['atMinute'],
        'playerName': value['playerName'],
    };
}

