/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectSummary
 */
export interface ObjectSummary {
    /**
     * 
     * @type {number}
     * @memberof ObjectSummary
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectSummary
     */
    totalSpent: number;
}

/**
 * Check if a given object implements the ObjectSummary interface.
 */
export function instanceOfObjectSummary(value: object): value is ObjectSummary {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('totalSpent' in value) || value['totalSpent'] === undefined) return false;
    return true;
}

export function ObjectSummaryFromJSON(json: any): ObjectSummary {
    return ObjectSummaryFromJSONTyped(json, false);
}

export function ObjectSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['Count'],
        'totalSpent': json['TotalSpent'],
    };
}

export function ObjectSummaryToJSON(json: any): ObjectSummary {
    return ObjectSummaryToJSONTyped(json, false);
}

export function ObjectSummaryToJSONTyped(value?: ObjectSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Count': value['count'],
        'TotalSpent': value['totalSpent'],
    };
}

