/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Public API representation of ParsedReplayJson
 * @export
 * @interface ParsedReplayJsonSchema
 */
export interface ParsedReplayJsonSchema {
    /**
     * 
     * @type {string}
     * @memberof ParsedReplayJsonSchema
     */
    jsonS3Uri: string;
    /**
     * 
     * @type {number}
     * @memberof ParsedReplayJsonSchema
     */
    matchId: number;
    /**
     * 
     * @type {string}
     * @memberof ParsedReplayJsonSchema
     */
    replayFileUrl: string;
    /**
     * 
     * @type {number}
     * @memberof ParsedReplayJsonSchema
     */
    numTimeStamps?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ParsedReplayJsonSchema
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ParsedReplayJsonSchema
     */
    gameTimestamp: Date;
    /**
     * 
     * @type {Date}
     * @memberof ParsedReplayJsonSchema
     */
    gameDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof ParsedReplayJsonSchema
     */
    updatedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ParsedReplayJsonSchema
     */
    hasEnhancedStats?: boolean | null;
}

/**
 * Check if a given object implements the ParsedReplayJsonSchema interface.
 */
export function instanceOfParsedReplayJsonSchema(value: object): value is ParsedReplayJsonSchema {
    if (!('jsonS3Uri' in value) || value['jsonS3Uri'] === undefined) return false;
    if (!('matchId' in value) || value['matchId'] === undefined) return false;
    if (!('replayFileUrl' in value) || value['replayFileUrl'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('gameTimestamp' in value) || value['gameTimestamp'] === undefined) return false;
    if (!('gameDate' in value) || value['gameDate'] === undefined) return false;
    return true;
}

export function ParsedReplayJsonSchemaFromJSON(json: any): ParsedReplayJsonSchema {
    return ParsedReplayJsonSchemaFromJSONTyped(json, false);
}

export function ParsedReplayJsonSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParsedReplayJsonSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonS3Uri': json['json_s3_uri'],
        'matchId': json['match_id'],
        'replayFileUrl': json['replay_file_url'],
        'numTimeStamps': json['num_time_stamps'] == null ? undefined : json['num_time_stamps'],
        'createdAt': (new Date(json['created_at'])),
        'gameTimestamp': (new Date(json['game_timestamp'])),
        'gameDate': (new Date(json['game_date'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'hasEnhancedStats': json['has_enhanced_stats'] == null ? undefined : json['has_enhanced_stats'],
    };
}

export function ParsedReplayJsonSchemaToJSON(json: any): ParsedReplayJsonSchema {
    return ParsedReplayJsonSchemaToJSONTyped(json, false);
}

export function ParsedReplayJsonSchemaToJSONTyped(value?: ParsedReplayJsonSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'json_s3_uri': value['jsonS3Uri'],
        'match_id': value['matchId'],
        'replay_file_url': value['replayFileUrl'],
        'num_time_stamps': value['numTimeStamps'],
        'created_at': value['createdAt'].toISOString(),
        'game_timestamp': value['gameTimestamp'].toISOString(),
        'game_date': value['gameDate'].toISOString().substring(0,10),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'has_enhanced_stats': value['hasEnhancedStats'],
    };
}

