/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PowerUse } from './PowerUse';
import {
    PowerUseFromJSON,
    PowerUseFromJSONTyped,
    PowerUseToJSON,
    PowerUseToJSONTyped,
} from './PowerUse';
import type { PowerPick } from './PowerPick';
import {
    PowerPickFromJSON,
    PowerPickFromJSONTyped,
    PowerPickToJSON,
    PowerPickToJSONTyped,
} from './PowerPick';
import type { General } from './General';
import {
    GeneralFromJSON,
    GeneralFromJSONTyped,
    GeneralToJSON,
    GeneralToJSONTyped,
} from './General';

/**
 * One player's powers in one match: what they bought and what they fired.
 * @export
 * @interface PlayerPowers
 */
export interface PlayerPowers {
    /**
     * 
     * @type {string}
     * @memberof PlayerPowers
     */
    playerName: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerPowers
     */
    faction: string;
    /**
     * 
     * @type {General}
     * @memberof PlayerPowers
     */
    general: General;
    /**
     * 
     * @type {number}
     * @memberof PlayerPowers
     */
    minutes: number;
    /**
     * 
     * @type {Array<PowerPick>}
     * @memberof PlayerPowers
     */
    picks?: Array<PowerPick>;
    /**
     * 
     * @type {Array<PowerUse>}
     * @memberof PlayerPowers
     */
    uses?: Array<PowerUse>;
}



/**
 * Check if a given object implements the PlayerPowers interface.
 */
export function instanceOfPlayerPowers(value: object): value is PlayerPowers {
    if (!('playerName' in value) || value['playerName'] === undefined) return false;
    if (!('faction' in value) || value['faction'] === undefined) return false;
    if (!('general' in value) || value['general'] === undefined) return false;
    if (!('minutes' in value) || value['minutes'] === undefined) return false;
    return true;
}

export function PlayerPowersFromJSON(json: any): PlayerPowers {
    return PlayerPowersFromJSONTyped(json, false);
}

export function PlayerPowersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerPowers {
    if (json == null) {
        return json;
    }
    return {
        
        'playerName': json['playerName'],
        'faction': json['faction'],
        'general': GeneralFromJSON(json['general']),
        'minutes': json['minutes'],
        'picks': json['picks'] == null ? undefined : ((json['picks'] as Array<any>).map(PowerPickFromJSON)),
        'uses': json['uses'] == null ? undefined : ((json['uses'] as Array<any>).map(PowerUseFromJSON)),
    };
}

export function PlayerPowersToJSON(json: any): PlayerPowers {
    return PlayerPowersToJSONTyped(json, false);
}

export function PlayerPowersToJSONTyped(value?: PlayerPowers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerName': value['playerName'],
        'faction': value['faction'],
        'general': GeneralToJSON(value['general']),
        'minutes': value['minutes'],
        'picks': value['picks'] == null ? undefined : ((value['picks'] as Array<any>).map(PowerPickToJSON)),
        'uses': value['uses'] == null ? undefined : ((value['uses'] as Array<any>).map(PowerUseToJSON)),
    };
}

