/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WinLoss } from './WinLoss';
import {
    WinLossFromJSON,
    WinLossFromJSONTyped,
    WinLossToJSON,
    WinLossToJSONTyped,
} from './WinLoss';
import type { PlayerStatFactionWL } from './PlayerStatFactionWL';
import {
    PlayerStatFactionWLFromJSON,
    PlayerStatFactionWLFromJSONTyped,
    PlayerStatFactionWLToJSON,
    PlayerStatFactionWLToJSONTyped,
} from './PlayerStatFactionWL';
import type { PlayerRateOverTime } from './PlayerRateOverTime';
import {
    PlayerRateOverTimeFromJSON,
    PlayerRateOverTimeFromJSONTyped,
    PlayerRateOverTimeToJSON,
    PlayerRateOverTimeToJSONTyped,
} from './PlayerRateOverTime';

/**
 * 
 * @export
 * @interface PlayerStat
 */
export interface PlayerStat {
    /**
     * 
     * @type {string}
     * @memberof PlayerStat
     */
    playerName: string;
    /**
     * 
     * @type {{ [key: string]: WinLoss; }}
     * @memberof PlayerStat
     */
    stats: { [key: string]: WinLoss; };
    /**
     * 
     * @type {Array<PlayerStatFactionWL>}
     * @memberof PlayerStat
     */
    factionStats: Array<PlayerStatFactionWL>;
    /**
     * 
     * @type {Array<PlayerRateOverTime>}
     * @memberof PlayerStat
     */
    overTime: Array<PlayerRateOverTime>;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof PlayerStat
     */
    gameCounts?: { [key: string]: number; };
}

/**
 * Check if a given object implements the PlayerStat interface.
 */
export function instanceOfPlayerStat(value: object): value is PlayerStat {
    if (!('playerName' in value) || value['playerName'] === undefined) return false;
    if (!('stats' in value) || value['stats'] === undefined) return false;
    if (!('factionStats' in value) || value['factionStats'] === undefined) return false;
    if (!('overTime' in value) || value['overTime'] === undefined) return false;
    return true;
}

export function PlayerStatFromJSON(json: any): PlayerStat {
    return PlayerStatFromJSONTyped(json, false);
}

export function PlayerStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerStat {
    if (json == null) {
        return json;
    }
    return {
        
        'playerName': json['playerName'],
        'stats': (mapValues(json['stats'], WinLossFromJSON)),
        'factionStats': ((json['factionStats'] as Array<any>).map(PlayerStatFactionWLFromJSON)),
        'overTime': ((json['overTime'] as Array<any>).map(PlayerRateOverTimeFromJSON)),
        'gameCounts': json['gameCounts'] == null ? undefined : json['gameCounts'],
    };
}

export function PlayerStatToJSON(json: any): PlayerStat {
    return PlayerStatToJSONTyped(json, false);
}

export function PlayerStatToJSONTyped(value?: PlayerStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerName': value['playerName'],
        'stats': (mapValues(value['stats'], WinLossToJSON)),
        'factionStats': ((value['factionStats'] as Array<any>).map(PlayerStatFactionWLToJSON)),
        'overTime': ((value['overTime'] as Array<any>).map(PlayerRateOverTimeToJSON)),
        'gameCounts': value['gameCounts'],
    };
}

