/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShortPlayerRating } from './ShortPlayerRating';
import {
    ShortPlayerRatingFromJSON,
    ShortPlayerRatingFromJSONTyped,
    ShortPlayerRatingToJSON,
    ShortPlayerRatingToJSONTyped,
} from './ShortPlayerRating';
import type { PlayerRatings } from './PlayerRatings';
import {
    PlayerRatingsFromJSON,
    PlayerRatingsFromJSONTyped,
    PlayerRatingsToJSON,
    PlayerRatingsToJSONTyped,
} from './PlayerRatings';

/**
 * 
 * @export
 * @interface PlayerRatingData
 */
export interface PlayerRatingData {
    /**
     * 
     * @type {Array<PlayerRatings>}
     * @memberof PlayerRatingData
     */
    playerRating: Array<PlayerRatings>;
    /**
     * 
     * @type {{ [key: string]: Array<ShortPlayerRating>; }}
     * @memberof PlayerRatingData
     */
    playerRatingOvertime?: { [key: string]: Array<ShortPlayerRating>; };
    /**
     * 
     * @type {{ [key: string]: Array<boolean>; }}
     * @memberof PlayerRatingData
     */
    playerForm?: { [key: string]: Array<boolean>; };
}

/**
 * Check if a given object implements the PlayerRatingData interface.
 */
export function instanceOfPlayerRatingData(value: object): value is PlayerRatingData {
    if (!('playerRating' in value) || value['playerRating'] === undefined) return false;
    return true;
}

export function PlayerRatingDataFromJSON(json: any): PlayerRatingData {
    return PlayerRatingDataFromJSONTyped(json, false);
}

export function PlayerRatingDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerRatingData {
    if (json == null) {
        return json;
    }
    return {
        
        'playerRating': ((json['player_rating'] as Array<any>).map(PlayerRatingsFromJSON)),
        'playerRatingOvertime': json['player_rating_overtime'] == null ? undefined : json['player_rating_overtime'],
        'playerForm': json['player_form'] == null ? undefined : json['player_form'],
    };
}

export function PlayerRatingDataToJSON(json: any): PlayerRatingData {
    return PlayerRatingDataToJSONTyped(json, false);
}

export function PlayerRatingDataToJSONTyped(value?: PlayerRatingData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player_rating': ((value['playerRating'] as Array<any>).map(PlayerRatingsToJSON)),
        'player_rating_overtime': value['playerRatingOvertime'],
        'player_form': value['playerForm'],
    };
}

