/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneralWL } from './GeneralWL';
import {
    GeneralWLFromJSON,
    GeneralWLFromJSONTyped,
    GeneralWLToJSON,
    GeneralWLToJSONTyped,
} from './GeneralWL';
import type { DateMessage } from './DateMessage';
import {
    DateMessageFromJSON,
    DateMessageFromJSONTyped,
    DateMessageToJSON,
    DateMessageToJSONTyped,
} from './DateMessage';

/**
 * 
 * @export
 * @interface PlayerRateOverTimeInput
 */
export interface PlayerRateOverTimeInput {
    /**
     * 
     * @type {DateMessage}
     * @memberof PlayerRateOverTimeInput
     */
    date: DateMessage;
    /**
     * 
     * @type {GeneralWL}
     * @memberof PlayerRateOverTimeInput
     */
    wl: GeneralWL;
}

/**
 * Check if a given object implements the PlayerRateOverTimeInput interface.
 */
export function instanceOfPlayerRateOverTimeInput(value: object): value is PlayerRateOverTimeInput {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('wl' in value) || value['wl'] === undefined) return false;
    return true;
}

export function PlayerRateOverTimeInputFromJSON(json: any): PlayerRateOverTimeInput {
    return PlayerRateOverTimeInputFromJSONTyped(json, false);
}

export function PlayerRateOverTimeInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerRateOverTimeInput {
    if (json == null) {
        return json;
    }
    return {
        
        'date': DateMessageFromJSON(json['date']),
        'wl': GeneralWLFromJSON(json['wl']),
    };
}

export function PlayerRateOverTimeInputToJSON(json: any): PlayerRateOverTimeInput {
    return PlayerRateOverTimeInputToJSONTyped(json, false);
}

export function PlayerRateOverTimeInputToJSONTyped(value?: PlayerRateOverTimeInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': DateMessageToJSON(value['date']),
        'wl': GeneralWLToJSON(value['wl']),
    };
}

