/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FavoriteObject } from './FavoriteObject';
import {
    FavoriteObjectFromJSON,
    FavoriteObjectFromJSONTyped,
    FavoriteObjectToJSON,
    FavoriteObjectToJSONTyped,
} from './FavoriteObject';
import type { ObjectUsageStat } from './ObjectUsageStat';
import {
    ObjectUsageStatFromJSON,
    ObjectUsageStatFromJSONTyped,
    ObjectUsageStatToJSON,
    ObjectUsageStatToJSONTyped,
} from './ObjectUsageStat';
import type { ProfileBadge } from './ProfileBadge';
import {
    ProfileBadgeFromJSON,
    ProfileBadgeFromJSONTyped,
    ProfileBadgeToJSON,
    ProfileBadgeToJSONTyped,
} from './ProfileBadge';

/**
 * MatchDetails-derived deep stats for one player.
 * 
 * Computed as a batch across all profiled players (percentiles are relative
 * to that population) and persisted per player; see radarvan.player_profile.
 * @export
 * @interface PlayerProfileComputed
 */
export interface PlayerProfileComputed {
    /**
     * 
     * @type {FavoriteObject}
     * @memberof PlayerProfileComputed
     */
    favoriteUnit?: FavoriteObject | null;
    /**
     * 
     * @type {FavoriteObject}
     * @memberof PlayerProfileComputed
     */
    favoriteBuilding?: FavoriteObject | null;
    /**
     * 
     * @type {FavoriteObject}
     * @memberof PlayerProfileComputed
     */
    favoriteUpgrade?: FavoriteObject | null;
    /**
     * 
     * @type {FavoriteObject}
     * @memberof PlayerProfileComputed
     */
    favoritePower?: FavoriteObject | null;
    /**
     * 
     * @type {Array<FavoriteObject>}
     * @memberof PlayerProfileComputed
     */
    aversions?: Array<FavoriteObject>;
    /**
     * 
     * @type {number}
     * @memberof PlayerProfileComputed
     */
    avgApm?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlayerProfileComputed
     */
    apmPercentile?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlayerProfileComputed
     */
    firstBloodRate?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlayerProfileComputed
     */
    firstBloodPercentile?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlayerProfileComputed
     */
    avgTimeToRank5?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlayerProfileComputed
     */
    rank5Percentile?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlayerProfileComputed
     */
    superweaponsBuiltPerGame?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlayerProfileComputed
     */
    superweaponPercentile?: number | null;
    /**
     * 
     * @type {Array<ProfileBadge>}
     * @memberof PlayerProfileComputed
     */
    badges?: Array<ProfileBadge>;
    /**
     * 
     * @type {Array<ObjectUsageStat>}
     * @memberof PlayerProfileComputed
     */
    objectUsage?: Array<ObjectUsageStat>;
    /**
     * 
     * @type {number}
     * @memberof PlayerProfileComputed
     */
    gamesAnalyzed: number;
    /**
     * 
     * @type {Date}
     * @memberof PlayerProfileComputed
     */
    computedAt: Date;
}

/**
 * Check if a given object implements the PlayerProfileComputed interface.
 */
export function instanceOfPlayerProfileComputed(value: object): value is PlayerProfileComputed {
    if (!('gamesAnalyzed' in value) || value['gamesAnalyzed'] === undefined) return false;
    if (!('computedAt' in value) || value['computedAt'] === undefined) return false;
    return true;
}

export function PlayerProfileComputedFromJSON(json: any): PlayerProfileComputed {
    return PlayerProfileComputedFromJSONTyped(json, false);
}

export function PlayerProfileComputedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerProfileComputed {
    if (json == null) {
        return json;
    }
    return {
        
        'favoriteUnit': json['favoriteUnit'] == null ? undefined : FavoriteObjectFromJSON(json['favoriteUnit']),
        'favoriteBuilding': json['favoriteBuilding'] == null ? undefined : FavoriteObjectFromJSON(json['favoriteBuilding']),
        'favoriteUpgrade': json['favoriteUpgrade'] == null ? undefined : FavoriteObjectFromJSON(json['favoriteUpgrade']),
        'favoritePower': json['favoritePower'] == null ? undefined : FavoriteObjectFromJSON(json['favoritePower']),
        'aversions': json['aversions'] == null ? undefined : ((json['aversions'] as Array<any>).map(FavoriteObjectFromJSON)),
        'avgApm': json['avgApm'] == null ? undefined : json['avgApm'],
        'apmPercentile': json['apmPercentile'] == null ? undefined : json['apmPercentile'],
        'firstBloodRate': json['firstBloodRate'] == null ? undefined : json['firstBloodRate'],
        'firstBloodPercentile': json['firstBloodPercentile'] == null ? undefined : json['firstBloodPercentile'],
        'avgTimeToRank5': json['avgTimeToRank5'] == null ? undefined : json['avgTimeToRank5'],
        'rank5Percentile': json['rank5Percentile'] == null ? undefined : json['rank5Percentile'],
        'superweaponsBuiltPerGame': json['superweaponsBuiltPerGame'] == null ? undefined : json['superweaponsBuiltPerGame'],
        'superweaponPercentile': json['superweaponPercentile'] == null ? undefined : json['superweaponPercentile'],
        'badges': json['badges'] == null ? undefined : ((json['badges'] as Array<any>).map(ProfileBadgeFromJSON)),
        'objectUsage': json['objectUsage'] == null ? undefined : ((json['objectUsage'] as Array<any>).map(ObjectUsageStatFromJSON)),
        'gamesAnalyzed': json['gamesAnalyzed'],
        'computedAt': (new Date(json['computedAt'])),
    };
}

export function PlayerProfileComputedToJSON(json: any): PlayerProfileComputed {
    return PlayerProfileComputedToJSONTyped(json, false);
}

export function PlayerProfileComputedToJSONTyped(value?: PlayerProfileComputed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'favoriteUnit': FavoriteObjectToJSON(value['favoriteUnit']),
        'favoriteBuilding': FavoriteObjectToJSON(value['favoriteBuilding']),
        'favoriteUpgrade': FavoriteObjectToJSON(value['favoriteUpgrade']),
        'favoritePower': FavoriteObjectToJSON(value['favoritePower']),
        'aversions': value['aversions'] == null ? undefined : ((value['aversions'] as Array<any>).map(FavoriteObjectToJSON)),
        'avgApm': value['avgApm'],
        'apmPercentile': value['apmPercentile'],
        'firstBloodRate': value['firstBloodRate'],
        'firstBloodPercentile': value['firstBloodPercentile'],
        'avgTimeToRank5': value['avgTimeToRank5'],
        'rank5Percentile': value['rank5Percentile'],
        'superweaponsBuiltPerGame': value['superweaponsBuiltPerGame'],
        'superweaponPercentile': value['superweaponPercentile'],
        'badges': value['badges'] == null ? undefined : ((value['badges'] as Array<any>).map(ProfileBadgeToJSON)),
        'objectUsage': value['objectUsage'] == null ? undefined : ((value['objectUsage'] as Array<any>).map(ObjectUsageStatToJSON)),
        'gamesAnalyzed': value['gamesAnalyzed'],
        'computedAt': value['computedAt'].toISOString().substring(0,10),
    };
}

