/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlayerEnum = {
    CoreDawg: 'CoreDawg',
    Syn: 'Syn',
    EasyArmy: 'EasyArmy',
    Stm: 'STM',
    Gorn: 'Gorn',
    HardArmy: 'HardArmy',
    Shifty: 'Shifty',
    MediumArmy: 'MediumArmy',
    WildCard: 'WildCard',
    EnragedFerret: 'EnragedFerret',
    Modus: 'Modus',
    Neo: 'Neo',
    Pancake: 'Pancake',
    OneThree111: 'OneThree111',
    Pcap: 'pcap',
    Skip: 'Skip',
    WilyWolf: 'WilyWolf',
    TacticalAi: 'TacticalAI',
    Tytan: 'Tytan'
} as const;
export type PlayerEnum = typeof PlayerEnum[keyof typeof PlayerEnum];


export function instanceOfPlayerEnum(value: any): boolean {
    for (const key in PlayerEnum) {
        if (Object.prototype.hasOwnProperty.call(PlayerEnum, key)) {
            if (PlayerEnum[key as keyof typeof PlayerEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PlayerEnumFromJSON(json: any): PlayerEnum {
    return PlayerEnumFromJSONTyped(json, false);
}

export function PlayerEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerEnum {
    return json as PlayerEnum;
}

export function PlayerEnumToJSON(value?: PlayerEnum | null): any {
    return value as any;
}

export function PlayerEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PlayerEnum {
    return value as PlayerEnum;
}

