/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerRatings
 */
export interface PlayerRatings {
    /**
     * 
     * @type {string}
     * @memberof PlayerRatings
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PlayerRatings
     */
    ordinal: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerRatings
     */
    mu: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerRatings
     */
    sigma: number;
}

/**
 * Check if a given object implements the PlayerRatings interface.
 */
export function instanceOfPlayerRatings(value: object): value is PlayerRatings {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ordinal' in value) || value['ordinal'] === undefined) return false;
    if (!('mu' in value) || value['mu'] === undefined) return false;
    if (!('sigma' in value) || value['sigma'] === undefined) return false;
    return true;
}

export function PlayerRatingsFromJSON(json: any): PlayerRatings {
    return PlayerRatingsFromJSONTyped(json, false);
}

export function PlayerRatingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerRatings {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ordinal': json['ordinal'],
        'mu': json['mu'],
        'sigma': json['sigma'],
    };
}

export function PlayerRatingsToJSON(json: any): PlayerRatings {
    return PlayerRatingsToJSONTyped(json, false);
}

export function PlayerRatingsToJSONTyped(value?: PlayerRatings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'ordinal': value['ordinal'],
        'mu': value['mu'],
        'sigma': value['sigma'],
    };
}

