/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerSkill
 */
export interface PlayerSkill {
    /**
     * 
     * @type {string}
     * @memberof PlayerSkill
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PlayerSkill
     */
    skill: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerSkill
     */
    gameCount: number;
}

/**
 * Check if a given object implements the PlayerSkill interface.
 */
export function instanceOfPlayerSkill(value: object): value is PlayerSkill {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('skill' in value) || value['skill'] === undefined) return false;
    if (!('gameCount' in value) || value['gameCount'] === undefined) return false;
    return true;
}

export function PlayerSkillFromJSON(json: any): PlayerSkill {
    return PlayerSkillFromJSONTyped(json, false);
}

export function PlayerSkillFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerSkill {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'skill': json['skill'],
        'gameCount': json['game_count'],
    };
}

export function PlayerSkillToJSON(json: any): PlayerSkill {
    return PlayerSkillToJSONTyped(json, false);
}

export function PlayerSkillToJSONTyped(value?: PlayerSkill | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'skill': value['skill'],
        'game_count': value['gameCount'],
    };
}

