/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerStat } from './PlayerStat';
import {
    PlayerStatFromJSON,
    PlayerStatFromJSONTyped,
    PlayerStatToJSON,
    PlayerStatToJSONTyped,
} from './PlayerStat';

/**
 * 
 * @export
 * @interface PlayerStats
 */
export interface PlayerStats {
    /**
     * 
     * @type {Array<PlayerStat>}
     * @memberof PlayerStats
     */
    playerStats: Array<PlayerStat>;
}

/**
 * Check if a given object implements the PlayerStats interface.
 */
export function instanceOfPlayerStats(value: object): value is PlayerStats {
    if (!('playerStats' in value) || value['playerStats'] === undefined) return false;
    return true;
}

export function PlayerStatsFromJSON(json: any): PlayerStats {
    return PlayerStatsFromJSONTyped(json, false);
}

export function PlayerStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerStats {
    if (json == null) {
        return json;
    }
    return {
        
        'playerStats': ((json['playerStats'] as Array<any>).map(PlayerStatFromJSON)),
    };
}

export function PlayerStatsToJSON(json: any): PlayerStats {
    return PlayerStatsToJSONTyped(json, false);
}

export function PlayerStatsToJSONTyped(value?: PlayerStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerStats': ((value['playerStats'] as Array<any>).map(PlayerStatToJSON)),
    };
}

