/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One power, for one player, on one general - against the group baseline.
 * 
 * The baseline is every *other* player on the same general, not the whole
 * group including this player. With a roster this small, leaving someone in
 * their own comparison flattens exactly the signal the row exists to show.
 * @export
 * @interface PowerRow
 */
export interface PowerRow {
    /**
     * 
     * @type {string}
     * @memberof PowerRow
     */
    power: string;
    /**
     * 
     * @type {boolean}
     * @memberof PowerRow
     */
    purchasable: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PowerRow
     */
    unlocksUnit: boolean;
    /**
     * 
     * @type {number}
     * @memberof PowerRow
     */
    gamesPicked: number;
    /**
     * 
     * @type {number}
     * @memberof PowerRow
     */
    pickRate: number;
    /**
     * 
     * @type {number}
     * @memberof PowerRow
     */
    groupPickRate: number;
    /**
     * 
     * @type {number}
     * @memberof PowerRow
     */
    avgPickMinute?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PowerRow
     */
    groupAvgPickMinute?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PowerRow
     */
    avgLevels: number;
    /**
     * 
     * @type {number}
     * @memberof PowerRow
     */
    groupAvgLevels: number;
    /**
     * 
     * @type {number}
     * @memberof PowerRow
     */
    uses: number;
    /**
     * 
     * @type {number}
     * @memberof PowerRow
     */
    usesPerMinute: number;
    /**
     * 
     * @type {number}
     * @memberof PowerRow
     */
    groupUsesPerMinute: number;
}

/**
 * Check if a given object implements the PowerRow interface.
 */
export function instanceOfPowerRow(value: object): value is PowerRow {
    if (!('power' in value) || value['power'] === undefined) return false;
    if (!('purchasable' in value) || value['purchasable'] === undefined) return false;
    if (!('unlocksUnit' in value) || value['unlocksUnit'] === undefined) return false;
    if (!('gamesPicked' in value) || value['gamesPicked'] === undefined) return false;
    if (!('pickRate' in value) || value['pickRate'] === undefined) return false;
    if (!('groupPickRate' in value) || value['groupPickRate'] === undefined) return false;
    if (!('avgLevels' in value) || value['avgLevels'] === undefined) return false;
    if (!('groupAvgLevels' in value) || value['groupAvgLevels'] === undefined) return false;
    if (!('uses' in value) || value['uses'] === undefined) return false;
    if (!('usesPerMinute' in value) || value['usesPerMinute'] === undefined) return false;
    if (!('groupUsesPerMinute' in value) || value['groupUsesPerMinute'] === undefined) return false;
    return true;
}

export function PowerRowFromJSON(json: any): PowerRow {
    return PowerRowFromJSONTyped(json, false);
}

export function PowerRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): PowerRow {
    if (json == null) {
        return json;
    }
    return {
        
        'power': json['power'],
        'purchasable': json['purchasable'],
        'unlocksUnit': json['unlocksUnit'],
        'gamesPicked': json['gamesPicked'],
        'pickRate': json['pickRate'],
        'groupPickRate': json['groupPickRate'],
        'avgPickMinute': json['avgPickMinute'] == null ? undefined : json['avgPickMinute'],
        'groupAvgPickMinute': json['groupAvgPickMinute'] == null ? undefined : json['groupAvgPickMinute'],
        'avgLevels': json['avgLevels'],
        'groupAvgLevels': json['groupAvgLevels'],
        'uses': json['uses'],
        'usesPerMinute': json['usesPerMinute'],
        'groupUsesPerMinute': json['groupUsesPerMinute'],
    };
}

export function PowerRowToJSON(json: any): PowerRow {
    return PowerRowToJSONTyped(json, false);
}

export function PowerRowToJSONTyped(value?: PowerRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'power': value['power'],
        'purchasable': value['purchasable'],
        'unlocksUnit': value['unlocksUnit'],
        'gamesPicked': value['gamesPicked'],
        'pickRate': value['pickRate'],
        'groupPickRate': value['groupPickRate'],
        'avgPickMinute': value['avgPickMinute'],
        'groupAvgPickMinute': value['groupAvgPickMinute'],
        'avgLevels': value['avgLevels'],
        'groupAvgLevels': value['groupAvgLevels'],
        'uses': value['uses'],
        'usesPerMinute': value['usesPerMinute'],
        'groupUsesPerMinute': value['groupUsesPerMinute'],
    };
}

