/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * How often one power was activated, by one player, in one match.
 * @export
 * @interface PowerUse
 */
export interface PowerUse {
    /**
     * 
     * @type {string}
     * @memberof PowerUse
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PowerUse
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof PowerUse
     */
    firstMinute?: number | null;
}

/**
 * Check if a given object implements the PowerUse interface.
 */
export function instanceOfPowerUse(value: object): value is PowerUse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function PowerUseFromJSON(json: any): PowerUse {
    return PowerUseFromJSONTyped(json, false);
}

export function PowerUseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PowerUse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'count': json['count'],
        'firstMinute': json['firstMinute'] == null ? undefined : json['firstMinute'],
    };
}

export function PowerUseToJSON(json: any): PowerUse {
    return PowerUseToJSONTyped(json, false);
}

export function PowerUseToJSONTyped(value?: PowerUse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'count': value['count'],
        'firstMinute': value['firstMinute'],
    };
}

