/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One `PurchaseScience` order: a generals point spent.
 * 
 * Deliberately just the raw id and when it was bought. The *name* of a
 * science is a property of the game's science list, not of this match, and
 * `generals_powers` resolves it at read time - so identifying an id we
 * currently can't name is a one-line table edit rather than a
 * DETAILS_VERSION bump and a re-derivation of every cached match.
 * @export
 * @interface PowerPick
 */
export interface PowerPick {
    /**
     * 
     * @type {number}
     * @memberof PowerPick
     */
    atMinute: number;
    /**
     * 
     * @type {number}
     * @memberof PowerPick
     */
    scienceId: number;
}

/**
 * Check if a given object implements the PowerPick interface.
 */
export function instanceOfPowerPick(value: object): value is PowerPick {
    if (!('atMinute' in value) || value['atMinute'] === undefined) return false;
    if (!('scienceId' in value) || value['scienceId'] === undefined) return false;
    return true;
}

export function PowerPickFromJSON(json: any): PowerPick {
    return PowerPickFromJSONTyped(json, false);
}

export function PowerPickFromJSONTyped(json: any, ignoreDiscriminator: boolean): PowerPick {
    if (json == null) {
        return json;
    }
    return {
        
        'atMinute': json['atMinute'],
        'scienceId': json['scienceId'],
    };
}

export function PowerPickToJSON(json: any): PowerPick {
    return PowerPickToJSONTyped(json, false);
}

export function PowerPickToJSONTyped(value?: PowerPick | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'atMinute': value['atMinute'],
        'scienceId': value['scienceId'],
    };
}

