/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { General } from './General';
import {
    GeneralFromJSON,
    GeneralFromJSONTyped,
    GeneralToJSON,
    GeneralToJSONTyped,
} from './General';

/**
 * 
 * @export
 * @interface PredictPlayer
 */
export interface PredictPlayer {
    /**
     * 
     * @type {string}
     * @memberof PredictPlayer
     */
    name: string;
    /**
     * 
     * @type {General}
     * @memberof PredictPlayer
     */
    general: General;
    /**
     * 
     * @type {number}
     * @memberof PredictPlayer
     */
    team: number;
}



/**
 * Check if a given object implements the PredictPlayer interface.
 */
export function instanceOfPredictPlayer(value: object): value is PredictPlayer {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('general' in value) || value['general'] === undefined) return false;
    if (!('team' in value) || value['team'] === undefined) return false;
    return true;
}

export function PredictPlayerFromJSON(json: any): PredictPlayer {
    return PredictPlayerFromJSONTyped(json, false);
}

export function PredictPlayerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PredictPlayer {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'general': GeneralFromJSON(json['general']),
        'team': json['team'],
    };
}

export function PredictPlayerToJSON(json: any): PredictPlayer {
    return PredictPlayerToJSONTyped(json, false);
}

export function PredictPlayerToJSONTyped(value?: PredictPlayer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'general': GeneralToJSON(value['general']),
        'team': value['team'],
    };
}

