/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A top-3 behavioral standout among profiled players for one stat.
 * @export
 * @interface ProfileBadge
 */
export interface ProfileBadge {
    /**
     * 
     * @type {string}
     * @memberof ProfileBadge
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileBadge
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileBadge
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof ProfileBadge
     */
    value: number;
    /**
     * 
     * @type {number}
     * @memberof ProfileBadge
     */
    rank: number;
    /**
     * 
     * @type {ProfileBadgeTierEnum}
     * @memberof ProfileBadge
     */
    tier: ProfileBadgeTierEnum;
    /**
     * 
     * @type {number}
     * @memberof ProfileBadge
     */
    totalPlayers: number;
}


/**
 * @export
 */
export const ProfileBadgeTierEnum = {
    Gold: 'gold',
    Silver: 'silver',
    Bronze: 'bronze'
} as const;
export type ProfileBadgeTierEnum = typeof ProfileBadgeTierEnum[keyof typeof ProfileBadgeTierEnum];


/**
 * Check if a given object implements the ProfileBadge interface.
 */
export function instanceOfProfileBadge(value: object): value is ProfileBadge {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('tier' in value) || value['tier'] === undefined) return false;
    if (!('totalPlayers' in value) || value['totalPlayers'] === undefined) return false;
    return true;
}

export function ProfileBadgeFromJSON(json: any): ProfileBadge {
    return ProfileBadgeFromJSONTyped(json, false);
}

export function ProfileBadgeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileBadge {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'label': json['label'],
        'description': json['description'],
        'value': json['value'],
        'rank': json['rank'],
        'tier': json['tier'],
        'totalPlayers': json['totalPlayers'],
    };
}

export function ProfileBadgeToJSON(json: any): ProfileBadge {
    return ProfileBadgeToJSONTyped(json, false);
}

export function ProfileBadgeToJSONTyped(value?: ProfileBadge | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'label': value['label'],
        'description': value['description'],
        'value': value['value'],
        'rank': value['rank'],
        'tier': value['tier'],
        'totalPlayers': value['totalPlayers'],
    };
}

