/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PushMapResult
 */
export interface PushMapResult {
    /**
     * 
     * @type {string}
     * @memberof PushMapResult
     */
    mapName: string;
    /**
     * 
     * @type {string}
     * @memberof PushMapResult
     */
    crc?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PushMapResult
     */
    pushed?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PushMapResult
     */
    alreadyPresent?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PushMapResult
     */
    error?: string | null;
}

/**
 * Check if a given object implements the PushMapResult interface.
 */
export function instanceOfPushMapResult(value: object): value is PushMapResult {
    if (!('mapName' in value) || value['mapName'] === undefined) return false;
    return true;
}

export function PushMapResultFromJSON(json: any): PushMapResult {
    return PushMapResultFromJSONTyped(json, false);
}

export function PushMapResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PushMapResult {
    if (json == null) {
        return json;
    }
    return {
        
        'mapName': json['map_name'],
        'crc': json['crc'] == null ? undefined : json['crc'],
        'pushed': json['pushed'] == null ? undefined : json['pushed'],
        'alreadyPresent': json['already_present'] == null ? undefined : json['already_present'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function PushMapResultToJSON(json: any): PushMapResult {
    return PushMapResultToJSONTyped(json, false);
}

export function PushMapResultToJSONTyped(value?: PushMapResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'map_name': value['mapName'],
        'crc': value['crc'],
        'pushed': value['pushed'],
        'already_present': value['alreadyPresent'],
        'error': value['error'],
    };
}

