/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PushMapResult } from './PushMapResult';
import {
    PushMapResultFromJSON,
    PushMapResultFromJSONTyped,
    PushMapResultToJSON,
    PushMapResultToJSONTyped,
} from './PushMapResult';

/**
 * 
 * @export
 * @interface PushMapsResponse
 */
export interface PushMapsResponse {
    /**
     * 
     * @type {number}
     * @memberof PushMapsResponse
     */
    requested: number;
    /**
     * 
     * @type {number}
     * @memberof PushMapsResponse
     */
    pushed: number;
    /**
     * 
     * @type {number}
     * @memberof PushMapsResponse
     */
    alreadyPresent?: number;
    /**
     * 
     * @type {Array<PushMapResult>}
     * @memberof PushMapsResponse
     */
    results?: Array<PushMapResult>;
}

/**
 * Check if a given object implements the PushMapsResponse interface.
 */
export function instanceOfPushMapsResponse(value: object): value is PushMapsResponse {
    if (!('requested' in value) || value['requested'] === undefined) return false;
    if (!('pushed' in value) || value['pushed'] === undefined) return false;
    return true;
}

export function PushMapsResponseFromJSON(json: any): PushMapsResponse {
    return PushMapsResponseFromJSONTyped(json, false);
}

export function PushMapsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PushMapsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requested': json['requested'],
        'pushed': json['pushed'],
        'alreadyPresent': json['already_present'] == null ? undefined : json['already_present'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(PushMapResultFromJSON)),
    };
}

export function PushMapsResponseToJSON(json: any): PushMapsResponse {
    return PushMapsResponseToJSONTyped(json, false);
}

export function PushMapsResponseToJSONTyped(value?: PushMapsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requested': value['requested'],
        'pushed': value['pushed'],
        'already_present': value['alreadyPresent'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(PushMapResultToJSON)),
    };
}

