/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReparseMapResult
 */
export interface ReparseMapResult {
    /**
     * 
     * @type {string}
     * @memberof ReparseMapResult
     */
    mapName: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReparseMapResult
     */
    wasMissing?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReparseMapResult
     */
    ok?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReparseMapResult
     */
    error?: string | null;
}

/**
 * Check if a given object implements the ReparseMapResult interface.
 */
export function instanceOfReparseMapResult(value: object): value is ReparseMapResult {
    if (!('mapName' in value) || value['mapName'] === undefined) return false;
    return true;
}

export function ReparseMapResultFromJSON(json: any): ReparseMapResult {
    return ReparseMapResultFromJSONTyped(json, false);
}

export function ReparseMapResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReparseMapResult {
    if (json == null) {
        return json;
    }
    return {
        
        'mapName': json['map_name'],
        'wasMissing': json['was_missing'] == null ? undefined : json['was_missing'],
        'ok': json['ok'] == null ? undefined : json['ok'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ReparseMapResultToJSON(json: any): ReparseMapResult {
    return ReparseMapResultToJSONTyped(json, false);
}

export function ReparseMapResultToJSONTyped(value?: ReparseMapResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'map_name': value['mapName'],
        'was_missing': value['wasMissing'],
        'ok': value['ok'],
        'error': value['error'],
    };
}

