/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Public API representation of ReplayFile
 * @export
 * @interface ReplayFileSchema
 */
export interface ReplayFileSchema {
    /**
     * 
     * @type {string}
     * @memberof ReplayFileSchema
     */
    originalUrl: string;
    /**
     * 
     * @type {string}
     * @memberof ReplayFileSchema
     */
    s3Uri: string;
    /**
     * 
     * @type {string}
     * @memberof ReplayFileSchema
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ReplayFileSchema
     */
    playerId: string;
    /**
     * 
     * @type {Date}
     * @memberof ReplayFileSchema
     */
    discoveredAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ReplayFileSchema
     */
    sourceDate: Date;
}

/**
 * Check if a given object implements the ReplayFileSchema interface.
 */
export function instanceOfReplayFileSchema(value: object): value is ReplayFileSchema {
    if (!('originalUrl' in value) || value['originalUrl'] === undefined) return false;
    if (!('s3Uri' in value) || value['s3Uri'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('playerId' in value) || value['playerId'] === undefined) return false;
    if (!('discoveredAt' in value) || value['discoveredAt'] === undefined) return false;
    if (!('sourceDate' in value) || value['sourceDate'] === undefined) return false;
    return true;
}

export function ReplayFileSchemaFromJSON(json: any): ReplayFileSchema {
    return ReplayFileSchemaFromJSONTyped(json, false);
}

export function ReplayFileSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplayFileSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'originalUrl': json['original_url'],
        's3Uri': json['s3_uri'],
        'status': json['status'],
        'playerId': json['player_id'],
        'discoveredAt': (new Date(json['discovered_at'])),
        'sourceDate': (new Date(json['source_date'])),
    };
}

export function ReplayFileSchemaToJSON(json: any): ReplayFileSchema {
    return ReplayFileSchemaToJSONTyped(json, false);
}

export function ReplayFileSchemaToJSONTyped(value?: ReplayFileSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'original_url': value['originalUrl'],
        's3_uri': value['s3Uri'],
        'status': value['status'],
        'player_id': value['playerId'],
        'discovered_at': value['discoveredAt'].toISOString(),
        'source_date': value['sourceDate'].toISOString().substring(0,10),
    };
}

