/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A parsed replay still missing player stats (backfill work item).
 * @export
 * @interface ReplayWithoutPlayerStats
 */
export interface ReplayWithoutPlayerStats {
    /**
     * 
     * @type {number}
     * @memberof ReplayWithoutPlayerStats
     */
    matchId: number;
    /**
     * 
     * @type {string}
     * @memberof ReplayWithoutPlayerStats
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof ReplayWithoutPlayerStats
     */
    s3Path: string;
    /**
     * 
     * @type {string}
     * @memberof ReplayWithoutPlayerStats
     */
    version?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReplayWithoutPlayerStats
     */
    presignedUrl: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReplayWithoutPlayerStats
     */
    allReplayUrls: Array<string>;
}

/**
 * Check if a given object implements the ReplayWithoutPlayerStats interface.
 */
export function instanceOfReplayWithoutPlayerStats(value: object): value is ReplayWithoutPlayerStats {
    if (!('matchId' in value) || value['matchId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('s3Path' in value) || value['s3Path'] === undefined) return false;
    if (!('presignedUrl' in value) || value['presignedUrl'] === undefined) return false;
    if (!('allReplayUrls' in value) || value['allReplayUrls'] === undefined) return false;
    return true;
}

export function ReplayWithoutPlayerStatsFromJSON(json: any): ReplayWithoutPlayerStats {
    return ReplayWithoutPlayerStatsFromJSONTyped(json, false);
}

export function ReplayWithoutPlayerStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplayWithoutPlayerStats {
    if (json == null) {
        return json;
    }
    return {
        
        'matchId': json['match_id'],
        'url': json['url'],
        's3Path': json['s3_path'],
        'version': json['version'] == null ? undefined : json['version'],
        'presignedUrl': json['presigned_url'],
        'allReplayUrls': json['all_replay_urls'],
    };
}

export function ReplayWithoutPlayerStatsToJSON(json: any): ReplayWithoutPlayerStats {
    return ReplayWithoutPlayerStatsToJSONTyped(json, false);
}

export function ReplayWithoutPlayerStatsToJSONTyped(value?: ReplayWithoutPlayerStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'match_id': value['matchId'],
        'url': value['url'],
        's3_path': value['s3Path'],
        'version': value['version'],
        'presigned_url': value['presignedUrl'],
        'all_replay_urls': value['allReplayUrls'],
    };
}

