/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseReparseRecentApiReparseRecentPostValue
 */
export interface ResponseReparseRecentApiReparseRecentPostValue {
}

/**
 * Check if a given object implements the ResponseReparseRecentApiReparseRecentPostValue interface.
 */
export function instanceOfResponseReparseRecentApiReparseRecentPostValue(value: object): value is ResponseReparseRecentApiReparseRecentPostValue {
    return true;
}

export function ResponseReparseRecentApiReparseRecentPostValueFromJSON(json: any): ResponseReparseRecentApiReparseRecentPostValue {
    return ResponseReparseRecentApiReparseRecentPostValueFromJSONTyped(json, false);
}

export function ResponseReparseRecentApiReparseRecentPostValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseReparseRecentApiReparseRecentPostValue {
    return json;
}

export function ResponseReparseRecentApiReparseRecentPostValueToJSON(json: any): ResponseReparseRecentApiReparseRecentPostValue {
    return ResponseReparseRecentApiReparseRecentPostValueToJSONTyped(json, false);
}

export function ResponseReparseRecentApiReparseRecentPostValueToJSONTyped(value?: ResponseReparseRecentApiReparseRecentPostValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

