/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ParsedReplayJsonSchema } from './ParsedReplayJsonSchema';
import {
    ParsedReplayJsonSchemaFromJSON,
    ParsedReplayJsonSchemaFromJSONTyped,
    ParsedReplayJsonSchemaToJSON,
    ParsedReplayJsonSchemaToJSONTyped,
} from './ParsedReplayJsonSchema';
import type { ReplayFileSchema } from './ReplayFileSchema';
import {
    ReplayFileSchemaFromJSON,
    ReplayFileSchemaFromJSONTyped,
    ReplayFileSchemaToJSON,
    ReplayFileSchemaToJSONTyped,
} from './ReplayFileSchema';

/**
 * 
 * @export
 * @interface ResponseGetFilesForMatchIdApiFilesForMatchGetValue
 */
export interface ResponseGetFilesForMatchIdApiFilesForMatchGetValue {
}

/**
 * Check if a given object implements the ResponseGetFilesForMatchIdApiFilesForMatchGetValue interface.
 */
export function instanceOfResponseGetFilesForMatchIdApiFilesForMatchGetValue(value: object): value is ResponseGetFilesForMatchIdApiFilesForMatchGetValue {
    return true;
}

export function ResponseGetFilesForMatchIdApiFilesForMatchGetValueFromJSON(json: any): ResponseGetFilesForMatchIdApiFilesForMatchGetValue {
    return ResponseGetFilesForMatchIdApiFilesForMatchGetValueFromJSONTyped(json, false);
}

export function ResponseGetFilesForMatchIdApiFilesForMatchGetValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseGetFilesForMatchIdApiFilesForMatchGetValue {
    return json;
}

export function ResponseGetFilesForMatchIdApiFilesForMatchGetValueToJSON(json: any): ResponseGetFilesForMatchIdApiFilesForMatchGetValue {
    return ResponseGetFilesForMatchIdApiFilesForMatchGetValueToJSONTyped(json, false);
}

export function ResponseGetFilesForMatchIdApiFilesForMatchGetValueToJSONTyped(value?: ResponseGetFilesForMatchIdApiFilesForMatchGetValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

