/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeedSource
 */
export interface SeedSource {
    /**
     * 
     * @type {SeedSourceKindEnum}
     * @memberof SeedSource
     */
    kind?: SeedSourceKindEnum;
    /**
     * 
     * @type {number}
     * @memberof SeedSource
     */
    seed: number;
}


/**
 * @export
 */
export const SeedSourceKindEnum = {
    Seed: 'seed'
} as const;
export type SeedSourceKindEnum = typeof SeedSourceKindEnum[keyof typeof SeedSourceKindEnum];


/**
 * Check if a given object implements the SeedSource interface.
 */
export function instanceOfSeedSource(value: object): value is SeedSource {
    if (!('seed' in value) || value['seed'] === undefined) return false;
    return true;
}

export function SeedSourceFromJSON(json: any): SeedSource {
    return SeedSourceFromJSONTyped(json, false);
}

export function SeedSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeedSource {
    if (json == null) {
        return json;
    }
    return {
        
        'kind': json['kind'] == null ? undefined : json['kind'],
        'seed': json['seed'],
    };
}

export function SeedSourceToJSON(json: any): SeedSource {
    return SeedSourceToJSONTyped(json, false);
}

export function SeedSourceToJSONTyped(value?: SeedSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kind': value['kind'],
        'seed': value['seed'],
    };
}

