/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelectPlayerRequest
 */
export interface SelectPlayerRequest {
    /**
     * 
     * @type {string}
     * @memberof SelectPlayerRequest
     */
    playerName: string;
}

/**
 * Check if a given object implements the SelectPlayerRequest interface.
 */
export function instanceOfSelectPlayerRequest(value: object): value is SelectPlayerRequest {
    if (!('playerName' in value) || value['playerName'] === undefined) return false;
    return true;
}

export function SelectPlayerRequestFromJSON(json: any): SelectPlayerRequest {
    return SelectPlayerRequestFromJSONTyped(json, false);
}

export function SelectPlayerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectPlayerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'playerName': json['player_name'],
    };
}

export function SelectPlayerRequestToJSON(json: any): SelectPlayerRequest {
    return SelectPlayerRequestToJSONTyped(json, false);
}

export function SelectPlayerRequestToJSONTyped(value?: SelectPlayerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player_name': value['playerName'],
    };
}

