/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShortPlayerRating
 */
export interface ShortPlayerRating {
    /**
     * 
     * @type {number}
     * @memberof ShortPlayerRating
     */
    mu: number;
    /**
     * 
     * @type {number}
     * @memberof ShortPlayerRating
     */
    sigma: number;
    /**
     * 
     * @type {Date}
     * @memberof ShortPlayerRating
     */
    atdate?: Date | null;
}

/**
 * Check if a given object implements the ShortPlayerRating interface.
 */
export function instanceOfShortPlayerRating(value: object): value is ShortPlayerRating {
    if (!('mu' in value) || value['mu'] === undefined) return false;
    if (!('sigma' in value) || value['sigma'] === undefined) return false;
    return true;
}

export function ShortPlayerRatingFromJSON(json: any): ShortPlayerRating {
    return ShortPlayerRatingFromJSONTyped(json, false);
}

export function ShortPlayerRatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShortPlayerRating {
    if (json == null) {
        return json;
    }
    return {
        
        'mu': json['mu'],
        'sigma': json['sigma'],
        'atdate': json['atdate'] == null ? undefined : (new Date(json['atdate'])),
    };
}

export function ShortPlayerRatingToJSON(json: any): ShortPlayerRating {
    return ShortPlayerRatingToJSONTyped(json, false);
}

export function ShortPlayerRatingToJSONTyped(value?: ShortPlayerRating | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mu': value['mu'],
        'sigma': value['sigma'],
        'atdate': value['atdate'] == null ? value['atdate'] : value['atdate'].toISOString().substring(0,10),
    };
}

