/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LoserOfSource } from './LoserOfSource';
import {
    instanceOfLoserOfSource,
    LoserOfSourceFromJSON,
    LoserOfSourceFromJSONTyped,
    LoserOfSourceToJSON,
} from './LoserOfSource';
import type { SeedSource } from './SeedSource';
import {
    instanceOfSeedSource,
    SeedSourceFromJSON,
    SeedSourceFromJSONTyped,
    SeedSourceToJSON,
} from './SeedSource';
import type { WinnerOfSource } from './WinnerOfSource';
import {
    instanceOfWinnerOfSource,
    WinnerOfSourceFromJSON,
    WinnerOfSourceFromJSONTyped,
    WinnerOfSourceToJSON,
} from './WinnerOfSource';

/**
 * @type SourceA
 * 
 * @export
 */
export type SourceA = { kind: 'loser' } & LoserOfSource | { kind: 'seed' } & SeedSource | { kind: 'winner' } & WinnerOfSource;

export function SourceAFromJSON(json: any): SourceA {
    return SourceAFromJSONTyped(json, false);
}

export function SourceAFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceA {
    if (json == null) {
        return json;
    }
    switch (json['kind']) {
        case 'loser':
            return Object.assign({}, LoserOfSourceFromJSONTyped(json, true), { kind: 'loser' } as const);
        case 'seed':
            return Object.assign({}, SeedSourceFromJSONTyped(json, true), { kind: 'seed' } as const);
        case 'winner':
            return Object.assign({}, WinnerOfSourceFromJSONTyped(json, true), { kind: 'winner' } as const);
        default:
            return json;
    }
}

export function SourceAToJSON(json: any): any {
    return SourceAToJSONTyped(json, false);
}

export function SourceAToJSONTyped(value?: SourceA | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['kind']) {
        case 'loser':
            return Object.assign({}, LoserOfSourceToJSON(value), { kind: 'loser' } as const);
        case 'seed':
            return Object.assign({}, SeedSourceToJSON(value), { kind: 'seed' } as const);
        case 'winner':
            return Object.assign({}, WinnerOfSourceToJSON(value), { kind: 'winner' } as const);
        default:
            return value;
    }
}

