/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Spent } from './Spent';
import {
    SpentFromJSON,
    SpentFromJSONTyped,
    SpentToJSON,
    SpentToJSONTyped,
} from './Spent';

/**
 * 
 * @export
 * @interface SpentOverTime
 */
export interface SpentOverTime {
    /**
     * 
     * @type {Array<Spent>}
     * @memberof SpentOverTime
     */
    buildings: Array<Spent>;
    /**
     * 
     * @type {Array<Spent>}
     * @memberof SpentOverTime
     */
    units: Array<Spent>;
    /**
     * 
     * @type {Array<Spent>}
     * @memberof SpentOverTime
     */
    upgrades: Array<Spent>;
    /**
     * 
     * @type {Array<Spent>}
     * @memberof SpentOverTime
     */
    total: Array<Spent>;
}

/**
 * Check if a given object implements the SpentOverTime interface.
 */
export function instanceOfSpentOverTime(value: object): value is SpentOverTime {
    if (!('buildings' in value) || value['buildings'] === undefined) return false;
    if (!('units' in value) || value['units'] === undefined) return false;
    if (!('upgrades' in value) || value['upgrades'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function SpentOverTimeFromJSON(json: any): SpentOverTime {
    return SpentOverTimeFromJSONTyped(json, false);
}

export function SpentOverTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpentOverTime {
    if (json == null) {
        return json;
    }
    return {
        
        'buildings': ((json['buildings'] as Array<any>).map(SpentFromJSON)),
        'units': ((json['units'] as Array<any>).map(SpentFromJSON)),
        'upgrades': ((json['upgrades'] as Array<any>).map(SpentFromJSON)),
        'total': ((json['total'] as Array<any>).map(SpentFromJSON)),
    };
}

export function SpentOverTimeToJSON(json: any): SpentOverTime {
    return SpentOverTimeToJSONTyped(json, false);
}

export function SpentOverTimeToJSONTyped(value?: SpentOverTime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'buildings': ((value['buildings'] as Array<any>).map(SpentToJSON)),
        'units': ((value['units'] as Array<any>).map(SpentToJSON)),
        'upgrades': ((value['upgrades'] as Array<any>).map(SpentToJSON)),
        'total': ((value['total'] as Array<any>).map(SpentToJSON)),
    };
}

