/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Team = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_MINUS_1: -1
} as const;
export type Team = typeof Team[keyof typeof Team];


export function instanceOfTeam(value: any): boolean {
    for (const key in Team) {
        if (Object.prototype.hasOwnProperty.call(Team, key)) {
            if (Team[key as keyof typeof Team] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TeamFromJSON(json: any): Team {
    return TeamFromJSONTyped(json, false);
}

export function TeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): Team {
    return json as Team;
}

export function TeamToJSON(value?: Team | null): any {
    return value as any;
}

export function TeamToJSONTyped(value: any, ignoreDiscriminator: boolean): Team {
    return value as Team;
}

