/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeammateProfileStat
 */
export interface TeammateProfileStat {
    /**
     * 
     * @type {string}
     * @memberof TeammateProfileStat
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof TeammateProfileStat
     */
    gamesTogether: number;
    /**
     * 
     * @type {number}
     * @memberof TeammateProfileStat
     */
    winsTogether: number;
    /**
     * 
     * @type {number}
     * @memberof TeammateProfileStat
     */
    synergy?: number | null;
}

/**
 * Check if a given object implements the TeammateProfileStat interface.
 */
export function instanceOfTeammateProfileStat(value: object): value is TeammateProfileStat {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('gamesTogether' in value) || value['gamesTogether'] === undefined) return false;
    if (!('winsTogether' in value) || value['winsTogether'] === undefined) return false;
    return true;
}

export function TeammateProfileStatFromJSON(json: any): TeammateProfileStat {
    return TeammateProfileStatFromJSONTyped(json, false);
}

export function TeammateProfileStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeammateProfileStat {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'gamesTogether': json['gamesTogether'],
        'winsTogether': json['winsTogether'],
        'synergy': json['synergy'] == null ? undefined : json['synergy'],
    };
}

export function TeammateProfileStatToJSON(json: any): TeammateProfileStat {
    return TeammateProfileStatToJSONTyped(json, false);
}

export function TeammateProfileStatToJSONTyped(value?: TeammateProfileStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'gamesTogether': value['gamesTogether'],
        'winsTogether': value['winsTogether'],
        'synergy': value['synergy'],
    };
}

