/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Value } from './Value';
import {
    ValueFromJSON,
    ValueFromJSONTyped,
    ValueToJSON,
    ValueToJSONTyped,
} from './Value';

/**
 * 
 * @export
 * @interface TournamentStat
 */
export interface TournamentStat {
    /**
     * 
     * @type {string}
     * @memberof TournamentStat
     */
    statName: string;
    /**
     * 
     * @type {Value}
     * @memberof TournamentStat
     */
    value?: Value | null;
    /**
     * 
     * @type {string}
     * @memberof TournamentStat
     */
    player?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TournamentStat
     */
    matchId?: number | null;
}

/**
 * Check if a given object implements the TournamentStat interface.
 */
export function instanceOfTournamentStat(value: object): value is TournamentStat {
    if (!('statName' in value) || value['statName'] === undefined) return false;
    return true;
}

export function TournamentStatFromJSON(json: any): TournamentStat {
    return TournamentStatFromJSONTyped(json, false);
}

export function TournamentStatFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentStat {
    if (json == null) {
        return json;
    }
    return {
        
        'statName': json['stat_name'],
        'value': json['value'] == null ? undefined : ValueFromJSON(json['value']),
        'player': json['player'] == null ? undefined : json['player'],
        'matchId': json['match_id'] == null ? undefined : json['match_id'],
    };
}

export function TournamentStatToJSON(json: any): TournamentStat {
    return TournamentStatToJSONTyped(json, false);
}

export function TournamentStatToJSONTyped(value?: TournamentStat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stat_name': value['statName'],
        'value': ValueToJSON(value['value']),
        'player': value['player'],
        'match_id': value['matchId'],
    };
}

