/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WinLoss } from './WinLoss';
import {
    WinLossFromJSON,
    WinLossFromJSONTyped,
    WinLossToJSON,
    WinLossToJSONTyped,
} from './WinLoss';
import type { MatchupResultOutput } from './MatchupResultOutput';
import {
    MatchupResultOutputFromJSON,
    MatchupResultOutputFromJSONTyped,
    MatchupResultOutputToJSON,
    MatchupResultOutputToJSONTyped,
} from './MatchupResultOutput';
import type { Tournament } from './Tournament';
import {
    TournamentFromJSON,
    TournamentFromJSONTyped,
    TournamentToJSON,
    TournamentToJSONTyped,
} from './Tournament';

/**
 * 
 * @export
 * @interface TournamentResultOutput
 */
export interface TournamentResultOutput {
    /**
     * 
     * @type {Tournament}
     * @memberof TournamentResultOutput
     */
    tournament: Tournament;
    /**
     * 
     * @type {Array<MatchupResultOutput>}
     * @memberof TournamentResultOutput
     */
    matchups: Array<MatchupResultOutput>;
    /**
     * 
     * @type {{ [key: string]: WinLoss; }}
     * @memberof TournamentResultOutput
     */
    records: { [key: string]: WinLoss; };
}

/**
 * Check if a given object implements the TournamentResultOutput interface.
 */
export function instanceOfTournamentResultOutput(value: object): value is TournamentResultOutput {
    if (!('tournament' in value) || value['tournament'] === undefined) return false;
    if (!('matchups' in value) || value['matchups'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function TournamentResultOutputFromJSON(json: any): TournamentResultOutput {
    return TournamentResultOutputFromJSONTyped(json, false);
}

export function TournamentResultOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentResultOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'tournament': TournamentFromJSON(json['tournament']),
        'matchups': ((json['matchups'] as Array<any>).map(MatchupResultOutputFromJSON)),
        'records': (mapValues(json['records'], WinLossFromJSON)),
    };
}

export function TournamentResultOutputToJSON(json: any): TournamentResultOutput {
    return TournamentResultOutputToJSONTyped(json, false);
}

export function TournamentResultOutputToJSONTyped(value?: TournamentResultOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tournament': TournamentToJSON(value['tournament']),
        'matchups': ((value['matchups'] as Array<any>).map(MatchupResultOutputToJSON)),
        'records': (mapValues(value['records'], WinLossToJSON)),
    };
}

