/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WinLoss } from './WinLoss';
import {
    WinLossFromJSON,
    WinLossFromJSONTyped,
    WinLossToJSON,
    WinLossToJSONTyped,
} from './WinLoss';
import type { Tournament } from './Tournament';
import {
    TournamentFromJSON,
    TournamentFromJSONTyped,
    TournamentToJSON,
    TournamentToJSONTyped,
} from './Tournament';
import type { MatchupResult } from './MatchupResult';
import {
    MatchupResultFromJSON,
    MatchupResultFromJSONTyped,
    MatchupResultToJSON,
    MatchupResultToJSONTyped,
} from './MatchupResult';

/**
 * 
 * @export
 * @interface TournamentResult
 */
export interface TournamentResult {
    /**
     * 
     * @type {Tournament}
     * @memberof TournamentResult
     */
    tournament: Tournament;
    /**
     * 
     * @type {Array<MatchupResult>}
     * @memberof TournamentResult
     */
    matchups: Array<MatchupResult>;
    /**
     * 
     * @type {{ [key: string]: WinLoss; }}
     * @memberof TournamentResult
     */
    records: { [key: string]: WinLoss; };
}

/**
 * Check if a given object implements the TournamentResult interface.
 */
export function instanceOfTournamentResult(value: object): value is TournamentResult {
    if (!('tournament' in value) || value['tournament'] === undefined) return false;
    if (!('matchups' in value) || value['matchups'] === undefined) return false;
    if (!('records' in value) || value['records'] === undefined) return false;
    return true;
}

export function TournamentResultFromJSON(json: any): TournamentResult {
    return TournamentResultFromJSONTyped(json, false);
}

export function TournamentResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentResult {
    if (json == null) {
        return json;
    }
    return {
        
        'tournament': TournamentFromJSON(json['tournament']),
        'matchups': ((json['matchups'] as Array<any>).map(MatchupResultFromJSON)),
        'records': (mapValues(json['records'], WinLossFromJSON)),
    };
}

export function TournamentResultToJSON(json: any): TournamentResult {
    return TournamentResultToJSONTyped(json, false);
}

export function TournamentResultToJSONTyped(value?: TournamentResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tournament': TournamentToJSON(value['tournament']),
        'matchups': ((value['matchups'] as Array<any>).map(MatchupResultToJSON)),
        'records': (mapValues(value['records'], WinLossToJSON)),
    };
}

