/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { General } from './General';
import {
    GeneralFromJSON,
    GeneralFromJSONTyped,
    GeneralToJSON,
    GeneralToJSONTyped,
} from './General';

/**
 * A pick rate that stands out from the rest of the group.
 * 
 * `surprise` is the gap in pick rate scaled by how much evidence there is for
 * it - a binomial z-score against the group's rate. It exists so one game of
 * something odd doesn't outrank a habit held over thirty.
 * @export
 * @interface UnusualPick
 */
export interface UnusualPick {
    /**
     * 
     * @type {General}
     * @memberof UnusualPick
     */
    general: General;
    /**
     * 
     * @type {string}
     * @memberof UnusualPick
     */
    power: string;
    /**
     * 
     * @type {number}
     * @memberof UnusualPick
     */
    games: number;
    /**
     * 
     * @type {number}
     * @memberof UnusualPick
     */
    pickRate: number;
    /**
     * 
     * @type {number}
     * @memberof UnusualPick
     */
    groupPickRate: number;
    /**
     * 
     * @type {number}
     * @memberof UnusualPick
     */
    surprise: number;
    /**
     * 
     * @type {string}
     * @memberof UnusualPick
     */
    direction: string;
}



/**
 * Check if a given object implements the UnusualPick interface.
 */
export function instanceOfUnusualPick(value: object): value is UnusualPick {
    if (!('general' in value) || value['general'] === undefined) return false;
    if (!('power' in value) || value['power'] === undefined) return false;
    if (!('games' in value) || value['games'] === undefined) return false;
    if (!('pickRate' in value) || value['pickRate'] === undefined) return false;
    if (!('groupPickRate' in value) || value['groupPickRate'] === undefined) return false;
    if (!('surprise' in value) || value['surprise'] === undefined) return false;
    if (!('direction' in value) || value['direction'] === undefined) return false;
    return true;
}

export function UnusualPickFromJSON(json: any): UnusualPick {
    return UnusualPickFromJSONTyped(json, false);
}

export function UnusualPickFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnusualPick {
    if (json == null) {
        return json;
    }
    return {
        
        'general': GeneralFromJSON(json['general']),
        'power': json['power'],
        'games': json['games'],
        'pickRate': json['pickRate'],
        'groupPickRate': json['groupPickRate'],
        'surprise': json['surprise'],
        'direction': json['direction'],
    };
}

export function UnusualPickToJSON(json: any): UnusualPick {
    return UnusualPickToJSONTyped(json, false);
}

export function UnusualPickToJSONTyped(value?: UnusualPick | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'general': GeneralToJSON(value['general']),
        'power': value['power'],
        'games': value['games'],
        'pickRate': value['pickRate'],
        'groupPickRate': value['groupPickRate'],
        'surprise': value['surprise'],
        'direction': value['direction'],
    };
}

