/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpgradeEvent
 */
export interface UpgradeEvent {
    /**
     * 
     * @type {string}
     * @memberof UpgradeEvent
     */
    playerName: string;
    /**
     * 
     * @type {number}
     * @memberof UpgradeEvent
     */
    timecode?: number;
    /**
     * 
     * @type {string}
     * @memberof UpgradeEvent
     */
    upgradeName: string;
    /**
     * 
     * @type {number}
     * @memberof UpgradeEvent
     */
    cost: number;
    /**
     * 
     * @type {number}
     * @memberof UpgradeEvent
     */
    atMinute: number;
}

/**
 * Check if a given object implements the UpgradeEvent interface.
 */
export function instanceOfUpgradeEvent(value: object): value is UpgradeEvent {
    if (!('playerName' in value) || value['playerName'] === undefined) return false;
    if (!('upgradeName' in value) || value['upgradeName'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('atMinute' in value) || value['atMinute'] === undefined) return false;
    return true;
}

export function UpgradeEventFromJSON(json: any): UpgradeEvent {
    return UpgradeEventFromJSONTyped(json, false);
}

export function UpgradeEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpgradeEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'playerName': json['playerName'],
        'timecode': json['timecode'] == null ? undefined : json['timecode'],
        'upgradeName': json['upgradeName'],
        'cost': json['cost'],
        'atMinute': json['atMinute'],
    };
}

export function UpgradeEventToJSON(json: any): UpgradeEvent {
    return UpgradeEventToJSONTyped(json, false);
}

export function UpgradeEventToJSONTyped(value?: UpgradeEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playerName': value['playerName'],
        'timecode': value['timecode'],
        'upgradeName': value['upgradeName'],
        'cost': value['cost'],
        'atMinute': value['atMinute'],
    };
}

