/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Team } from './Team';
import {
    TeamFromJSON,
    TeamFromJSONTyped,
    TeamToJSON,
    TeamToJSONTyped,
} from './Team';

/**
 * 
 * @export
 * @interface WinnerOverride
 */
export interface WinnerOverride {
    /**
     * 
     * @type {number}
     * @memberof WinnerOverride
     */
    matchId: number;
    /**
     * 
     * @type {Team}
     * @memberof WinnerOverride
     */
    winningTeamId: Team;
    /**
     * 
     * @type {string}
     * @memberof WinnerOverride
     */
    incomplete?: string | null;
}



/**
 * Check if a given object implements the WinnerOverride interface.
 */
export function instanceOfWinnerOverride(value: object): value is WinnerOverride {
    if (!('matchId' in value) || value['matchId'] === undefined) return false;
    if (!('winningTeamId' in value) || value['winningTeamId'] === undefined) return false;
    return true;
}

export function WinnerOverrideFromJSON(json: any): WinnerOverride {
    return WinnerOverrideFromJSONTyped(json, false);
}

export function WinnerOverrideFromJSONTyped(json: any, ignoreDiscriminator: boolean): WinnerOverride {
    if (json == null) {
        return json;
    }
    return {
        
        'matchId': json['match_id'],
        'winningTeamId': TeamFromJSON(json['winning_team_id']),
        'incomplete': json['incomplete'] == null ? undefined : json['incomplete'],
    };
}

export function WinnerOverrideToJSON(json: any): WinnerOverride {
    return WinnerOverrideToJSONTyped(json, false);
}

export function WinnerOverrideToJSONTyped(value?: WinnerOverride | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'match_id': value['matchId'],
        'winning_team_id': TeamToJSON(value['winningTeamId']),
        'incomplete': value['incomplete'],
    };
}

