/* tslint:disable */
/* eslint-disable */
/**
 * radarvan
 * Stats for generals
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WinProbPoint
 */
export interface WinProbPoint {
    /**
     * 
     * @type {number}
     * @memberof WinProbPoint
     */
    atMinute: number;
    /**
     * 
     * @type {number}
     * @memberof WinProbPoint
     */
    probTeamA: number;
}

/**
 * Check if a given object implements the WinProbPoint interface.
 */
export function instanceOfWinProbPoint(value: object): value is WinProbPoint {
    if (!('atMinute' in value) || value['atMinute'] === undefined) return false;
    if (!('probTeamA' in value) || value['probTeamA'] === undefined) return false;
    return true;
}

export function WinProbPointFromJSON(json: any): WinProbPoint {
    return WinProbPointFromJSONTyped(json, false);
}

export function WinProbPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): WinProbPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'atMinute': json['at_minute'],
        'probTeamA': json['prob_team_a'],
    };
}

export function WinProbPointToJSON(json: any): WinProbPoint {
    return WinProbPointToJSONTyped(json, false);
}

export function WinProbPointToJSONTyped(value?: WinProbPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'at_minute': value['atMinute'],
        'prob_team_a': value['probTeamA'],
    };
}

